// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.operations;

import io.github.primelib.jira.datacenter.client.auth.AuthMethod;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Delete2IssueByIssueIdOrKeyWorklogByIdV1
 * <p>
 * Deletes a worklog from an issue.
 * 
 * Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:**
 * 
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  *Delete all worklogs*[ project permission](https://confluence.atlassian.com/x/yodKLg) to delete any worklog or *Delete own worklogs* to delete worklogs created by the user,
 *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID or key of the issue.
     *
     */
    @NonNull
    private String issueIdOrKey;

    /**
     * The ID of the worklog.
     *
     */
    @NonNull
    private String id;

    /**
     * Whether users watching the issue are notified by email.
     *
     */
    @Nullable
    private Boolean notifyUsers;

    /**
     * Defines how to update the issue's time estimate, the options are:
     * 
     *  *  `new` Sets the estimate to a specific value, defined in `newEstimate`.
     *  *  `leave` Leaves the estimate unchanged.
     *  *  `manual` Increases the estimate by amount specified in `increaseBy`.
     *  *  `auto` Reduces the estimate by the value of `timeSpent` in the worklog.
     *
     */
    @Nullable
    private String adjustEstimate;

    /**
     * The value to set as the issue's remaining time estimate, as days (\#d), hours (\#h), or minutes (\#m or \#). For example, *2d*. Required when `adjustEstimate` is `new`.
     *
     */
    @Nullable
    private String newEstimate;

    /**
     * The amount to increase the issue's remaining estimate by, as days (\#d), hours (\#h), or minutes (\#m or \#). For example, *2d*. Required when `adjustEstimate` is `manual`.
     *
     */
    @Nullable
    private String increaseBy;

    /**
     * Whether the work log entry should be added to the issue even if the issue is not editable, because jira.issue.editable set to false or missing. For example, the issue is closed. Connect and Forge app users with admin permission can use this flag.
     *
     */
    @Nullable
    private Boolean overrideEditableFlag;

    /** Throws an exception if the request is not successful. */
    @NonNull
    private Boolean failOnError = true;

    /** Extra headers to include in the request */
    @NonNull
    private Map<String, List<String>> extraHeaders = new LinkedHashMap<>();

    /** Extra query parameters to include in the request */
    @NonNull
    private Map<String, List<String>> extraQueryParams = new LinkedHashMap<>();

    /**
     * Specific authentication methods for this operation.
     * If null, the global authentication is used.
     */
    @Nullable
    private List<AuthMethod> overrideAuthMethods;

    /**
     * Constructs a validated instance of {@link Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec(Consumer<Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(issueIdOrKey, "issueIdOrKey is a required parameter!");
        Objects.requireNonNull(id, "id is a required parameter!");
    }

    /** Adds a single header */
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec extraHeader(String key, String value) {
        this.extraHeaders.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value header */
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec extraHeader(String key, List<String> value) {
    this.extraHeaders.put(key, value);
    return this;
    }

    /** Adds a single query parameter */
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec extraQueryParam(String key, String value) {
        this.extraQueryParams.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value query parameter */
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec extraQueryParam(String key, List<String> value) {
        this.extraQueryParams.put(key, value);
        return this;
    }

    /** Adds a single auth method to the override list. */
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec overrideAuthMethod(AuthMethod method) {
        if (this.overrideAuthMethods == null) {
            this.overrideAuthMethods = new ArrayList<>();
        }
        this.overrideAuthMethods.add(method);
        return this;
    }

    /** Resets this operation to use global authentication settings. */
    public Delete2IssueByIssueIdOrKeyWorklogByIdV1OperationSpec useGlobalAuth() {
        this.overrideAuthMethods = null;
        return this;
    }
}
