// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.operations;

import io.github.primelib.jira.datacenter.client.auth.AuthMethod;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Get2ConfigFieldschemeByIdProjectsV1
 * <p>
 * REST Endpoint for searching for projects belonging to a given field association scheme
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2ConfigFieldschemeByIdProjectsV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The starting index of the returned projects. Base index: 0.
     *
     */
    @Nullable
    private Long startAt;

    /**
     * The maximum number of projects to return per page, maximum allowed value is 100.
     *
     */
    @Nullable
    private Integer maxResults;

    /**
     * The project Ids to filter by, if empty then all projects belonging to a field association scheme will be returned
     *
     */
    @Nullable
    private List<Long> projectId;

    /**
     * The scheme id to search for associated projects
     *
     */
    @NonNull
    private Long id;

    /** Throws an exception if the request is not successful. */
    @NonNull
    private Boolean failOnError = true;

    /** Extra headers to include in the request */
    @NonNull
    private Map<String, List<String>> extraHeaders = new LinkedHashMap<>();

    /** Extra query parameters to include in the request */
    @NonNull
    private Map<String, List<String>> extraQueryParams = new LinkedHashMap<>();

    /**
     * Specific authentication methods for this operation.
     * If null, the global authentication is used.
     */
    @Nullable
    private List<AuthMethod> overrideAuthMethods;

    /**
     * Constructs a validated instance of {@link Get2ConfigFieldschemeByIdProjectsV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec(Consumer<Get2ConfigFieldschemeByIdProjectsV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(id, "id is a required parameter!");
    }

    /** Adds a single header */
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec extraHeader(String key, String value) {
        this.extraHeaders.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value header */
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec extraHeader(String key, List<String> value) {
    this.extraHeaders.put(key, value);
    return this;
    }

    /** Adds a single query parameter */
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec extraQueryParam(String key, String value) {
        this.extraQueryParams.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value query parameter */
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec extraQueryParam(String key, List<String> value) {
        this.extraQueryParams.put(key, value);
        return this;
    }

    /** Adds a single auth method to the override list. */
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec overrideAuthMethod(AuthMethod method) {
        if (this.overrideAuthMethods == null) {
            this.overrideAuthMethods = new ArrayList<>();
        }
        this.overrideAuthMethods.add(method);
        return this;
    }

    /** Resets this operation to use global authentication settings. */
    public Get2ConfigFieldschemeByIdProjectsV1OperationSpec useGlobalAuth() {
        this.overrideAuthMethods = null;
        return this;
    }
}
