// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.operations;

import io.github.primelib.jira.datacenter.client.auth.AuthMethod;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Get2DashboardSearchV1
 * <p>
 * Returns a [paginated](#pagination) list of dashboards. This operation is similar to [Get dashboards](#api-rest-api-2-dashboard-get) except that the results can be refined to include dashboards that have specific attributes. For example, dashboards with a particular name. When multiple attributes are specified only filters matching all attributes are returned.
 * 
 * This operation can be accessed anonymously.
 * 
 * **[Permissions](#permissions) required:** The following dashboards that match the query parameters are returned:
 * 
 *  *  Dashboards owned by the user. Not returned for anonymous users.
 *  *  Dashboards shared with a group that the user is a member of. Not returned for anonymous users.
 *  *  Dashboards shared with a private project that the user can browse. Not returned for anonymous users.
 *  *  Dashboards shared with a public project.
 *  *  Dashboards shared with the public.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Get2DashboardSearchV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * String used to perform a case-insensitive partial match with `name`.
     *
     */
    @Nullable
    private String dashboardName;

    /**
     * User account ID used to return dashboards with the matching `owner.accountId`. This parameter cannot be used with the `owner` parameter.
     *
     */
    @Nullable
    private String accountId;

    /**
     * This parameter is deprecated because of privacy changes. Use `accountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. User name used to return dashboards with the matching `owner.name`. This parameter cannot be used with the `accountId` parameter.
     *
     */
    @Nullable
    private String owner;

    /**
     * As a group's name can change, use of `groupId` is recommended. Group name used to return dashboards that are shared with a group that matches `sharePermissions.group.name`. This parameter cannot be used with the `groupId` parameter.
     *
     */
    @Nullable
    private String groupname;

    /**
     * Group ID used to return dashboards that are shared with a group that matches `sharePermissions.group.groupId`. This parameter cannot be used with the `groupname` parameter.
     *
     */
    @Nullable
    private String groupId;

    /**
     * Project ID used to returns dashboards that are shared with a project that matches `sharePermissions.project.id`.
     *
     */
    @Nullable
    private Long projectId;

    /**
     * [Order](#ordering) the results by a field:
     * 
     *  *  `description` Sorts by dashboard description. Note that this sort works independently of whether the expand to display the description field is in use.
     *  *  `favourite_count` Sorts by dashboard popularity.
     *  *  `id` Sorts by dashboard ID.
     *  *  `is_favourite` Sorts by whether the dashboard is marked as a favorite.
     *  *  `name` Sorts by dashboard name.
     *  *  `owner` Sorts by dashboard owner name.
     *
     */
    @Nullable
    private String orderBy;

    /**
     * The index of the first item to return in a page of results (page offset).
     *
     */
    @Nullable
    private Long startAt;

    /**
     * The maximum number of items to return per page.
     *
     */
    @Nullable
    private Integer maxResults;

    /**
     * The status to filter by. It may be active, archived or deleted.
     *
     */
    @Nullable
    private String status;

    /**
     * Use [expand](#expansion) to include additional information about dashboard in the response. This parameter accepts a comma-separated list. Expand options include:
     * 
     *  *  `description` Returns the description of the dashboard.
     *  *  `owner` Returns the owner of the dashboard.
     *  *  `viewUrl` Returns the URL that is used to view the dashboard.
     *  *  `favourite` Returns `isFavourite`, an indicator of whether the user has set the dashboard as a favorite.
     *  *  `favouritedCount` Returns `popularity`, a count of how many users have set this dashboard as a favorite.
     *  *  `sharePermissions` Returns details of the share permissions defined for the dashboard.
     *  *  `editPermissions` Returns details of the edit permissions defined for the dashboard.
     *  *  `isWritable` Returns whether the current user has permission to edit the dashboard.
     *
     */
    @Nullable
    private String expand;

    /** Throws an exception if the request is not successful. */
    @NonNull
    private Boolean failOnError = true;

    /** Extra headers to include in the request */
    @NonNull
    private Map<String, List<String>> extraHeaders = new LinkedHashMap<>();

    /** Extra query parameters to include in the request */
    @NonNull
    private Map<String, List<String>> extraQueryParams = new LinkedHashMap<>();

    /**
     * Specific authentication methods for this operation.
     * If null, the global authentication is used.
     */
    @Nullable
    private List<AuthMethod> overrideAuthMethods;

    /**
     * Constructs a validated instance of {@link Get2DashboardSearchV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Get2DashboardSearchV1OperationSpec(Consumer<Get2DashboardSearchV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }

    /** Adds a single header */
    public Get2DashboardSearchV1OperationSpec extraHeader(String key, String value) {
        this.extraHeaders.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value header */
    public Get2DashboardSearchV1OperationSpec extraHeader(String key, List<String> value) {
    this.extraHeaders.put(key, value);
    return this;
    }

    /** Adds a single query parameter */
    public Get2DashboardSearchV1OperationSpec extraQueryParam(String key, String value) {
        this.extraQueryParams.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value query parameter */
    public Get2DashboardSearchV1OperationSpec extraQueryParam(String key, List<String> value) {
        this.extraQueryParams.put(key, value);
        return this;
    }

    /** Adds a single auth method to the override list. */
    public Get2DashboardSearchV1OperationSpec overrideAuthMethod(AuthMethod method) {
        if (this.overrideAuthMethods == null) {
            this.overrideAuthMethods = new ArrayList<>();
        }
        this.overrideAuthMethods.add(method);
        return this;
    }

    /** Resets this operation to use global authentication settings. */
    public Get2DashboardSearchV1OperationSpec useGlobalAuth() {
        this.overrideAuthMethods = null;
        return this;
    }
}
