// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.operations;

import io.github.primelib.jira.datacenter.client.auth.AuthMethod;
import io.github.primelib.jira.datacenter.client.models.ArchiveIssueAsyncRequest;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Post2IssueArchiveV1
 * <p>
 * Enables admins to archive up to 100,000 issues in a single request using JQL, returning the URL to check the status of the submitted request.
 * 
 * You can use the [get task](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-tasks/#api-rest-api-3-task-taskid-get) and [cancel task](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-tasks/#api-rest-api-3-task-taskid-cancel-post) APIs to manage the request.
 * 
 * **Note that:**
 * 
 *  *  you can't archive subtasks directly, only through their parent issues
 *  *  you can only archive issues from software, service management, and business projects
 * 
 * **[Permissions](#permissions) required:** Jira admin or site admin: [global permission](https://confluence.atlassian.com/x/x4dKLg)
 * 
 * **License required:** Premium or Enterprise
 * 
 * **Signed-in users only:** This API can't be accessed anonymously.
 * 
 * **Rate limiting:** Only a single request per jira instance can be active at any given time.
 * 
 *   
 * 
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class Post2IssueArchiveV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * A JQL query specifying the issues to archive. Note that subtasks can only be archived through their parent issues.
     *
     */
    @NonNull
    private ArchiveIssueAsyncRequest payload;

    /** Throws an exception if the request is not successful. */
    @NonNull
    private Boolean failOnError = true;

    /** Extra headers to include in the request */
    @NonNull
    private Map<String, List<String>> extraHeaders = new LinkedHashMap<>();

    /** Extra query parameters to include in the request */
    @NonNull
    private Map<String, List<String>> extraQueryParams = new LinkedHashMap<>();

    /**
     * Specific authentication methods for this operation.
     * If null, the global authentication is used.
     */
    @Nullable
    private List<AuthMethod> overrideAuthMethods;

    /**
     * Constructs a validated instance of {@link Post2IssueArchiveV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public Post2IssueArchiveV1OperationSpec(Consumer<Post2IssueArchiveV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }

    /** Adds a single header */
    public Post2IssueArchiveV1OperationSpec extraHeader(String key, String value) {
        this.extraHeaders.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value header */
    public Post2IssueArchiveV1OperationSpec extraHeader(String key, List<String> value) {
    this.extraHeaders.put(key, value);
    return this;
    }

    /** Adds a single query parameter */
    public Post2IssueArchiveV1OperationSpec extraQueryParam(String key, String value) {
        this.extraQueryParams.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value query parameter */
    public Post2IssueArchiveV1OperationSpec extraQueryParam(String key, List<String> value) {
        this.extraQueryParams.put(key, value);
        return this;
    }

    /** Adds a single auth method to the override list. */
    public Post2IssueArchiveV1OperationSpec overrideAuthMethod(AuthMethod method) {
        if (this.overrideAuthMethods == null) {
            this.overrideAuthMethods = new ArrayList<>();
        }
        this.overrideAuthMethods.add(method);
        return this;
    }

    /** Resets this operation to use global authentication settings. */
    public Post2IssueArchiveV1OperationSpec useGlobalAuth() {
        this.overrideAuthMethods = null;
        return this;
    }
}
