// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.operations;

import io.github.primelib.jira.datacenter.client.auth.AuthMethod;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1
 * <p>
 * Submits a request to trigger migration of connect issue field to its Forge custom field counterpart.
 * 
 * When migrating a Connect app to Forge, [Issue Field](https://developer.atlassian.com/cloud/jira/software/modules/issue-field/) modules
 * must be converted to [Custom field](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) modules.
 * This endpoint triggers the background migration of field data. Use the GET endpoint to retrieve
 * the status and progress of the task.
 * 
 * For more details, see
 * [Jira modules &gt; Jira Custom Fields](https://developer.atlassian.com/platform/adopting-forge-from-connect/migrate-jira-custom-fields/).
 * 
 * **[Permissions](#permissions) required:** Only Connect and Forge apps can make this request.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the Connect app that contains the Jira issue field being migrated.
     *
     */
    @NonNull
    private String connectKey;

    /**
     * The module key of the Connect issue field being migrated.
     *
     */
    @NonNull
    private String jiraIssueFieldsKey;

    /**
     * Whether to retrigger the migration if it has already completed.
     *
     */
    @Nullable
    private Boolean retriggerCompletedMigration;

    /** Throws an exception if the request is not successful. */
    @NonNull
    private Boolean failOnError = true;

    /** Extra headers to include in the request */
    @NonNull
    private Map<String, List<String>> extraHeaders = new LinkedHashMap<>();

    /** Extra query parameters to include in the request */
    @NonNull
    private Map<String, List<String>> extraQueryParams = new LinkedHashMap<>();

    /**
     * Specific authentication methods for this operation.
     * If null, the global authentication is used.
     */
    @Nullable
    private List<AuthMethod> overrideAuthMethods;

    /**
     * Constructs a validated instance of {@link PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec(Consumer<PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(connectKey, "connectKey is a required parameter!");
        Objects.requireNonNull(jiraIssueFieldsKey, "jiraIssueFieldsKey is a required parameter!");
    }

    /** Adds a single header */
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec extraHeader(String key, String value) {
        this.extraHeaders.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value header */
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec extraHeader(String key, List<String> value) {
    this.extraHeaders.put(key, value);
    return this;
    }

    /** Adds a single query parameter */
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec extraQueryParam(String key, String value) {
        this.extraQueryParams.put(key, List.of(value));
        return this;
    }

    /** Adds a multi-value query parameter */
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec extraQueryParam(String key, List<String> value) {
        this.extraQueryParams.put(key, value);
        return this;
    }

    /** Adds a single auth method to the override list. */
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec overrideAuthMethod(AuthMethod method) {
        if (this.overrideAuthMethods == null) {
            this.overrideAuthMethods = new ArrayList<>();
        }
        this.overrideAuthMethods.add(method);
        return this;
    }

    /** Resets this operation to use global authentication settings. */
    public PostAtlassianConnect1MigrationByConnectKeyByJiraIssueFieldsKeyTaskV1OperationSpec useGlobalAuth() {
        this.overrideAuthMethods = null;
        return this;
    }
}
