// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * AssigneeTypeEnum621E93
 * <p>
 * The default assignee when creating issues for this project.
 *
 */
@JsonTypeName("AssigneeTypeEnum621E93")
@Generated(value = "io.github.primelib.primecodegen")
public enum AssigneeTypeEnum621E93 {
    PROJECT_LEAD("PROJECT_LEAD"),
    UNASSIGNED("UNASSIGNED"),
    ;

    private final String value;

    AssigneeTypeEnum621E93(String value) {
        this.value = value;
    }
}
