// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * RendererTypeEnum
 * <p>
 * The renderer type for the field, null to preserve current renderer type
 *
 */
@JsonTypeName("RendererTypeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum RendererTypeEnum {
    ATLASSIAN_WIKI_RENDERER("atlassian-wiki-renderer"),
    JIRA_TEXT_RENDERER("jira-text-renderer"),
    ;

    private final String value;

    RendererTypeEnum(String value) {
        this.value = value;
    }
}
