// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * SwimlaneStrategyEnum
 * <p>
 * The swimlane strategy for the board.
 *
 */
@JsonTypeName("SwimlaneStrategyEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum SwimlaneStrategyEnum {
    ASSIGNEE("assignee"),
    ASSIGNEE_UNASSIGNED_FIRST("assigneeUnassignedFirst"),
    CUSTOM("custom"),
    EPIC("epic"),
    ISSUECHILDREN("issuechildren"),
    ISSUEPARENT("issueparent"),
    NONE("none"),
    PARENT_CHILD("parentChild"),
    PROJECT("project"),
    REQUEST_TYPE("request_type"),
    ;

    private final String value;

    SwimlaneStrategyEnum(String value) {
        this.value = value;
    }
}
