// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * TypeEnum08551C
 * <p>
 * The team type. This is "PlanOnly" or "Atlassian".
 *
 */
@JsonTypeName("TypeEnum08551C")
@Generated(value = "io.github.primelib.primecodegen")
public enum TypeEnum08551C {
    ATLASSIAN("Atlassian"),
    PLAN_ONLY("PlanOnly"),
    ;

    private final String value;

    TypeEnum08551C(String value) {
        this.value = value;
    }
}
