// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * TypeEnume4F536
 * <p>
 * The transition type.
 *
 */
@JsonTypeName("TypeEnume4F536")
@Generated(value = "io.github.primelib.primecodegen")
public enum TypeEnume4F536 {
    DIRECTED("DIRECTED"),
    GLOBAL("GLOBAL"),
    INITIAL("INITIAL"),
    ;

    private final String value;

    TypeEnume4F536(String value) {
        this.value = value;
    }
}
