// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * ViewTypeEnum
 * <p>
 * The view type of the context.  
 * Supported values:
 * 
 *  *  `GIC` \- Jira global issue create
 *  *  `IssueView` \- Jira issue view
 *  *  `IssueTransition` \- Jira issue transition
 *  *  `JSMRequestCreate` \- Jira Service Management request create portal view
 *  *  `GICAgentView` \- Agent view variant of Jira global issue create
 *  *  `IssueViewAgentView` \- Agent view variant of Jira issue view
 *  *  `IssueTransitionAgentView` \- Agent view variant of Jira issue transition
 * 
 * For Jira and Agent view types (`GIC`, `IssueView`, `IssueTransition`, `GICAgentView`, `IssueViewAgentView`, `IssueTransitionAgentView`), null is treated as a wildcard, meaning the UI modification will be applied to all view types. Each Jira or Agent context can have a maximum of one wildcard.  
 *   
 * Agent view contexts use `projectId` and `issueTypeId` like Jira contexts, and may optionally also set `requestTypeId`. Agent view contexts must not set `portalId`.  
 *   
 * Wildcards are not applicable for JSM contexts.
 *
 */
@JsonTypeName("ViewTypeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum ViewTypeEnum {
    GIC("GIC"),
    GIC_AGENT_VIEW("GICAgentView"),
    ISSUE_TRANSITION("IssueTransition"),
    ISSUE_TRANSITION_AGENT_VIEW("IssueTransitionAgentView"),
    ISSUE_VIEW("IssueView"),
    ISSUE_VIEW_AGENT_VIEW("IssueViewAgentView"),
    JSM_REQUEST_CREATE("JSMRequestCreate"),
    ;

    private final String value;

    ViewTypeEnum(String value) {
        this.value = value;
    }
}
