// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * AutoCompleteSuggestion
 * <p>
 * A field auto-complete suggestion.
 *
 */
@JsonTypeName("AutoCompleteSuggestion")
@JsonPropertyOrder({
    "displayName",
    "value"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AutoCompleteSuggestion {

    /**
     * The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
     */
    @JsonProperty("displayName")
    protected String displayName;

    /**
     * The value of a suggested item.
     */
    @JsonProperty("value")
    protected String value;

    /**
     * Constructs a validated instance of {@link AutoCompleteSuggestion}.
     *
     * @param spec the specification to process
     */
    public AutoCompleteSuggestion(Consumer<AutoCompleteSuggestion> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected AutoCompleteSuggestion() {
    }
    /**
     * Constructs a validated instance of {@link AutoCompleteSuggestion}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AutoCompleteSuggestion(Consumer)} instead.
     * @param displayName The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
     * @param value The value of a suggested item.
     */
    @ApiStatus.Internal
    public AutoCompleteSuggestion(String displayName, String value) {
        this.displayName = displayName;
        this.value = value;
    }


    /**
     * Fluent getter for displayName.
     * <p>
     * The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
     *
     * @return displayName
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Fluent setter for displayName.
     * <p>
     * The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
     *
     * @param displayName displayName
     * @return this
     */
    public AutoCompleteSuggestion displayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Gets the value of displayName.
     * <p>
     * The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
     *
     * @return displayName
     */
    @JsonProperty("displayName")
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Sets the value of displayName.
     * <p>
     * The display name of a suggested item. If `fieldValue` or `predicateValue` are provided, the matching text is highlighted with the HTML bold tag.
     *
     * @param displayName displayName
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    /**
     * Fluent getter for value.
     * <p>
     * The value of a suggested item.
     *
     * @return value
     */
    public String value() {
        return this.value;
    }

    /**
     * Fluent setter for value.
     * <p>
     * The value of a suggested item.
     *
     * @param value value
     * @return this
     */
    public AutoCompleteSuggestion value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Gets the value of value.
     * <p>
     * The value of a suggested item.
     *
     * @return value
     */
    @JsonProperty("value")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of value.
     * <p>
     * The value of a suggested item.
     *
     * @param value value
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AutoCompleteSuggestion that = (AutoCompleteSuggestion) o;
        return
            Objects.equals(this.displayName, that.displayName) &&
            Objects.equals(this.value, that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.displayName, 
            this.value
        );
    }

    @Override
    public String toString() {
        return "AutoCompleteSuggestion{"
            + "displayName=" + displayName + ", "
            + "value=" + value
            + "}";
    }
}
