// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * ConditionGroupUpdate
 * <p>
 * The conditions group associated with the transition.
 *
 */
@JsonTypeName("ConditionGroupUpdate")
@JsonPropertyOrder({
    "conditionGroups",
    "conditions",
    "operation"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ConditionGroupUpdate {

    /**
     * The nested conditions of the condition group.
     */
    @JsonProperty("conditionGroups")
    protected List<ConditionGroupUpdate> conditionGroups;

    /**
     * The rules for this condition.
     */
    @JsonProperty("conditions")
    protected List<WorkflowRuleConfiguration> conditions;

    /**
     * Determines how the conditions in the group are evaluated. Accepts either `ANY` or `ALL`. If `ANY` is used, at least one condition in the group must be true for the group to evaluate to true. If `ALL` is used, all conditions in the group must be true for the group to evaluate to true.
     */
    @JsonProperty("operation")
    protected String operation;

    /**
     * Constructs a validated instance of {@link ConditionGroupUpdate}.
     *
     * @param spec the specification to process
     */
    public ConditionGroupUpdate(Consumer<ConditionGroupUpdate> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected ConditionGroupUpdate() {
    }
    /**
     * Constructs a validated instance of {@link ConditionGroupUpdate}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ConditionGroupUpdate(Consumer)} instead.
     * @param conditionGroups The nested conditions of the condition group.
     * @param conditions The rules for this condition.
     * @param operation Determines how the conditions in the group are evaluated. Accepts either `ANY` or `ALL`. If `ANY` is used, at least one condition in the group must be true for the group to evaluate to true. If `ALL` is used, all conditions in the group must be true for the group to evaluate to true.
     */
    @ApiStatus.Internal
    public ConditionGroupUpdate(List<ConditionGroupUpdate> conditionGroups, List<WorkflowRuleConfiguration> conditions, String operation) {
        this.conditionGroups = conditionGroups;
        this.conditions = conditions;
        this.operation = operation;
    }


    /**
     * Fluent getter for conditionGroups.
     * <p>
     * The nested conditions of the condition group.
     *
     * @return conditionGroups
     */
    public List<ConditionGroupUpdate> conditionGroups() {
        return this.conditionGroups;
    }

    /**
     * Fluent setter for conditionGroups.
     * <p>
     * The nested conditions of the condition group.
     *
     * @param conditionGroups conditionGroups
     * @return this
     */
    public ConditionGroupUpdate conditionGroups(List<ConditionGroupUpdate> conditionGroups) {
        this.conditionGroups = conditionGroups;
        return this;
    }

    /**
     * Gets the value of conditionGroups.
     * <p>
     * The nested conditions of the condition group.
     *
     * @return conditionGroups
     */
    @JsonProperty("conditionGroups")
    public List<ConditionGroupUpdate> getConditionGroups() {
        return this.conditionGroups;
    }

    /**
     * Sets the value of conditionGroups.
     * <p>
     * The nested conditions of the condition group.
     *
     * @param conditionGroups conditionGroups
     */
    public void setConditionGroups(List<ConditionGroupUpdate> conditionGroups) {
        this.conditionGroups = conditionGroups;
    }
    /**
     * Fluent getter for conditions.
     * <p>
     * The rules for this condition.
     *
     * @return conditions
     */
    public List<WorkflowRuleConfiguration> conditions() {
        return this.conditions;
    }

    /**
     * Fluent setter for conditions.
     * <p>
     * The rules for this condition.
     *
     * @param conditions conditions
     * @return this
     */
    public ConditionGroupUpdate conditions(List<WorkflowRuleConfiguration> conditions) {
        this.conditions = conditions;
        return this;
    }

    /**
     * Gets the value of conditions.
     * <p>
     * The rules for this condition.
     *
     * @return conditions
     */
    @JsonProperty("conditions")
    public List<WorkflowRuleConfiguration> getConditions() {
        return this.conditions;
    }

    /**
     * Sets the value of conditions.
     * <p>
     * The rules for this condition.
     *
     * @param conditions conditions
     */
    public void setConditions(List<WorkflowRuleConfiguration> conditions) {
        this.conditions = conditions;
    }
    /**
     * Fluent getter for operation.
     * <p>
     * Determines how the conditions in the group are evaluated. Accepts either `ANY` or `ALL`. If `ANY` is used, at least one condition in the group must be true for the group to evaluate to true. If `ALL` is used, all conditions in the group must be true for the group to evaluate to true.
     *
     * @return operation
     */
    public String operation() {
        return this.operation;
    }

    /**
     * Fluent setter for operation.
     * <p>
     * Determines how the conditions in the group are evaluated. Accepts either `ANY` or `ALL`. If `ANY` is used, at least one condition in the group must be true for the group to evaluate to true. If `ALL` is used, all conditions in the group must be true for the group to evaluate to true.
     *
     * @param operation operation
     * @return this
     */
    public ConditionGroupUpdate operation(String operation) {
        this.operation = operation;
        return this;
    }

    /**
     * Gets the value of operation.
     * <p>
     * Determines how the conditions in the group are evaluated. Accepts either `ANY` or `ALL`. If `ANY` is used, at least one condition in the group must be true for the group to evaluate to true. If `ALL` is used, all conditions in the group must be true for the group to evaluate to true.
     *
     * @return operation
     */
    @JsonProperty("operation")
    public String getOperation() {
        return this.operation;
    }

    /**
     * Sets the value of operation.
     * <p>
     * Determines how the conditions in the group are evaluated. Accepts either `ANY` or `ALL`. If `ANY` is used, at least one condition in the group must be true for the group to evaluate to true. If `ALL` is used, all conditions in the group must be true for the group to evaluate to true.
     *
     * @param operation operation
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ConditionGroupUpdate that = (ConditionGroupUpdate) o;
        return
            Objects.equals(this.conditionGroups, that.conditionGroups) &&
            Objects.equals(this.conditions, that.conditions) &&
            Objects.equals(this.operation, that.operation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.conditionGroups, 
            this.conditions, 
            this.operation
        );
    }

    @Override
    public String toString() {
        return "ConditionGroupUpdate{"
            + "conditionGroups=" + conditionGroups + ", "
            + "conditions=" + conditions + ", "
            + "operation=" + operation
            + "}";
    }
}
