// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContainerForProjectFeatures
 * <p>
 * The list of features on a project.
 *
 */
@JsonTypeName("ContainerForProjectFeatures")
@JsonPropertyOrder({
    "features"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContainerForProjectFeatures {

    /**
     * The project features.
     */
    @JsonProperty("features")
    protected List<ProjectFeature> features;

    /**
     * Constructs a validated instance of {@link ContainerForProjectFeatures}.
     *
     * @param spec the specification to process
     */
    public ContainerForProjectFeatures(Consumer<ContainerForProjectFeatures> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected ContainerForProjectFeatures() {
    }
    /**
     * Constructs a validated instance of {@link ContainerForProjectFeatures}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContainerForProjectFeatures(Consumer)} instead.
     * @param features The project features.
     */
    @ApiStatus.Internal
    public ContainerForProjectFeatures(List<ProjectFeature> features) {
        this.features = features;
    }


    /**
     * Fluent getter for features.
     * <p>
     * The project features.
     *
     * @return features
     */
    public List<ProjectFeature> features() {
        return this.features;
    }

    /**
     * Fluent setter for features.
     * <p>
     * The project features.
     *
     * @param features features
     * @return this
     */
    public ContainerForProjectFeatures features(List<ProjectFeature> features) {
        this.features = features;
        return this;
    }

    /**
     * Gets the value of features.
     * <p>
     * The project features.
     *
     * @return features
     */
    @JsonProperty("features")
    public List<ProjectFeature> getFeatures() {
        return this.features;
    }

    /**
     * Sets the value of features.
     * <p>
     * The project features.
     *
     * @param features features
     */
    public void setFeatures(List<ProjectFeature> features) {
        this.features = features;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContainerForProjectFeatures that = (ContainerForProjectFeatures) o;
        return
            Objects.equals(this.features, that.features);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.features
        );
    }

    @Override
    public String toString() {
        return "ContainerForProjectFeatures{"
            + "features=" + features
            + "}";
    }
}
