// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * DeleteAndReplaceVersionBean
 *
 */
@JsonTypeName("DeleteAndReplaceVersionBean")
@JsonPropertyOrder({
    "customFieldReplacementList",
    "moveAffectedIssuesTo",
    "moveFixIssuesTo"
})
@Generated(value = "io.github.primelib.primecodegen")
public class DeleteAndReplaceVersionBean {

    /**
     * An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
     */
    @JsonProperty("customFieldReplacementList")
    protected List<CustomFieldReplacement> customFieldReplacementList;

    /**
     * The ID of the version to update `affectedVersion` to when the field contains the deleted version.
     */
    @JsonProperty("moveAffectedIssuesTo")
    protected Long moveAffectedIssuesTo;

    /**
     * The ID of the version to update `fixVersion` to when the field contains the deleted version.
     */
    @JsonProperty("moveFixIssuesTo")
    protected Long moveFixIssuesTo;

    /**
     * Constructs a validated instance of {@link DeleteAndReplaceVersionBean}.
     *
     * @param spec the specification to process
     */
    public DeleteAndReplaceVersionBean(Consumer<DeleteAndReplaceVersionBean> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected DeleteAndReplaceVersionBean() {
    }
    /**
     * Constructs a validated instance of {@link DeleteAndReplaceVersionBean}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #DeleteAndReplaceVersionBean(Consumer)} instead.
     * @param customFieldReplacementList An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
     * @param moveAffectedIssuesTo The ID of the version to update `affectedVersion` to when the field contains the deleted version.
     * @param moveFixIssuesTo The ID of the version to update `fixVersion` to when the field contains the deleted version.
     */
    @ApiStatus.Internal
    public DeleteAndReplaceVersionBean(List<CustomFieldReplacement> customFieldReplacementList, Long moveAffectedIssuesTo, Long moveFixIssuesTo) {
        this.customFieldReplacementList = customFieldReplacementList;
        this.moveAffectedIssuesTo = moveAffectedIssuesTo;
        this.moveFixIssuesTo = moveFixIssuesTo;
    }


    /**
     * Fluent getter for customFieldReplacementList.
     * <p>
     * An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
     *
     * @return customFieldReplacementList
     */
    public List<CustomFieldReplacement> customFieldReplacementList() {
        return this.customFieldReplacementList;
    }

    /**
     * Fluent setter for customFieldReplacementList.
     * <p>
     * An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
     *
     * @param customFieldReplacementList customFieldReplacementList
     * @return this
     */
    public DeleteAndReplaceVersionBean customFieldReplacementList(List<CustomFieldReplacement> customFieldReplacementList) {
        this.customFieldReplacementList = customFieldReplacementList;
        return this;
    }

    /**
     * Gets the value of customFieldReplacementList.
     * <p>
     * An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
     *
     * @return customFieldReplacementList
     */
    @JsonProperty("customFieldReplacementList")
    public List<CustomFieldReplacement> getCustomFieldReplacementList() {
        return this.customFieldReplacementList;
    }

    /**
     * Sets the value of customFieldReplacementList.
     * <p>
     * An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
     *
     * @param customFieldReplacementList customFieldReplacementList
     */
    public void setCustomFieldReplacementList(List<CustomFieldReplacement> customFieldReplacementList) {
        this.customFieldReplacementList = customFieldReplacementList;
    }
    /**
     * Fluent getter for moveAffectedIssuesTo.
     * <p>
     * The ID of the version to update `affectedVersion` to when the field contains the deleted version.
     *
     * @return moveAffectedIssuesTo
     */
    public Long moveAffectedIssuesTo() {
        return this.moveAffectedIssuesTo;
    }

    /**
     * Fluent setter for moveAffectedIssuesTo.
     * <p>
     * The ID of the version to update `affectedVersion` to when the field contains the deleted version.
     *
     * @param moveAffectedIssuesTo moveAffectedIssuesTo
     * @return this
     */
    public DeleteAndReplaceVersionBean moveAffectedIssuesTo(Long moveAffectedIssuesTo) {
        this.moveAffectedIssuesTo = moveAffectedIssuesTo;
        return this;
    }

    /**
     * Gets the value of moveAffectedIssuesTo.
     * <p>
     * The ID of the version to update `affectedVersion` to when the field contains the deleted version.
     *
     * @return moveAffectedIssuesTo
     */
    @JsonProperty("moveAffectedIssuesTo")
    public Long getMoveAffectedIssuesTo() {
        return this.moveAffectedIssuesTo;
    }

    /**
     * Sets the value of moveAffectedIssuesTo.
     * <p>
     * The ID of the version to update `affectedVersion` to when the field contains the deleted version.
     *
     * @param moveAffectedIssuesTo moveAffectedIssuesTo
     */
    public void setMoveAffectedIssuesTo(Long moveAffectedIssuesTo) {
        this.moveAffectedIssuesTo = moveAffectedIssuesTo;
    }
    /**
     * Fluent getter for moveFixIssuesTo.
     * <p>
     * The ID of the version to update `fixVersion` to when the field contains the deleted version.
     *
     * @return moveFixIssuesTo
     */
    public Long moveFixIssuesTo() {
        return this.moveFixIssuesTo;
    }

    /**
     * Fluent setter for moveFixIssuesTo.
     * <p>
     * The ID of the version to update `fixVersion` to when the field contains the deleted version.
     *
     * @param moveFixIssuesTo moveFixIssuesTo
     * @return this
     */
    public DeleteAndReplaceVersionBean moveFixIssuesTo(Long moveFixIssuesTo) {
        this.moveFixIssuesTo = moveFixIssuesTo;
        return this;
    }

    /**
     * Gets the value of moveFixIssuesTo.
     * <p>
     * The ID of the version to update `fixVersion` to when the field contains the deleted version.
     *
     * @return moveFixIssuesTo
     */
    @JsonProperty("moveFixIssuesTo")
    public Long getMoveFixIssuesTo() {
        return this.moveFixIssuesTo;
    }

    /**
     * Sets the value of moveFixIssuesTo.
     * <p>
     * The ID of the version to update `fixVersion` to when the field contains the deleted version.
     *
     * @param moveFixIssuesTo moveFixIssuesTo
     */
    public void setMoveFixIssuesTo(Long moveFixIssuesTo) {
        this.moveFixIssuesTo = moveFixIssuesTo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DeleteAndReplaceVersionBean that = (DeleteAndReplaceVersionBean) o;
        return
            Objects.equals(this.customFieldReplacementList, that.customFieldReplacementList) &&
            Objects.equals(this.moveAffectedIssuesTo, that.moveAffectedIssuesTo) &&
            Objects.equals(this.moveFixIssuesTo, that.moveFixIssuesTo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.customFieldReplacementList, 
            this.moveAffectedIssuesTo, 
            this.moveFixIssuesTo
        );
    }

    @Override
    public String toString() {
        return "DeleteAndReplaceVersionBean{"
            + "customFieldReplacementList=" + customFieldReplacementList + ", "
            + "moveAffectedIssuesTo=" + moveAffectedIssuesTo + ", "
            + "moveFixIssuesTo=" + moveFixIssuesTo
            + "}";
    }
}
