// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Errors
 *
 */
@JsonTypeName("Errors")
@JsonPropertyOrder({
    "issueIsSubtask",
    "issuesInArchivedProjects",
    "issuesInUnlicensedProjects",
    "issuesNotFound",
    "userDoesNotHavePermission"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Errors {

    @JsonProperty("issueIsSubtask")
    protected Error issueIsSubtask;

    @JsonProperty("issuesInArchivedProjects")
    protected Error issuesInArchivedProjects;

    @JsonProperty("issuesInUnlicensedProjects")
    protected Error issuesInUnlicensedProjects;

    @JsonProperty("issuesNotFound")
    protected Error issuesNotFound;

    @JsonProperty("userDoesNotHavePermission")
    protected Error userDoesNotHavePermission;

    /**
     * Constructs a validated instance of {@link Errors}.
     *
     * @param spec the specification to process
     */
    public Errors(Consumer<Errors> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Errors() {
    }
    /**
     * Constructs a validated instance of {@link Errors}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Errors(Consumer)} instead.
     * @param issueIsSubtask issueIsSubtask
     * @param issuesInArchivedProjects issuesInArchivedProjects
     * @param issuesInUnlicensedProjects issuesInUnlicensedProjects
     * @param issuesNotFound issuesNotFound
     * @param userDoesNotHavePermission userDoesNotHavePermission
     */
    @ApiStatus.Internal
    public Errors(Error issueIsSubtask, Error issuesInArchivedProjects, Error issuesInUnlicensedProjects, Error issuesNotFound, Error userDoesNotHavePermission) {
        this.issueIsSubtask = issueIsSubtask;
        this.issuesInArchivedProjects = issuesInArchivedProjects;
        this.issuesInUnlicensedProjects = issuesInUnlicensedProjects;
        this.issuesNotFound = issuesNotFound;
        this.userDoesNotHavePermission = userDoesNotHavePermission;
    }


    /**
     * Fluent getter for issueIsSubtask.
     *
     * @return issueIsSubtask
     */
    public Error issueIsSubtask() {
        return this.issueIsSubtask;
    }

    /**
     * Fluent setter for issueIsSubtask.
     *
     * @param issueIsSubtask issueIsSubtask
     * @return this
     */
    public Errors issueIsSubtask(Error issueIsSubtask) {
        this.issueIsSubtask = issueIsSubtask;
        return this;
    }

    /**
     * Gets the value of issueIsSubtask.
     *
     * @return issueIsSubtask
     */
    @JsonProperty("issueIsSubtask")
    public Error getIssueIsSubtask() {
        return this.issueIsSubtask;
    }

    /**
     * Sets the value of issueIsSubtask.
     *
     * @param issueIsSubtask issueIsSubtask
     */
    public void setIssueIsSubtask(Error issueIsSubtask) {
        this.issueIsSubtask = issueIsSubtask;
    }
    /**
     * Fluent getter for issuesInArchivedProjects.
     *
     * @return issuesInArchivedProjects
     */
    public Error issuesInArchivedProjects() {
        return this.issuesInArchivedProjects;
    }

    /**
     * Fluent setter for issuesInArchivedProjects.
     *
     * @param issuesInArchivedProjects issuesInArchivedProjects
     * @return this
     */
    public Errors issuesInArchivedProjects(Error issuesInArchivedProjects) {
        this.issuesInArchivedProjects = issuesInArchivedProjects;
        return this;
    }

    /**
     * Gets the value of issuesInArchivedProjects.
     *
     * @return issuesInArchivedProjects
     */
    @JsonProperty("issuesInArchivedProjects")
    public Error getIssuesInArchivedProjects() {
        return this.issuesInArchivedProjects;
    }

    /**
     * Sets the value of issuesInArchivedProjects.
     *
     * @param issuesInArchivedProjects issuesInArchivedProjects
     */
    public void setIssuesInArchivedProjects(Error issuesInArchivedProjects) {
        this.issuesInArchivedProjects = issuesInArchivedProjects;
    }
    /**
     * Fluent getter for issuesInUnlicensedProjects.
     *
     * @return issuesInUnlicensedProjects
     */
    public Error issuesInUnlicensedProjects() {
        return this.issuesInUnlicensedProjects;
    }

    /**
     * Fluent setter for issuesInUnlicensedProjects.
     *
     * @param issuesInUnlicensedProjects issuesInUnlicensedProjects
     * @return this
     */
    public Errors issuesInUnlicensedProjects(Error issuesInUnlicensedProjects) {
        this.issuesInUnlicensedProjects = issuesInUnlicensedProjects;
        return this;
    }

    /**
     * Gets the value of issuesInUnlicensedProjects.
     *
     * @return issuesInUnlicensedProjects
     */
    @JsonProperty("issuesInUnlicensedProjects")
    public Error getIssuesInUnlicensedProjects() {
        return this.issuesInUnlicensedProjects;
    }

    /**
     * Sets the value of issuesInUnlicensedProjects.
     *
     * @param issuesInUnlicensedProjects issuesInUnlicensedProjects
     */
    public void setIssuesInUnlicensedProjects(Error issuesInUnlicensedProjects) {
        this.issuesInUnlicensedProjects = issuesInUnlicensedProjects;
    }
    /**
     * Fluent getter for issuesNotFound.
     *
     * @return issuesNotFound
     */
    public Error issuesNotFound() {
        return this.issuesNotFound;
    }

    /**
     * Fluent setter for issuesNotFound.
     *
     * @param issuesNotFound issuesNotFound
     * @return this
     */
    public Errors issuesNotFound(Error issuesNotFound) {
        this.issuesNotFound = issuesNotFound;
        return this;
    }

    /**
     * Gets the value of issuesNotFound.
     *
     * @return issuesNotFound
     */
    @JsonProperty("issuesNotFound")
    public Error getIssuesNotFound() {
        return this.issuesNotFound;
    }

    /**
     * Sets the value of issuesNotFound.
     *
     * @param issuesNotFound issuesNotFound
     */
    public void setIssuesNotFound(Error issuesNotFound) {
        this.issuesNotFound = issuesNotFound;
    }
    /**
     * Fluent getter for userDoesNotHavePermission.
     *
     * @return userDoesNotHavePermission
     */
    public Error userDoesNotHavePermission() {
        return this.userDoesNotHavePermission;
    }

    /**
     * Fluent setter for userDoesNotHavePermission.
     *
     * @param userDoesNotHavePermission userDoesNotHavePermission
     * @return this
     */
    public Errors userDoesNotHavePermission(Error userDoesNotHavePermission) {
        this.userDoesNotHavePermission = userDoesNotHavePermission;
        return this;
    }

    /**
     * Gets the value of userDoesNotHavePermission.
     *
     * @return userDoesNotHavePermission
     */
    @JsonProperty("userDoesNotHavePermission")
    public Error getUserDoesNotHavePermission() {
        return this.userDoesNotHavePermission;
    }

    /**
     * Sets the value of userDoesNotHavePermission.
     *
     * @param userDoesNotHavePermission userDoesNotHavePermission
     */
    public void setUserDoesNotHavePermission(Error userDoesNotHavePermission) {
        this.userDoesNotHavePermission = userDoesNotHavePermission;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Errors that = (Errors) o;
        return
            Objects.equals(this.issueIsSubtask, that.issueIsSubtask) &&
            Objects.equals(this.issuesInArchivedProjects, that.issuesInArchivedProjects) &&
            Objects.equals(this.issuesInUnlicensedProjects, that.issuesInUnlicensedProjects) &&
            Objects.equals(this.issuesNotFound, that.issuesNotFound) &&
            Objects.equals(this.userDoesNotHavePermission, that.userDoesNotHavePermission);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.issueIsSubtask, 
            this.issuesInArchivedProjects, 
            this.issuesInUnlicensedProjects, 
            this.issuesNotFound, 
            this.userDoesNotHavePermission
        );
    }

    @Override
    public String toString() {
        return "Errors{"
            + "issueIsSubtask=" + issueIsSubtask + ", "
            + "issuesInArchivedProjects=" + issuesInArchivedProjects + ", "
            + "issuesInUnlicensedProjects=" + issuesInUnlicensedProjects + ", "
            + "issuesNotFound=" + issuesNotFound + ", "
            + "userDoesNotHavePermission=" + userDoesNotHavePermission
            + "}";
    }
}
