// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * FieldLayoutSchemePayload
 * <p>
 * Deprecated use [fieldAssociationScheme](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-field-schemes/#api-group-field-schemes) instead Defines the payload for the field layout schemes. See [ Field configuration scheme](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-field-configurations/#api-rest-api-3-fieldconfigurationscheme-post).
 * 
 * [ How to configure a field configuration scheme](https://support.atlassian.com/jira-cloud-administration/docs/configure-a-field-configuration-scheme/).
 *
 */
@JsonTypeName("FieldLayoutSchemePayload")
@JsonPropertyOrder({
    "defaultFieldLayout",
    "description",
    "explicitMappings",
    "name",
    "pcri"
})
@Generated(value = "io.github.primelib.primecodegen")
public class FieldLayoutSchemePayload {

    /**
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     */
    @JsonProperty("defaultFieldLayout")
    protected ProjectCreateResourceIdentifier defaultFieldLayout;

    /**
     * The description of the field layout scheme
     */
    @JsonProperty("description")
    protected String description;

    /**
     * There is a default configuration "fieldlayout" that is applied to all issue types using this scheme that don't have an explicit mapping users can create (or re-use existing) configurations for other issue types and map them to this scheme
     */
    @JsonProperty("explicitMappings")
    protected Map<String, ProjectCreateResourceIdentifier> explicitMappings;

    /**
     * The name of the field layout scheme
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     */
    @JsonProperty("pcri")
    protected ProjectCreateResourceIdentifier pcri;

    /**
     * Constructs a validated instance of {@link FieldLayoutSchemePayload}.
     *
     * @param spec the specification to process
     */
    public FieldLayoutSchemePayload(Consumer<FieldLayoutSchemePayload> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected FieldLayoutSchemePayload() {
    }
    /**
     * Constructs a validated instance of {@link FieldLayoutSchemePayload}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #FieldLayoutSchemePayload(Consumer)} instead.
     * @param defaultFieldLayout Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     * @param description The description of the field layout scheme
     * @param explicitMappings There is a default configuration "fieldlayout" that is applied to all issue types using this scheme that don't have an explicit mapping users can create (or re-use existing) configurations for other issue types and map them to this scheme
     * @param name The name of the field layout scheme
     * @param pcri Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     */
    @ApiStatus.Internal
    public FieldLayoutSchemePayload(ProjectCreateResourceIdentifier defaultFieldLayout, String description, Map<String, ProjectCreateResourceIdentifier> explicitMappings, String name, ProjectCreateResourceIdentifier pcri) {
        this.defaultFieldLayout = defaultFieldLayout;
        this.description = description;
        this.explicitMappings = explicitMappings;
        this.name = name;
        this.pcri = pcri;
    }


    /**
     * Fluent getter for defaultFieldLayout.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @return defaultFieldLayout
     */
    public ProjectCreateResourceIdentifier defaultFieldLayout() {
        return this.defaultFieldLayout;
    }

    /**
     * Fluent setter for defaultFieldLayout.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @param defaultFieldLayout defaultFieldLayout
     * @return this
     */
    public FieldLayoutSchemePayload defaultFieldLayout(ProjectCreateResourceIdentifier defaultFieldLayout) {
        this.defaultFieldLayout = defaultFieldLayout;
        return this;
    }

    /**
     * Gets the value of defaultFieldLayout.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @return defaultFieldLayout
     */
    @JsonProperty("defaultFieldLayout")
    public ProjectCreateResourceIdentifier getDefaultFieldLayout() {
        return this.defaultFieldLayout;
    }

    /**
     * Sets the value of defaultFieldLayout.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @param defaultFieldLayout defaultFieldLayout
     */
    public void setDefaultFieldLayout(ProjectCreateResourceIdentifier defaultFieldLayout) {
        this.defaultFieldLayout = defaultFieldLayout;
    }
    /**
     * Fluent getter for description.
     * <p>
     * The description of the field layout scheme
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the field layout scheme
     *
     * @param description description
     * @return this
     */
    public FieldLayoutSchemePayload description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the field layout scheme
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the field layout scheme
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for explicitMappings.
     * <p>
     * There is a default configuration "fieldlayout" that is applied to all issue types using this scheme that don't have an explicit mapping users can create (or re-use existing) configurations for other issue types and map them to this scheme
     *
     * @return explicitMappings
     */
    public Map<String, ProjectCreateResourceIdentifier> explicitMappings() {
        return this.explicitMappings;
    }

    /**
     * Fluent setter for explicitMappings.
     * <p>
     * There is a default configuration "fieldlayout" that is applied to all issue types using this scheme that don't have an explicit mapping users can create (or re-use existing) configurations for other issue types and map them to this scheme
     *
     * @param explicitMappings explicitMappings
     * @return this
     */
    public FieldLayoutSchemePayload explicitMappings(Map<String, ProjectCreateResourceIdentifier> explicitMappings) {
        this.explicitMappings = explicitMappings;
        return this;
    }

    /**
     * Gets the value of explicitMappings.
     * <p>
     * There is a default configuration "fieldlayout" that is applied to all issue types using this scheme that don't have an explicit mapping users can create (or re-use existing) configurations for other issue types and map them to this scheme
     *
     * @return explicitMappings
     */
    @JsonProperty("explicitMappings")
    public Map<String, ProjectCreateResourceIdentifier> getExplicitMappings() {
        return this.explicitMappings;
    }

    /**
     * Sets the value of explicitMappings.
     * <p>
     * There is a default configuration "fieldlayout" that is applied to all issue types using this scheme that don't have an explicit mapping users can create (or re-use existing) configurations for other issue types and map them to this scheme
     *
     * @param explicitMappings explicitMappings
     */
    public void setExplicitMappings(Map<String, ProjectCreateResourceIdentifier> explicitMappings) {
        this.explicitMappings = explicitMappings;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the field layout scheme
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the field layout scheme
     *
     * @param name name
     * @return this
     */
    public FieldLayoutSchemePayload name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the field layout scheme
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the field layout scheme
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @return pcri
     */
    public ProjectCreateResourceIdentifier pcri() {
        return this.pcri;
    }

    /**
     * Fluent setter for pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @param pcri pcri
     * @return this
     */
    public FieldLayoutSchemePayload pcri(ProjectCreateResourceIdentifier pcri) {
        this.pcri = pcri;
        return this;
    }

    /**
     * Gets the value of pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @return pcri
     */
    @JsonProperty("pcri")
    public ProjectCreateResourceIdentifier getPcri() {
        return this.pcri;
    }

    /**
     * Sets the value of pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @param pcri pcri
     */
    public void setPcri(ProjectCreateResourceIdentifier pcri) {
        this.pcri = pcri;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldLayoutSchemePayload that = (FieldLayoutSchemePayload) o;
        return
            Objects.equals(this.defaultFieldLayout, that.defaultFieldLayout) &&
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.explicitMappings, that.explicitMappings) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.pcri, that.pcri);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.defaultFieldLayout, 
            this.description, 
            this.explicitMappings, 
            this.name, 
            this.pcri
        );
    }

    @Override
    public String toString() {
        return "FieldLayoutSchemePayload{"
            + "defaultFieldLayout=" + defaultFieldLayout + ", "
            + "description=" + description + ", "
            + "explicitMappings=" + explicitMappings + ", "
            + "name=" + name + ", "
            + "pcri=" + pcri
            + "}";
    }
}
