// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * FieldConfigurationItem
 * <p>
 * A field within a field configuration.
 *
 */
@JsonTypeName("FieldConfigurationItem")
@JsonPropertyOrder({
    "description",
    "id",
    "isHidden",
    "isRequired",
    "renderer"
})
@Generated(value = "io.github.primelib.primecodegen")
public class FieldConfigurationItem {

    /**
     * The description of the field within the field configuration.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * The ID of the field within the field configuration.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * Whether the field is hidden in the field configuration.
     */
    @JsonProperty("isHidden")
    protected Boolean isHidden;

    /**
     * Whether the field is required in the field configuration.
     */
    @JsonProperty("isRequired")
    protected Boolean isRequired;

    /**
     * The renderer type for the field within the field configuration.
     */
    @JsonProperty("renderer")
    protected String renderer;

    /**
     * Constructs a validated instance of {@link FieldConfigurationItem}.
     *
     * @param spec the specification to process
     */
    public FieldConfigurationItem(Consumer<FieldConfigurationItem> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected FieldConfigurationItem() {
    }
    /**
     * Constructs a validated instance of {@link FieldConfigurationItem}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #FieldConfigurationItem(Consumer)} instead.
     * @param description The description of the field within the field configuration.
     * @param id The ID of the field within the field configuration.
     * @param isHidden Whether the field is hidden in the field configuration.
     * @param isRequired Whether the field is required in the field configuration.
     * @param renderer The renderer type for the field within the field configuration.
     */
    @ApiStatus.Internal
    public FieldConfigurationItem(String description, String id, Boolean isHidden, Boolean isRequired, String renderer) {
        this.description = description;
        this.id = id;
        this.isHidden = isHidden;
        this.isRequired = isRequired;
        this.renderer = renderer;
    }


    /**
     * Fluent getter for description.
     * <p>
     * The description of the field within the field configuration.
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the field within the field configuration.
     *
     * @param description description
     * @return this
     */
    public FieldConfigurationItem description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the field within the field configuration.
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the field within the field configuration.
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for id.
     * <p>
     * The ID of the field within the field configuration.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The ID of the field within the field configuration.
     *
     * @param id id
     * @return this
     */
    public FieldConfigurationItem id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The ID of the field within the field configuration.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The ID of the field within the field configuration.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * Fluent getter for isHidden.
     * <p>
     * Whether the field is hidden in the field configuration.
     *
     * @return isHidden
     */
    public Boolean isHidden() {
        return this.isHidden;
    }

    /**
     * Fluent setter for isHidden.
     * <p>
     * Whether the field is hidden in the field configuration.
     *
     * @param isHidden isHidden
     * @return this
     */
    public FieldConfigurationItem isHidden(Boolean isHidden) {
        this.isHidden = isHidden;
        return this;
    }

    /**
     * Gets the value of isHidden.
     * <p>
     * Whether the field is hidden in the field configuration.
     *
     * @return isHidden
     */
    @JsonProperty("isHidden")
    public Boolean getIsHidden() {
        return this.isHidden;
    }

    /**
     * Sets the value of isHidden.
     * <p>
     * Whether the field is hidden in the field configuration.
     *
     * @param isHidden isHidden
     */
    public void setIsHidden(Boolean isHidden) {
        this.isHidden = isHidden;
    }
    /**
     * Fluent getter for isRequired.
     * <p>
     * Whether the field is required in the field configuration.
     *
     * @return isRequired
     */
    public Boolean isRequired() {
        return this.isRequired;
    }

    /**
     * Fluent setter for isRequired.
     * <p>
     * Whether the field is required in the field configuration.
     *
     * @param isRequired isRequired
     * @return this
     */
    public FieldConfigurationItem isRequired(Boolean isRequired) {
        this.isRequired = isRequired;
        return this;
    }

    /**
     * Gets the value of isRequired.
     * <p>
     * Whether the field is required in the field configuration.
     *
     * @return isRequired
     */
    @JsonProperty("isRequired")
    public Boolean getIsRequired() {
        return this.isRequired;
    }

    /**
     * Sets the value of isRequired.
     * <p>
     * Whether the field is required in the field configuration.
     *
     * @param isRequired isRequired
     */
    public void setIsRequired(Boolean isRequired) {
        this.isRequired = isRequired;
    }
    /**
     * Fluent getter for renderer.
     * <p>
     * The renderer type for the field within the field configuration.
     *
     * @return renderer
     */
    public String renderer() {
        return this.renderer;
    }

    /**
     * Fluent setter for renderer.
     * <p>
     * The renderer type for the field within the field configuration.
     *
     * @param renderer renderer
     * @return this
     */
    public FieldConfigurationItem renderer(String renderer) {
        this.renderer = renderer;
        return this;
    }

    /**
     * Gets the value of renderer.
     * <p>
     * The renderer type for the field within the field configuration.
     *
     * @return renderer
     */
    @JsonProperty("renderer")
    public String getRenderer() {
        return this.renderer;
    }

    /**
     * Sets the value of renderer.
     * <p>
     * The renderer type for the field within the field configuration.
     *
     * @param renderer renderer
     */
    public void setRenderer(String renderer) {
        this.renderer = renderer;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldConfigurationItem that = (FieldConfigurationItem) o;
        return
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.isHidden, that.isHidden) &&
            Objects.equals(this.isRequired, that.isRequired) &&
            Objects.equals(this.renderer, that.renderer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.description, 
            this.id, 
            this.isHidden, 
            this.isRequired, 
            this.renderer
        );
    }

    @Override
    public String toString() {
        return "FieldConfigurationItem{"
            + "description=" + description + ", "
            + "id=" + id + ", "
            + "isHidden=" + isHidden + ", "
            + "isRequired=" + isRequired + ", "
            + "renderer=" + renderer
            + "}";
    }
}
