// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * FieldConfigurationItemsDetails
 * <p>
 * Details of field configuration items.
 *
 */
@JsonTypeName("FieldConfigurationItemsDetails")
@JsonPropertyOrder({
    "fieldConfigurationItems"
})
@Generated(value = "io.github.primelib.primecodegen")
public class FieldConfigurationItemsDetails {

    /**
     * Details of fields in a field configuration.
     */
    @JsonProperty("fieldConfigurationItems")
    protected List<FieldConfigurationItem> fieldConfigurationItems;

    /**
     * Constructs a validated instance of {@link FieldConfigurationItemsDetails}.
     *
     * @param spec the specification to process
     */
    public FieldConfigurationItemsDetails(Consumer<FieldConfigurationItemsDetails> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected FieldConfigurationItemsDetails() {
    }
    /**
     * Constructs a validated instance of {@link FieldConfigurationItemsDetails}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #FieldConfigurationItemsDetails(Consumer)} instead.
     * @param fieldConfigurationItems Details of fields in a field configuration.
     */
    @ApiStatus.Internal
    public FieldConfigurationItemsDetails(List<FieldConfigurationItem> fieldConfigurationItems) {
        this.fieldConfigurationItems = fieldConfigurationItems;
    }


    /**
     * Fluent getter for fieldConfigurationItems.
     * <p>
     * Details of fields in a field configuration.
     *
     * @return fieldConfigurationItems
     */
    public List<FieldConfigurationItem> fieldConfigurationItems() {
        return this.fieldConfigurationItems;
    }

    /**
     * Fluent setter for fieldConfigurationItems.
     * <p>
     * Details of fields in a field configuration.
     *
     * @param fieldConfigurationItems fieldConfigurationItems
     * @return this
     */
    public FieldConfigurationItemsDetails fieldConfigurationItems(List<FieldConfigurationItem> fieldConfigurationItems) {
        this.fieldConfigurationItems = fieldConfigurationItems;
        return this;
    }

    /**
     * Gets the value of fieldConfigurationItems.
     * <p>
     * Details of fields in a field configuration.
     *
     * @return fieldConfigurationItems
     */
    @JsonProperty("fieldConfigurationItems")
    public List<FieldConfigurationItem> getFieldConfigurationItems() {
        return this.fieldConfigurationItems;
    }

    /**
     * Sets the value of fieldConfigurationItems.
     * <p>
     * Details of fields in a field configuration.
     *
     * @param fieldConfigurationItems fieldConfigurationItems
     */
    public void setFieldConfigurationItems(List<FieldConfigurationItem> fieldConfigurationItems) {
        this.fieldConfigurationItems = fieldConfigurationItems;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldConfigurationItemsDetails that = (FieldConfigurationItemsDetails) o;
        return
            Objects.equals(this.fieldConfigurationItems, that.fieldConfigurationItems);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.fieldConfigurationItems
        );
    }

    @Override
    public String toString() {
        return "FieldConfigurationItemsDetails{"
            + "fieldConfigurationItems=" + fieldConfigurationItems
            + "}";
    }
}
