// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * GetPermissionHolderResponse
 *
 */
@JsonTypeName("GetPermissionHolderResponse")
@JsonPropertyOrder({
    "type",
    "value"
})
@Generated(value = "io.github.primelib.primecodegen")
public class GetPermissionHolderResponse {

    /**
     * The permission holder type. This is "Group" or "AccountId".
     */
    @JsonProperty("type")
    protected String type;

    /**
     * The permission holder value. This is a group name if the type is "Group" or an account ID if the type is "AccountId".
     */
    @JsonProperty("value")
    protected String value;

    /**
     * Constructs a validated instance of {@link GetPermissionHolderResponse}.
     *
     * @param spec the specification to process
     */
    public GetPermissionHolderResponse(Consumer<GetPermissionHolderResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected GetPermissionHolderResponse() {
    }
    /**
     * Constructs a validated instance of {@link GetPermissionHolderResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #GetPermissionHolderResponse(Consumer)} instead.
     * @param type The permission holder type. This is "Group" or "AccountId".
     * @param value The permission holder value. This is a group name if the type is "Group" or an account ID if the type is "AccountId".
     */
    @ApiStatus.Internal
    public GetPermissionHolderResponse(String type, String value) {
        this.type = type;
        this.value = value;
    }


    /**
     * Fluent getter for type.
     * <p>
     * The permission holder type. This is "Group" or "AccountId".
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     * <p>
     * The permission holder type. This is "Group" or "AccountId".
     *
     * @param type type
     * @return this
     */
    public GetPermissionHolderResponse type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     * <p>
     * The permission holder type. This is "Group" or "AccountId".
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     * <p>
     * The permission holder type. This is "Group" or "AccountId".
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }
    /**
     * Fluent getter for value.
     * <p>
     * The permission holder value. This is a group name if the type is "Group" or an account ID if the type is "AccountId".
     *
     * @return value
     */
    public String value() {
        return this.value;
    }

    /**
     * Fluent setter for value.
     * <p>
     * The permission holder value. This is a group name if the type is "Group" or an account ID if the type is "AccountId".
     *
     * @param value value
     * @return this
     */
    public GetPermissionHolderResponse value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Gets the value of value.
     * <p>
     * The permission holder value. This is a group name if the type is "Group" or an account ID if the type is "AccountId".
     *
     * @return value
     */
    @JsonProperty("value")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of value.
     * <p>
     * The permission holder value. This is a group name if the type is "Group" or an account ID if the type is "AccountId".
     *
     * @param value value
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GetPermissionHolderResponse that = (GetPermissionHolderResponse) o;
        return
            Objects.equals(this.type, that.type) &&
            Objects.equals(this.value, that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.type, 
            this.value
        );
    }

    @Override
    public String toString() {
        return "GetPermissionHolderResponse{"
            + "type=" + type + ", "
            + "value=" + value
            + "}";
    }
}
