// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * GetPlanOnlyTeamResponse
 *
 */
@JsonTypeName("GetPlanOnlyTeamResponse")
@JsonPropertyOrder({
    "capacity",
    "id",
    "issueSourceId",
    "memberAccountIds",
    "name",
    "planningStyle",
    "sprintLength"
})
@Generated(value = "io.github.primelib.primecodegen")
public class GetPlanOnlyTeamResponse {

    /**
     * The capacity for the plan-only team.
     */
    @JsonProperty("capacity")
    protected Double capacity;

    /**
     * The plan-only team ID.
     */
    @JsonProperty("id")
    protected Long id;

    /**
     * The ID of the issue source for the plan-only team.
     */
    @JsonProperty("issueSourceId")
    protected Long issueSourceId;

    /**
     * The account IDs of the plan-only team members.
     */
    @JsonProperty("memberAccountIds")
    protected List<String> memberAccountIds;

    /**
     * The plan-only team name.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The planning style for the plan-only team. This is "Scrum" or "Kanban".
     */
    @JsonProperty("planningStyle")
    protected String planningStyle;

    /**
     * The sprint length for the plan-only team.
     */
    @JsonProperty("sprintLength")
    protected Long sprintLength;

    /**
     * Constructs a validated instance of {@link GetPlanOnlyTeamResponse}.
     *
     * @param spec the specification to process
     */
    public GetPlanOnlyTeamResponse(Consumer<GetPlanOnlyTeamResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected GetPlanOnlyTeamResponse() {
    }
    /**
     * Constructs a validated instance of {@link GetPlanOnlyTeamResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #GetPlanOnlyTeamResponse(Consumer)} instead.
     * @param capacity The capacity for the plan-only team.
     * @param id The plan-only team ID.
     * @param issueSourceId The ID of the issue source for the plan-only team.
     * @param memberAccountIds The account IDs of the plan-only team members.
     * @param name The plan-only team name.
     * @param planningStyle The planning style for the plan-only team. This is "Scrum" or "Kanban".
     * @param sprintLength The sprint length for the plan-only team.
     */
    @ApiStatus.Internal
    public GetPlanOnlyTeamResponse(Double capacity, Long id, Long issueSourceId, List<String> memberAccountIds, String name, String planningStyle, Long sprintLength) {
        this.capacity = capacity;
        this.id = id;
        this.issueSourceId = issueSourceId;
        this.memberAccountIds = memberAccountIds;
        this.name = name;
        this.planningStyle = planningStyle;
        this.sprintLength = sprintLength;
    }


    /**
     * Fluent getter for capacity.
     * <p>
     * The capacity for the plan-only team.
     *
     * @return capacity
     */
    public Double capacity() {
        return this.capacity;
    }

    /**
     * Fluent setter for capacity.
     * <p>
     * The capacity for the plan-only team.
     *
     * @param capacity capacity
     * @return this
     */
    public GetPlanOnlyTeamResponse capacity(Double capacity) {
        this.capacity = capacity;
        return this;
    }

    /**
     * Gets the value of capacity.
     * <p>
     * The capacity for the plan-only team.
     *
     * @return capacity
     */
    @JsonProperty("capacity")
    public Double getCapacity() {
        return this.capacity;
    }

    /**
     * Sets the value of capacity.
     * <p>
     * The capacity for the plan-only team.
     *
     * @param capacity capacity
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }
    /**
     * Fluent getter for id.
     * <p>
     * The plan-only team ID.
     *
     * @return id
     */
    public Long id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The plan-only team ID.
     *
     * @param id id
     * @return this
     */
    public GetPlanOnlyTeamResponse id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The plan-only team ID.
     *
     * @return id
     */
    @JsonProperty("id")
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The plan-only team ID.
     *
     * @param id id
     */
    public void setId(Long id) {
        this.id = id;
    }
    /**
     * Fluent getter for issueSourceId.
     * <p>
     * The ID of the issue source for the plan-only team.
     *
     * @return issueSourceId
     */
    public Long issueSourceId() {
        return this.issueSourceId;
    }

    /**
     * Fluent setter for issueSourceId.
     * <p>
     * The ID of the issue source for the plan-only team.
     *
     * @param issueSourceId issueSourceId
     * @return this
     */
    public GetPlanOnlyTeamResponse issueSourceId(Long issueSourceId) {
        this.issueSourceId = issueSourceId;
        return this;
    }

    /**
     * Gets the value of issueSourceId.
     * <p>
     * The ID of the issue source for the plan-only team.
     *
     * @return issueSourceId
     */
    @JsonProperty("issueSourceId")
    public Long getIssueSourceId() {
        return this.issueSourceId;
    }

    /**
     * Sets the value of issueSourceId.
     * <p>
     * The ID of the issue source for the plan-only team.
     *
     * @param issueSourceId issueSourceId
     */
    public void setIssueSourceId(Long issueSourceId) {
        this.issueSourceId = issueSourceId;
    }
    /**
     * Fluent getter for memberAccountIds.
     * <p>
     * The account IDs of the plan-only team members.
     *
     * @return memberAccountIds
     */
    public List<String> memberAccountIds() {
        return this.memberAccountIds;
    }

    /**
     * Fluent setter for memberAccountIds.
     * <p>
     * The account IDs of the plan-only team members.
     *
     * @param memberAccountIds memberAccountIds
     * @return this
     */
    public GetPlanOnlyTeamResponse memberAccountIds(List<String> memberAccountIds) {
        this.memberAccountIds = memberAccountIds;
        return this;
    }

    /**
     * Gets the value of memberAccountIds.
     * <p>
     * The account IDs of the plan-only team members.
     *
     * @return memberAccountIds
     */
    @JsonProperty("memberAccountIds")
    public List<String> getMemberAccountIds() {
        return this.memberAccountIds;
    }

    /**
     * Sets the value of memberAccountIds.
     * <p>
     * The account IDs of the plan-only team members.
     *
     * @param memberAccountIds memberAccountIds
     */
    public void setMemberAccountIds(List<String> memberAccountIds) {
        this.memberAccountIds = memberAccountIds;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The plan-only team name.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The plan-only team name.
     *
     * @param name name
     * @return this
     */
    public GetPlanOnlyTeamResponse name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The plan-only team name.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The plan-only team name.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for planningStyle.
     * <p>
     * The planning style for the plan-only team. This is "Scrum" or "Kanban".
     *
     * @return planningStyle
     */
    public String planningStyle() {
        return this.planningStyle;
    }

    /**
     * Fluent setter for planningStyle.
     * <p>
     * The planning style for the plan-only team. This is "Scrum" or "Kanban".
     *
     * @param planningStyle planningStyle
     * @return this
     */
    public GetPlanOnlyTeamResponse planningStyle(String planningStyle) {
        this.planningStyle = planningStyle;
        return this;
    }

    /**
     * Gets the value of planningStyle.
     * <p>
     * The planning style for the plan-only team. This is "Scrum" or "Kanban".
     *
     * @return planningStyle
     */
    @JsonProperty("planningStyle")
    public String getPlanningStyle() {
        return this.planningStyle;
    }

    /**
     * Sets the value of planningStyle.
     * <p>
     * The planning style for the plan-only team. This is "Scrum" or "Kanban".
     *
     * @param planningStyle planningStyle
     */
    public void setPlanningStyle(String planningStyle) {
        this.planningStyle = planningStyle;
    }
    /**
     * Fluent getter for sprintLength.
     * <p>
     * The sprint length for the plan-only team.
     *
     * @return sprintLength
     */
    public Long sprintLength() {
        return this.sprintLength;
    }

    /**
     * Fluent setter for sprintLength.
     * <p>
     * The sprint length for the plan-only team.
     *
     * @param sprintLength sprintLength
     * @return this
     */
    public GetPlanOnlyTeamResponse sprintLength(Long sprintLength) {
        this.sprintLength = sprintLength;
        return this;
    }

    /**
     * Gets the value of sprintLength.
     * <p>
     * The sprint length for the plan-only team.
     *
     * @return sprintLength
     */
    @JsonProperty("sprintLength")
    public Long getSprintLength() {
        return this.sprintLength;
    }

    /**
     * Sets the value of sprintLength.
     * <p>
     * The sprint length for the plan-only team.
     *
     * @param sprintLength sprintLength
     */
    public void setSprintLength(Long sprintLength) {
        this.sprintLength = sprintLength;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GetPlanOnlyTeamResponse that = (GetPlanOnlyTeamResponse) o;
        return
            Objects.equals(this.capacity, that.capacity) &&
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.issueSourceId, that.issueSourceId) &&
            Objects.equals(this.memberAccountIds, that.memberAccountIds) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.planningStyle, that.planningStyle) &&
            Objects.equals(this.sprintLength, that.sprintLength);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.capacity, 
            this.id, 
            this.issueSourceId, 
            this.memberAccountIds, 
            this.name, 
            this.planningStyle, 
            this.sprintLength
        );
    }

    @Override
    public String toString() {
        return "GetPlanOnlyTeamResponse{"
            + "capacity=" + capacity + ", "
            + "id=" + id + ", "
            + "issueSourceId=" + issueSourceId + ", "
            + "memberAccountIds=" + memberAccountIds + ", "
            + "name=" + name + ", "
            + "planningStyle=" + planningStyle + ", "
            + "sprintLength=" + sprintLength
            + "}";
    }
}
