// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * IncludedFields
 *
 */
@JsonTypeName("IncludedFields")
@JsonPropertyOrder({
    "actuallyIncluded",
    "excluded",
    "included"
})
@Generated(value = "io.github.primelib.primecodegen")
public class IncludedFields {

    @JsonProperty("actuallyIncluded")
    protected List<String> actuallyIncluded;

    @JsonProperty("excluded")
    protected List<String> excluded;

    @JsonProperty("included")
    protected List<String> included;

    /**
     * Constructs a validated instance of {@link IncludedFields}.
     *
     * @param spec the specification to process
     */
    public IncludedFields(Consumer<IncludedFields> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected IncludedFields() {
    }
    /**
     * Constructs a validated instance of {@link IncludedFields}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #IncludedFields(Consumer)} instead.
     * @param actuallyIncluded actuallyIncluded
     * @param excluded excluded
     * @param included included
     */
    @ApiStatus.Internal
    public IncludedFields(List<String> actuallyIncluded, List<String> excluded, List<String> included) {
        this.actuallyIncluded = actuallyIncluded;
        this.excluded = excluded;
        this.included = included;
    }


    /**
     * Fluent getter for actuallyIncluded.
     *
     * @return actuallyIncluded
     */
    public List<String> actuallyIncluded() {
        return this.actuallyIncluded;
    }

    /**
     * Fluent setter for actuallyIncluded.
     *
     * @param actuallyIncluded actuallyIncluded
     * @return this
     */
    public IncludedFields actuallyIncluded(List<String> actuallyIncluded) {
        this.actuallyIncluded = actuallyIncluded;
        return this;
    }

    /**
     * Gets the value of actuallyIncluded.
     *
     * @return actuallyIncluded
     */
    @JsonProperty("actuallyIncluded")
    public List<String> getActuallyIncluded() {
        return this.actuallyIncluded;
    }

    /**
     * Sets the value of actuallyIncluded.
     *
     * @param actuallyIncluded actuallyIncluded
     */
    public void setActuallyIncluded(List<String> actuallyIncluded) {
        this.actuallyIncluded = actuallyIncluded;
    }
    /**
     * Fluent getter for excluded.
     *
     * @return excluded
     */
    public List<String> excluded() {
        return this.excluded;
    }

    /**
     * Fluent setter for excluded.
     *
     * @param excluded excluded
     * @return this
     */
    public IncludedFields excluded(List<String> excluded) {
        this.excluded = excluded;
        return this;
    }

    /**
     * Gets the value of excluded.
     *
     * @return excluded
     */
    @JsonProperty("excluded")
    public List<String> getExcluded() {
        return this.excluded;
    }

    /**
     * Sets the value of excluded.
     *
     * @param excluded excluded
     */
    public void setExcluded(List<String> excluded) {
        this.excluded = excluded;
    }
    /**
     * Fluent getter for included.
     *
     * @return included
     */
    public List<String> included() {
        return this.included;
    }

    /**
     * Fluent setter for included.
     *
     * @param included included
     * @return this
     */
    public IncludedFields included(List<String> included) {
        this.included = included;
        return this;
    }

    /**
     * Gets the value of included.
     *
     * @return included
     */
    @JsonProperty("included")
    public List<String> getIncluded() {
        return this.included;
    }

    /**
     * Sets the value of included.
     *
     * @param included included
     */
    public void setIncluded(List<String> included) {
        this.included = included;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IncludedFields that = (IncludedFields) o;
        return
            Objects.equals(this.actuallyIncluded, that.actuallyIncluded) &&
            Objects.equals(this.excluded, that.excluded) &&
            Objects.equals(this.included, that.included);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.actuallyIncluded, 
            this.excluded, 
            this.included
        );
    }

    @Override
    public String toString() {
        return "IncludedFields{"
            + "actuallyIncluded=" + actuallyIncluded + ", "
            + "excluded=" + excluded + ", "
            + "included=" + included
            + "}";
    }
}
