// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * IssueTypeIssueCreateMetadata
 * <p>
 * Details of the issue creation metadata for an issue type.
 *
 */
@JsonTypeName("IssueTypeIssueCreateMetadata")
@JsonPropertyOrder({
    "avatarId",
    "description",
    "entityId",
    "expand",
    "fields",
    "hierarchyLevel",
    "iconUrl",
    "id",
    "name",
    "scope",
    "self",
    "subtask"
})
@Generated(value = "io.github.primelib.primecodegen")
public class IssueTypeIssueCreateMetadata {

    /**
     * The ID of the issue type's avatar.
     */
    @JsonProperty("avatarId")
    protected Long avatarId;

    /**
     * The description of the issue type.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * Unique ID for next-gen projects.
     */
    @JsonProperty("entityId")
    protected UUID entityId;

    /**
     * Expand options that include additional issue type metadata details in the response.
     */
    @JsonProperty("expand")
    protected String expand;

    /**
     * List of the fields available when creating an issue for the issue type.
     */
    @JsonProperty("fields")
    protected Map<String, FieldMetadata> fields;

    /**
     * Hierarchy level of the issue type.
     */
    @JsonProperty("hierarchyLevel")
    protected Integer hierarchyLevel;

    /**
     * The URL of the issue type's avatar.
     */
    @JsonProperty("iconUrl")
    protected String iconUrl;

    /**
     * The ID of the issue type.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The name of the issue type.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Details of the next-gen projects the issue type is available in.
     */
    @JsonProperty("scope")
    protected Object scope;

    /**
     * The URL of these issue type details.
     */
    @JsonProperty("self")
    protected String self;

    /**
     * Whether this issue type is used to create subtasks.
     */
    @JsonProperty("subtask")
    protected Boolean subtask;

    /**
     * Constructs a validated instance of {@link IssueTypeIssueCreateMetadata}.
     *
     * @param spec the specification to process
     */
    public IssueTypeIssueCreateMetadata(Consumer<IssueTypeIssueCreateMetadata> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected IssueTypeIssueCreateMetadata() {
    }
    /**
     * Constructs a validated instance of {@link IssueTypeIssueCreateMetadata}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #IssueTypeIssueCreateMetadata(Consumer)} instead.
     * @param avatarId The ID of the issue type's avatar.
     * @param description The description of the issue type.
     * @param entityId Unique ID for next-gen projects.
     * @param expand Expand options that include additional issue type metadata details in the response.
     * @param fields List of the fields available when creating an issue for the issue type.
     * @param hierarchyLevel Hierarchy level of the issue type.
     * @param iconUrl The URL of the issue type's avatar.
     * @param id The ID of the issue type.
     * @param name The name of the issue type.
     * @param scope Details of the next-gen projects the issue type is available in.
     * @param self The URL of these issue type details.
     * @param subtask Whether this issue type is used to create subtasks.
     */
    @ApiStatus.Internal
    public IssueTypeIssueCreateMetadata(Long avatarId, String description, UUID entityId, String expand, Map<String, FieldMetadata> fields, Integer hierarchyLevel, String iconUrl, String id, String name, Object scope, String self, Boolean subtask) {
        this.avatarId = avatarId;
        this.description = description;
        this.entityId = entityId;
        this.expand = expand;
        this.fields = fields;
        this.hierarchyLevel = hierarchyLevel;
        this.iconUrl = iconUrl;
        this.id = id;
        this.name = name;
        this.scope = scope;
        this.self = self;
        this.subtask = subtask;
    }


    /**
     * Fluent getter for avatarId.
     * <p>
     * The ID of the issue type's avatar.
     *
     * @return avatarId
     */
    public Long avatarId() {
        return this.avatarId;
    }

    /**
     * Fluent setter for avatarId.
     * <p>
     * The ID of the issue type's avatar.
     *
     * @param avatarId avatarId
     * @return this
     */
    public IssueTypeIssueCreateMetadata avatarId(Long avatarId) {
        this.avatarId = avatarId;
        return this;
    }

    /**
     * Gets the value of avatarId.
     * <p>
     * The ID of the issue type's avatar.
     *
     * @return avatarId
     */
    @JsonProperty("avatarId")
    public Long getAvatarId() {
        return this.avatarId;
    }

    /**
     * Sets the value of avatarId.
     * <p>
     * The ID of the issue type's avatar.
     *
     * @param avatarId avatarId
     */
    public void setAvatarId(Long avatarId) {
        this.avatarId = avatarId;
    }
    /**
     * Fluent getter for description.
     * <p>
     * The description of the issue type.
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the issue type.
     *
     * @param description description
     * @return this
     */
    public IssueTypeIssueCreateMetadata description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the issue type.
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the issue type.
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for entityId.
     * <p>
     * Unique ID for next-gen projects.
     *
     * @return entityId
     */
    public UUID entityId() {
        return this.entityId;
    }

    /**
     * Fluent setter for entityId.
     * <p>
     * Unique ID for next-gen projects.
     *
     * @param entityId entityId
     * @return this
     */
    public IssueTypeIssueCreateMetadata entityId(UUID entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * Gets the value of entityId.
     * <p>
     * Unique ID for next-gen projects.
     *
     * @return entityId
     */
    @JsonProperty("entityId")
    public UUID getEntityId() {
        return this.entityId;
    }

    /**
     * Sets the value of entityId.
     * <p>
     * Unique ID for next-gen projects.
     *
     * @param entityId entityId
     */
    public void setEntityId(UUID entityId) {
        this.entityId = entityId;
    }
    /**
     * Fluent getter for expand.
     * <p>
     * Expand options that include additional issue type metadata details in the response.
     *
     * @return expand
     */
    public String expand() {
        return this.expand;
    }

    /**
     * Fluent setter for expand.
     * <p>
     * Expand options that include additional issue type metadata details in the response.
     *
     * @param expand expand
     * @return this
     */
    public IssueTypeIssueCreateMetadata expand(String expand) {
        this.expand = expand;
        return this;
    }

    /**
     * Gets the value of expand.
     * <p>
     * Expand options that include additional issue type metadata details in the response.
     *
     * @return expand
     */
    @JsonProperty("expand")
    public String getExpand() {
        return this.expand;
    }

    /**
     * Sets the value of expand.
     * <p>
     * Expand options that include additional issue type metadata details in the response.
     *
     * @param expand expand
     */
    public void setExpand(String expand) {
        this.expand = expand;
    }
    /**
     * Fluent getter for fields.
     * <p>
     * List of the fields available when creating an issue for the issue type.
     *
     * @return fields
     */
    public Map<String, FieldMetadata> fields() {
        return this.fields;
    }

    /**
     * Fluent setter for fields.
     * <p>
     * List of the fields available when creating an issue for the issue type.
     *
     * @param fields fields
     * @return this
     */
    public IssueTypeIssueCreateMetadata fields(Map<String, FieldMetadata> fields) {
        this.fields = fields;
        return this;
    }

    /**
     * Gets the value of fields.
     * <p>
     * List of the fields available when creating an issue for the issue type.
     *
     * @return fields
     */
    @JsonProperty("fields")
    public Map<String, FieldMetadata> getFields() {
        return this.fields;
    }

    /**
     * Sets the value of fields.
     * <p>
     * List of the fields available when creating an issue for the issue type.
     *
     * @param fields fields
     */
    public void setFields(Map<String, FieldMetadata> fields) {
        this.fields = fields;
    }
    /**
     * Fluent getter for hierarchyLevel.
     * <p>
     * Hierarchy level of the issue type.
     *
     * @return hierarchyLevel
     */
    public Integer hierarchyLevel() {
        return this.hierarchyLevel;
    }

    /**
     * Fluent setter for hierarchyLevel.
     * <p>
     * Hierarchy level of the issue type.
     *
     * @param hierarchyLevel hierarchyLevel
     * @return this
     */
    public IssueTypeIssueCreateMetadata hierarchyLevel(Integer hierarchyLevel) {
        this.hierarchyLevel = hierarchyLevel;
        return this;
    }

    /**
     * Gets the value of hierarchyLevel.
     * <p>
     * Hierarchy level of the issue type.
     *
     * @return hierarchyLevel
     */
    @JsonProperty("hierarchyLevel")
    public Integer getHierarchyLevel() {
        return this.hierarchyLevel;
    }

    /**
     * Sets the value of hierarchyLevel.
     * <p>
     * Hierarchy level of the issue type.
     *
     * @param hierarchyLevel hierarchyLevel
     */
    public void setHierarchyLevel(Integer hierarchyLevel) {
        this.hierarchyLevel = hierarchyLevel;
    }
    /**
     * Fluent getter for iconUrl.
     * <p>
     * The URL of the issue type's avatar.
     *
     * @return iconUrl
     */
    public String iconUrl() {
        return this.iconUrl;
    }

    /**
     * Fluent setter for iconUrl.
     * <p>
     * The URL of the issue type's avatar.
     *
     * @param iconUrl iconUrl
     * @return this
     */
    public IssueTypeIssueCreateMetadata iconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
        return this;
    }

    /**
     * Gets the value of iconUrl.
     * <p>
     * The URL of the issue type's avatar.
     *
     * @return iconUrl
     */
    @JsonProperty("iconUrl")
    public String getIconUrl() {
        return this.iconUrl;
    }

    /**
     * Sets the value of iconUrl.
     * <p>
     * The URL of the issue type's avatar.
     *
     * @param iconUrl iconUrl
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }
    /**
     * Fluent getter for id.
     * <p>
     * The ID of the issue type.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The ID of the issue type.
     *
     * @param id id
     * @return this
     */
    public IssueTypeIssueCreateMetadata id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The ID of the issue type.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The ID of the issue type.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the issue type.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the issue type.
     *
     * @param name name
     * @return this
     */
    public IssueTypeIssueCreateMetadata name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the issue type.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the issue type.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for scope.
     * <p>
     * Details of the next-gen projects the issue type is available in.
     *
     * @return scope
     */
    public Object scope() {
        return this.scope;
    }

    /**
     * Fluent setter for scope.
     * <p>
     * Details of the next-gen projects the issue type is available in.
     *
     * @param scope scope
     * @return this
     */
    public IssueTypeIssueCreateMetadata scope(Object scope) {
        this.scope = scope;
        return this;
    }

    /**
     * Gets the value of scope.
     * <p>
     * Details of the next-gen projects the issue type is available in.
     *
     * @return scope
     */
    @JsonProperty("scope")
    public Object getScope() {
        return this.scope;
    }

    /**
     * Sets the value of scope.
     * <p>
     * Details of the next-gen projects the issue type is available in.
     *
     * @param scope scope
     */
    public void setScope(Object scope) {
        this.scope = scope;
    }
    /**
     * Fluent getter for self.
     * <p>
     * The URL of these issue type details.
     *
     * @return self
     */
    public String self() {
        return this.self;
    }

    /**
     * Fluent setter for self.
     * <p>
     * The URL of these issue type details.
     *
     * @param self self
     * @return this
     */
    public IssueTypeIssueCreateMetadata self(String self) {
        this.self = self;
        return this;
    }

    /**
     * Gets the value of self.
     * <p>
     * The URL of these issue type details.
     *
     * @return self
     */
    @JsonProperty("self")
    public String getSelf() {
        return this.self;
    }

    /**
     * Sets the value of self.
     * <p>
     * The URL of these issue type details.
     *
     * @param self self
     */
    public void setSelf(String self) {
        this.self = self;
    }
    /**
     * Fluent getter for subtask.
     * <p>
     * Whether this issue type is used to create subtasks.
     *
     * @return subtask
     */
    public Boolean subtask() {
        return this.subtask;
    }

    /**
     * Fluent setter for subtask.
     * <p>
     * Whether this issue type is used to create subtasks.
     *
     * @param subtask subtask
     * @return this
     */
    public IssueTypeIssueCreateMetadata subtask(Boolean subtask) {
        this.subtask = subtask;
        return this;
    }

    /**
     * Gets the value of subtask.
     * <p>
     * Whether this issue type is used to create subtasks.
     *
     * @return subtask
     */
    @JsonProperty("subtask")
    public Boolean getSubtask() {
        return this.subtask;
    }

    /**
     * Sets the value of subtask.
     * <p>
     * Whether this issue type is used to create subtasks.
     *
     * @param subtask subtask
     */
    public void setSubtask(Boolean subtask) {
        this.subtask = subtask;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IssueTypeIssueCreateMetadata that = (IssueTypeIssueCreateMetadata) o;
        return
            Objects.equals(this.avatarId, that.avatarId) &&
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.entityId, that.entityId) &&
            Objects.equals(this.expand, that.expand) &&
            Objects.equals(this.fields, that.fields) &&
            Objects.equals(this.hierarchyLevel, that.hierarchyLevel) &&
            Objects.equals(this.iconUrl, that.iconUrl) &&
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.scope, that.scope) &&
            Objects.equals(this.self, that.self) &&
            Objects.equals(this.subtask, that.subtask);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.avatarId, 
            this.description, 
            this.entityId, 
            this.expand, 
            this.fields, 
            this.hierarchyLevel, 
            this.iconUrl, 
            this.id, 
            this.name, 
            this.scope, 
            this.self, 
            this.subtask
        );
    }

    @Override
    public String toString() {
        return "IssueTypeIssueCreateMetadata{"
            + "avatarId=" + avatarId + ", "
            + "description=" + description + ", "
            + "entityId=" + entityId + ", "
            + "expand=" + expand + ", "
            + "fields=" + fields + ", "
            + "hierarchyLevel=" + hierarchyLevel + ", "
            + "iconUrl=" + iconUrl + ", "
            + "id=" + id + ", "
            + "name=" + name + ", "
            + "scope=" + scope + ", "
            + "self=" + self + ", "
            + "subtask=" + subtask
            + "}";
    }
}
