// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * IssueTypeScreenSchemesProjects
 * <p>
 * Issue type screen scheme with a list of the projects that use it.
 *
 */
@JsonTypeName("IssueTypeScreenSchemesProjects")
@JsonPropertyOrder({
    "issueTypeScreenScheme",
    "projectIds"
})
@Generated(value = "io.github.primelib.primecodegen")
public class IssueTypeScreenSchemesProjects {

    /**
     * Details of an issue type screen scheme.
     */
    @JsonProperty("issueTypeScreenScheme")
    protected Object issueTypeScreenScheme;

    /**
     * The IDs of the projects using the issue type screen scheme.
     */
    @JsonProperty("projectIds")
    protected List<String> projectIds;

    /**
     * Constructs a validated instance of {@link IssueTypeScreenSchemesProjects}.
     *
     * @param spec the specification to process
     */
    public IssueTypeScreenSchemesProjects(Consumer<IssueTypeScreenSchemesProjects> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected IssueTypeScreenSchemesProjects() {
    }
    /**
     * Constructs a validated instance of {@link IssueTypeScreenSchemesProjects}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #IssueTypeScreenSchemesProjects(Consumer)} instead.
     * @param issueTypeScreenScheme Details of an issue type screen scheme.
     * @param projectIds The IDs of the projects using the issue type screen scheme.
     */
    @ApiStatus.Internal
    public IssueTypeScreenSchemesProjects(Object issueTypeScreenScheme, List<String> projectIds) {
        this.issueTypeScreenScheme = issueTypeScreenScheme;
        this.projectIds = projectIds;
    }


    /**
     * Fluent getter for issueTypeScreenScheme.
     * <p>
     * Details of an issue type screen scheme.
     *
     * @return issueTypeScreenScheme
     */
    public Object issueTypeScreenScheme() {
        return this.issueTypeScreenScheme;
    }

    /**
     * Fluent setter for issueTypeScreenScheme.
     * <p>
     * Details of an issue type screen scheme.
     *
     * @param issueTypeScreenScheme issueTypeScreenScheme
     * @return this
     */
    public IssueTypeScreenSchemesProjects issueTypeScreenScheme(Object issueTypeScreenScheme) {
        this.issueTypeScreenScheme = issueTypeScreenScheme;
        return this;
    }

    /**
     * Gets the value of issueTypeScreenScheme.
     * <p>
     * Details of an issue type screen scheme.
     *
     * @return issueTypeScreenScheme
     */
    @JsonProperty("issueTypeScreenScheme")
    public Object getIssueTypeScreenScheme() {
        return this.issueTypeScreenScheme;
    }

    /**
     * Sets the value of issueTypeScreenScheme.
     * <p>
     * Details of an issue type screen scheme.
     *
     * @param issueTypeScreenScheme issueTypeScreenScheme
     */
    public void setIssueTypeScreenScheme(Object issueTypeScreenScheme) {
        this.issueTypeScreenScheme = issueTypeScreenScheme;
    }
    /**
     * Fluent getter for projectIds.
     * <p>
     * The IDs of the projects using the issue type screen scheme.
     *
     * @return projectIds
     */
    public List<String> projectIds() {
        return this.projectIds;
    }

    /**
     * Fluent setter for projectIds.
     * <p>
     * The IDs of the projects using the issue type screen scheme.
     *
     * @param projectIds projectIds
     * @return this
     */
    public IssueTypeScreenSchemesProjects projectIds(List<String> projectIds) {
        this.projectIds = projectIds;
        return this;
    }

    /**
     * Gets the value of projectIds.
     * <p>
     * The IDs of the projects using the issue type screen scheme.
     *
     * @return projectIds
     */
    @JsonProperty("projectIds")
    public List<String> getProjectIds() {
        return this.projectIds;
    }

    /**
     * Sets the value of projectIds.
     * <p>
     * The IDs of the projects using the issue type screen scheme.
     *
     * @param projectIds projectIds
     */
    public void setProjectIds(List<String> projectIds) {
        this.projectIds = projectIds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IssueTypeScreenSchemesProjects that = (IssueTypeScreenSchemesProjects) o;
        return
            Objects.equals(this.issueTypeScreenScheme, that.issueTypeScreenScheme) &&
            Objects.equals(this.projectIds, that.projectIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.issueTypeScreenScheme, 
            this.projectIds
        );
    }

    @Override
    public String toString() {
        return "IssueTypeScreenSchemesProjects{"
            + "issueTypeScreenScheme=" + issueTypeScreenScheme + ", "
            + "projectIds=" + projectIds
            + "}";
    }
}
