// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * IssueTypeUpdateBean
 *
 */
@JsonTypeName("IssueTypeUpdateBean")
@JsonPropertyOrder({
    "avatarId",
    "description",
    "name"
})
@Generated(value = "io.github.primelib.primecodegen")
public class IssueTypeUpdateBean {

    /**
     * The ID of an issue type avatar. This can be obtained be obtained from the following endpoints:

 *  [System issue type avatar IDs only](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-avatar-type-system-get)
 *  [System and custom issue type avatar IDs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-universal-avatar-type-type-owner-entityid-get)
     */
    @JsonProperty("avatarId")
    protected Long avatarId;

    /**
     * The description of the issue type.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * The unique name for the issue type. The maximum length is 60 characters.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Constructs a validated instance of {@link IssueTypeUpdateBean}.
     *
     * @param spec the specification to process
     */
    public IssueTypeUpdateBean(Consumer<IssueTypeUpdateBean> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected IssueTypeUpdateBean() {
    }
    /**
     * Constructs a validated instance of {@link IssueTypeUpdateBean}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #IssueTypeUpdateBean(Consumer)} instead.
     * @param avatarId The ID of an issue type avatar. This can be obtained be obtained from the following endpoints:

 *  [System issue type avatar IDs only](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-avatar-type-system-get)
 *  [System and custom issue type avatar IDs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-universal-avatar-type-type-owner-entityid-get)
     * @param description The description of the issue type.
     * @param name The unique name for the issue type. The maximum length is 60 characters.
     */
    @ApiStatus.Internal
    public IssueTypeUpdateBean(Long avatarId, String description, String name) {
        this.avatarId = avatarId;
        this.description = description;
        this.name = name;
    }


    /**
     * Fluent getter for avatarId.
     * <p>
     * The ID of an issue type avatar. This can be obtained be obtained from the following endpoints:
     * 
     *  *  [System issue type avatar IDs only](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-avatar-type-system-get)
     *  *  [System and custom issue type avatar IDs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-universal-avatar-type-type-owner-entityid-get)
     *
     * @return avatarId
     */
    public Long avatarId() {
        return this.avatarId;
    }

    /**
     * Fluent setter for avatarId.
     * <p>
     * The ID of an issue type avatar. This can be obtained be obtained from the following endpoints:
     * 
     *  *  [System issue type avatar IDs only](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-avatar-type-system-get)
     *  *  [System and custom issue type avatar IDs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-universal-avatar-type-type-owner-entityid-get)
     *
     * @param avatarId avatarId
     * @return this
     */
    public IssueTypeUpdateBean avatarId(Long avatarId) {
        this.avatarId = avatarId;
        return this;
    }

    /**
     * Gets the value of avatarId.
     * <p>
     * The ID of an issue type avatar. This can be obtained be obtained from the following endpoints:
     * 
     *  *  [System issue type avatar IDs only](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-avatar-type-system-get)
     *  *  [System and custom issue type avatar IDs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-universal-avatar-type-type-owner-entityid-get)
     *
     * @return avatarId
     */
    @JsonProperty("avatarId")
    public Long getAvatarId() {
        return this.avatarId;
    }

    /**
     * Sets the value of avatarId.
     * <p>
     * The ID of an issue type avatar. This can be obtained be obtained from the following endpoints:
     * 
     *  *  [System issue type avatar IDs only](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-avatar-type-system-get)
     *  *  [System and custom issue type avatar IDs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-avatars/#api-rest-api-3-universal-avatar-type-type-owner-entityid-get)
     *
     * @param avatarId avatarId
     */
    public void setAvatarId(Long avatarId) {
        this.avatarId = avatarId;
    }
    /**
     * Fluent getter for description.
     * <p>
     * The description of the issue type.
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the issue type.
     *
     * @param description description
     * @return this
     */
    public IssueTypeUpdateBean description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the issue type.
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the issue type.
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The unique name for the issue type. The maximum length is 60 characters.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The unique name for the issue type. The maximum length is 60 characters.
     *
     * @param name name
     * @return this
     */
    public IssueTypeUpdateBean name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The unique name for the issue type. The maximum length is 60 characters.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The unique name for the issue type. The maximum length is 60 characters.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IssueTypeUpdateBean that = (IssueTypeUpdateBean) o;
        return
            Objects.equals(this.avatarId, that.avatarId) &&
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.name, that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.avatarId, 
            this.description, 
            this.name
        );
    }

    @Override
    public String toString() {
        return "IssueTypeUpdateBean{"
            + "avatarId=" + avatarId + ", "
            + "description=" + description + ", "
            + "name=" + name
            + "}";
    }
}
