// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * IssueTypeSchemeProjectAssociation
 * <p>
 * Details of the association between an issue type scheme and project.
 *
 */
@JsonTypeName("IssueTypeSchemeProjectAssociation")
@JsonPropertyOrder({
    "issueTypeSchemeId",
    "projectId"
})
@Generated(value = "io.github.primelib.primecodegen")
public class IssueTypeSchemeProjectAssociation {

    /**
     * The ID of the issue type scheme.
     */
    @JsonProperty("issueTypeSchemeId")
    protected String issueTypeSchemeId;

    /**
     * The ID of the project.
     */
    @JsonProperty("projectId")
    protected String projectId;

    /**
     * Constructs a validated instance of {@link IssueTypeSchemeProjectAssociation}.
     *
     * @param spec the specification to process
     */
    public IssueTypeSchemeProjectAssociation(Consumer<IssueTypeSchemeProjectAssociation> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected IssueTypeSchemeProjectAssociation() {
    }
    /**
     * Constructs a validated instance of {@link IssueTypeSchemeProjectAssociation}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #IssueTypeSchemeProjectAssociation(Consumer)} instead.
     * @param issueTypeSchemeId The ID of the issue type scheme.
     * @param projectId The ID of the project.
     */
    @ApiStatus.Internal
    public IssueTypeSchemeProjectAssociation(String issueTypeSchemeId, String projectId) {
        this.issueTypeSchemeId = issueTypeSchemeId;
        this.projectId = projectId;
    }


    /**
     * Fluent getter for issueTypeSchemeId.
     * <p>
     * The ID of the issue type scheme.
     *
     * @return issueTypeSchemeId
     */
    public String issueTypeSchemeId() {
        return this.issueTypeSchemeId;
    }

    /**
     * Fluent setter for issueTypeSchemeId.
     * <p>
     * The ID of the issue type scheme.
     *
     * @param issueTypeSchemeId issueTypeSchemeId
     * @return this
     */
    public IssueTypeSchemeProjectAssociation issueTypeSchemeId(String issueTypeSchemeId) {
        this.issueTypeSchemeId = issueTypeSchemeId;
        return this;
    }

    /**
     * Gets the value of issueTypeSchemeId.
     * <p>
     * The ID of the issue type scheme.
     *
     * @return issueTypeSchemeId
     */
    @JsonProperty("issueTypeSchemeId")
    public String getIssueTypeSchemeId() {
        return this.issueTypeSchemeId;
    }

    /**
     * Sets the value of issueTypeSchemeId.
     * <p>
     * The ID of the issue type scheme.
     *
     * @param issueTypeSchemeId issueTypeSchemeId
     */
    public void setIssueTypeSchemeId(String issueTypeSchemeId) {
        this.issueTypeSchemeId = issueTypeSchemeId;
    }
    /**
     * Fluent getter for projectId.
     * <p>
     * The ID of the project.
     *
     * @return projectId
     */
    public String projectId() {
        return this.projectId;
    }

    /**
     * Fluent setter for projectId.
     * <p>
     * The ID of the project.
     *
     * @param projectId projectId
     * @return this
     */
    public IssueTypeSchemeProjectAssociation projectId(String projectId) {
        this.projectId = projectId;
        return this;
    }

    /**
     * Gets the value of projectId.
     * <p>
     * The ID of the project.
     *
     * @return projectId
     */
    @JsonProperty("projectId")
    public String getProjectId() {
        return this.projectId;
    }

    /**
     * Sets the value of projectId.
     * <p>
     * The ID of the project.
     *
     * @param projectId projectId
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IssueTypeSchemeProjectAssociation that = (IssueTypeSchemeProjectAssociation) o;
        return
            Objects.equals(this.issueTypeSchemeId, that.issueTypeSchemeId) &&
            Objects.equals(this.projectId, that.projectId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.issueTypeSchemeId, 
            this.projectId
        );
    }

    @Override
    public String toString() {
        return "IssueTypeSchemeProjectAssociation{"
            + "issueTypeSchemeId=" + issueTypeSchemeId + ", "
            + "projectId=" + projectId
            + "}";
    }
}
