// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * JiraWorkflowPreviewStatus
 * <p>
 * Details of a status.
 *
 */
@JsonTypeName("JiraWorkflowPreviewStatus")
@JsonPropertyOrder({
    "description",
    "id",
    "name",
    "rawName",
    "scope",
    "statusCategory",
    "statusReference"
})
@Generated(value = "io.github.primelib.primecodegen")
public class JiraWorkflowPreviewStatus {

    /**
     * The description of the status.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * The ID of the status.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The name of the status.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The raw name of the status.
     */
    @JsonProperty("rawName")
    protected String rawName;

    /**
     * The scope of the workflow.
     */
    @JsonProperty("scope")
    protected WorkflowPreviewScope scope;

    /**
     * The category of the status.
     */
    @JsonProperty("statusCategory")
    protected String statusCategory;

    /**
     * The reference of the status. Unique within this response but not guaranteed to be stable across requests.
     */
    @JsonProperty("statusReference")
    protected String statusReference;

    /**
     * Constructs a validated instance of {@link JiraWorkflowPreviewStatus}.
     *
     * @param spec the specification to process
     */
    public JiraWorkflowPreviewStatus(Consumer<JiraWorkflowPreviewStatus> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected JiraWorkflowPreviewStatus() {
    }
    /**
     * Constructs a validated instance of {@link JiraWorkflowPreviewStatus}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #JiraWorkflowPreviewStatus(Consumer)} instead.
     * @param description The description of the status.
     * @param id The ID of the status.
     * @param name The name of the status.
     * @param rawName The raw name of the status.
     * @param scope The scope of the workflow.
     * @param statusCategory The category of the status.
     * @param statusReference The reference of the status. Unique within this response but not guaranteed to be stable across requests.
     */
    @ApiStatus.Internal
    public JiraWorkflowPreviewStatus(String description, String id, String name, String rawName, WorkflowPreviewScope scope, String statusCategory, String statusReference) {
        this.description = description;
        this.id = id;
        this.name = name;
        this.rawName = rawName;
        this.scope = scope;
        this.statusCategory = statusCategory;
        this.statusReference = statusReference;
    }


    /**
     * Fluent getter for description.
     * <p>
     * The description of the status.
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the status.
     *
     * @param description description
     * @return this
     */
    public JiraWorkflowPreviewStatus description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the status.
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the status.
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for id.
     * <p>
     * The ID of the status.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The ID of the status.
     *
     * @param id id
     * @return this
     */
    public JiraWorkflowPreviewStatus id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The ID of the status.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The ID of the status.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the status.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the status.
     *
     * @param name name
     * @return this
     */
    public JiraWorkflowPreviewStatus name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the status.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the status.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for rawName.
     * <p>
     * The raw name of the status.
     *
     * @return rawName
     */
    public String rawName() {
        return this.rawName;
    }

    /**
     * Fluent setter for rawName.
     * <p>
     * The raw name of the status.
     *
     * @param rawName rawName
     * @return this
     */
    public JiraWorkflowPreviewStatus rawName(String rawName) {
        this.rawName = rawName;
        return this;
    }

    /**
     * Gets the value of rawName.
     * <p>
     * The raw name of the status.
     *
     * @return rawName
     */
    @JsonProperty("rawName")
    public String getRawName() {
        return this.rawName;
    }

    /**
     * Sets the value of rawName.
     * <p>
     * The raw name of the status.
     *
     * @param rawName rawName
     */
    public void setRawName(String rawName) {
        this.rawName = rawName;
    }
    /**
     * Fluent getter for scope.
     * <p>
     * The scope of the workflow.
     *
     * @return scope
     */
    public WorkflowPreviewScope scope() {
        return this.scope;
    }

    /**
     * Fluent setter for scope.
     * <p>
     * The scope of the workflow.
     *
     * @param scope scope
     * @return this
     */
    public JiraWorkflowPreviewStatus scope(WorkflowPreviewScope scope) {
        this.scope = scope;
        return this;
    }

    /**
     * Gets the value of scope.
     * <p>
     * The scope of the workflow.
     *
     * @return scope
     */
    @JsonProperty("scope")
    public WorkflowPreviewScope getScope() {
        return this.scope;
    }

    /**
     * Sets the value of scope.
     * <p>
     * The scope of the workflow.
     *
     * @param scope scope
     */
    public void setScope(WorkflowPreviewScope scope) {
        this.scope = scope;
    }
    /**
     * Fluent getter for statusCategory.
     * <p>
     * The category of the status.
     *
     * @return statusCategory
     */
    public String statusCategory() {
        return this.statusCategory;
    }

    /**
     * Fluent setter for statusCategory.
     * <p>
     * The category of the status.
     *
     * @param statusCategory statusCategory
     * @return this
     */
    public JiraWorkflowPreviewStatus statusCategory(String statusCategory) {
        this.statusCategory = statusCategory;
        return this;
    }

    /**
     * Gets the value of statusCategory.
     * <p>
     * The category of the status.
     *
     * @return statusCategory
     */
    @JsonProperty("statusCategory")
    public String getStatusCategory() {
        return this.statusCategory;
    }

    /**
     * Sets the value of statusCategory.
     * <p>
     * The category of the status.
     *
     * @param statusCategory statusCategory
     */
    public void setStatusCategory(String statusCategory) {
        this.statusCategory = statusCategory;
    }
    /**
     * Fluent getter for statusReference.
     * <p>
     * The reference of the status. Unique within this response but not guaranteed to be stable across requests.
     *
     * @return statusReference
     */
    public String statusReference() {
        return this.statusReference;
    }

    /**
     * Fluent setter for statusReference.
     * <p>
     * The reference of the status. Unique within this response but not guaranteed to be stable across requests.
     *
     * @param statusReference statusReference
     * @return this
     */
    public JiraWorkflowPreviewStatus statusReference(String statusReference) {
        this.statusReference = statusReference;
        return this;
    }

    /**
     * Gets the value of statusReference.
     * <p>
     * The reference of the status. Unique within this response but not guaranteed to be stable across requests.
     *
     * @return statusReference
     */
    @JsonProperty("statusReference")
    public String getStatusReference() {
        return this.statusReference;
    }

    /**
     * Sets the value of statusReference.
     * <p>
     * The reference of the status. Unique within this response but not guaranteed to be stable across requests.
     *
     * @param statusReference statusReference
     */
    public void setStatusReference(String statusReference) {
        this.statusReference = statusReference;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        JiraWorkflowPreviewStatus that = (JiraWorkflowPreviewStatus) o;
        return
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.rawName, that.rawName) &&
            Objects.equals(this.scope, that.scope) &&
            Objects.equals(this.statusCategory, that.statusCategory) &&
            Objects.equals(this.statusReference, that.statusReference);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.description, 
            this.id, 
            this.name, 
            this.rawName, 
            this.scope, 
            this.statusCategory, 
            this.statusReference
        );
    }

    @Override
    public String toString() {
        return "JiraWorkflowPreviewStatus{"
            + "description=" + description + ", "
            + "id=" + id + ", "
            + "name=" + name + ", "
            + "rawName=" + rawName + ", "
            + "scope=" + scope + ", "
            + "statusCategory=" + statusCategory + ", "
            + "statusReference=" + statusReference
            + "}";
    }
}
