// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * JqlqueryWithUnknownUsers
 * <p>
 * JQL queries that contained users that could not be found
 *
 */
@JsonTypeName("JqlqueryWithUnknownUsers")
@JsonPropertyOrder({
    "convertedQuery",
    "originalQuery"
})
@Generated(value = "io.github.primelib.primecodegen")
public class JqlqueryWithUnknownUsers {

    /**
     * The converted query, with accountIDs instead of user identifiers, or 'unknown' for users that could not be found
     */
    @JsonProperty("convertedQuery")
    protected String convertedQuery;

    /**
     * The original query, for reference
     */
    @JsonProperty("originalQuery")
    protected String originalQuery;

    /**
     * Constructs a validated instance of {@link JqlqueryWithUnknownUsers}.
     *
     * @param spec the specification to process
     */
    public JqlqueryWithUnknownUsers(Consumer<JqlqueryWithUnknownUsers> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected JqlqueryWithUnknownUsers() {
    }
    /**
     * Constructs a validated instance of {@link JqlqueryWithUnknownUsers}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #JqlqueryWithUnknownUsers(Consumer)} instead.
     * @param convertedQuery The converted query, with accountIDs instead of user identifiers, or 'unknown' for users that could not be found
     * @param originalQuery The original query, for reference
     */
    @ApiStatus.Internal
    public JqlqueryWithUnknownUsers(String convertedQuery, String originalQuery) {
        this.convertedQuery = convertedQuery;
        this.originalQuery = originalQuery;
    }


    /**
     * Fluent getter for convertedQuery.
     * <p>
     * The converted query, with accountIDs instead of user identifiers, or 'unknown' for users that could not be found
     *
     * @return convertedQuery
     */
    public String convertedQuery() {
        return this.convertedQuery;
    }

    /**
     * Fluent setter for convertedQuery.
     * <p>
     * The converted query, with accountIDs instead of user identifiers, or 'unknown' for users that could not be found
     *
     * @param convertedQuery convertedQuery
     * @return this
     */
    public JqlqueryWithUnknownUsers convertedQuery(String convertedQuery) {
        this.convertedQuery = convertedQuery;
        return this;
    }

    /**
     * Gets the value of convertedQuery.
     * <p>
     * The converted query, with accountIDs instead of user identifiers, or 'unknown' for users that could not be found
     *
     * @return convertedQuery
     */
    @JsonProperty("convertedQuery")
    public String getConvertedQuery() {
        return this.convertedQuery;
    }

    /**
     * Sets the value of convertedQuery.
     * <p>
     * The converted query, with accountIDs instead of user identifiers, or 'unknown' for users that could not be found
     *
     * @param convertedQuery convertedQuery
     */
    public void setConvertedQuery(String convertedQuery) {
        this.convertedQuery = convertedQuery;
    }
    /**
     * Fluent getter for originalQuery.
     * <p>
     * The original query, for reference
     *
     * @return originalQuery
     */
    public String originalQuery() {
        return this.originalQuery;
    }

    /**
     * Fluent setter for originalQuery.
     * <p>
     * The original query, for reference
     *
     * @param originalQuery originalQuery
     * @return this
     */
    public JqlqueryWithUnknownUsers originalQuery(String originalQuery) {
        this.originalQuery = originalQuery;
        return this;
    }

    /**
     * Gets the value of originalQuery.
     * <p>
     * The original query, for reference
     *
     * @return originalQuery
     */
    @JsonProperty("originalQuery")
    public String getOriginalQuery() {
        return this.originalQuery;
    }

    /**
     * Sets the value of originalQuery.
     * <p>
     * The original query, for reference
     *
     * @param originalQuery originalQuery
     */
    public void setOriginalQuery(String originalQuery) {
        this.originalQuery = originalQuery;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        JqlqueryWithUnknownUsers that = (JqlqueryWithUnknownUsers) o;
        return
            Objects.equals(this.convertedQuery, that.convertedQuery) &&
            Objects.equals(this.originalQuery, that.originalQuery);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.convertedQuery, 
            this.originalQuery
        );
    }

    @Override
    public String toString() {
        return "JqlqueryWithUnknownUsers{"
            + "convertedQuery=" + convertedQuery + ", "
            + "originalQuery=" + originalQuery
            + "}";
    }
}
