// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * JsonNode
 *
 */
@JsonTypeName("JsonNode")
@JsonPropertyOrder({
    "array",
    "bigDecimal",
    "bigInteger",
    "bigIntegerValue",
    "binary",
    "binaryValue",
    "booleanProp",
    "booleanValue",
    "containerNode",
    "decimalValue",
    "doubleProp",
    "doubleValue",
    "elements",
    "fieldNames",
    "fields",
    "floatingPointNumber",
    "intProp",
    "intValue",
    "integralNumber",
    "longProp",
    "longValue",
    "missingNode",
    "nullProp",
    "number",
    "numberType",
    "numberValue",
    "objectProp",
    "pojo",
    "textValue",
    "textual",
    "valueAsBoolean",
    "valueAsDouble",
    "valueAsInt",
    "valueAsLong",
    "valueAsText",
    "valueNode"
})
@Generated(value = "io.github.primelib.primecodegen")
public class JsonNode {

    @JsonProperty("array")
    protected Boolean array;

    @JsonProperty("bigDecimal")
    protected Boolean bigDecimal;

    @JsonProperty("bigInteger")
    protected Boolean bigInteger;

    @JsonProperty("bigIntegerValue")
    protected Long bigIntegerValue;

    @JsonProperty("binary")
    protected Boolean binary;

    @JsonProperty("binaryValue")
    protected List<Byte[]> binaryValue;

    @JsonProperty("boolean")
    protected Boolean booleanProp;

    @JsonProperty("booleanValue")
    protected Boolean booleanValue;

    @JsonProperty("containerNode")
    protected Boolean containerNode;

    @JsonProperty("decimalValue")
    protected Double decimalValue;

    @JsonProperty("double")
    protected Boolean doubleProp;

    @JsonProperty("doubleValue")
    protected Double doubleValue;

    @JsonProperty("elements")
    protected Object elements;

    @JsonProperty("fieldNames")
    protected Object fieldNames;

    @JsonProperty("fields")
    protected Object fields;

    @JsonProperty("floatingPointNumber")
    protected Boolean floatingPointNumber;

    @JsonProperty("int")
    protected Boolean intProp;

    @JsonProperty("intValue")
    protected Integer intValue;

    @JsonProperty("integralNumber")
    protected Boolean integralNumber;

    @JsonProperty("long")
    protected Boolean longProp;

    @JsonProperty("longValue")
    protected Long longValue;

    @JsonProperty("missingNode")
    protected Boolean missingNode;

    @JsonProperty("null")
    protected Boolean nullProp;

    @JsonProperty("number")
    protected Boolean number;

    @JsonProperty("numberType")
    protected String numberType;

    @JsonProperty("numberValue")
    protected Double numberValue;

    @JsonProperty("object")
    protected Boolean objectProp;

    @JsonProperty("pojo")
    protected Boolean pojo;

    @JsonProperty("textValue")
    protected String textValue;

    @JsonProperty("textual")
    protected Boolean textual;

    @JsonProperty("valueAsBoolean")
    protected Boolean valueAsBoolean;

    @JsonProperty("valueAsDouble")
    protected Double valueAsDouble;

    @JsonProperty("valueAsInt")
    protected Integer valueAsInt;

    @JsonProperty("valueAsLong")
    protected Long valueAsLong;

    @JsonProperty("valueAsText")
    protected String valueAsText;

    @JsonProperty("valueNode")
    protected Boolean valueNode;

    /**
     * Constructs a validated instance of {@link JsonNode}.
     *
     * @param spec the specification to process
     */
    public JsonNode(Consumer<JsonNode> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected JsonNode() {
    }
    /**
     * Constructs a validated instance of {@link JsonNode}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #JsonNode(Consumer)} instead.
     * @param array array
     * @param bigDecimal bigDecimal
     * @param bigInteger bigInteger
     * @param bigIntegerValue bigIntegerValue
     * @param binary binary
     * @param binaryValue binaryValue
     * @param booleanProp booleanProp
     * @param booleanValue booleanValue
     * @param containerNode containerNode
     * @param decimalValue decimalValue
     * @param doubleProp doubleProp
     * @param doubleValue doubleValue
     * @param elements elements
     * @param fieldNames fieldNames
     * @param fields fields
     * @param floatingPointNumber floatingPointNumber
     * @param intProp intProp
     * @param intValue intValue
     * @param integralNumber integralNumber
     * @param longProp longProp
     * @param longValue longValue
     * @param missingNode missingNode
     * @param nullProp nullProp
     * @param number number
     * @param numberType numberType
     * @param numberValue numberValue
     * @param objectProp objectProp
     * @param pojo pojo
     * @param textValue textValue
     * @param textual textual
     * @param valueAsBoolean valueAsBoolean
     * @param valueAsDouble valueAsDouble
     * @param valueAsInt valueAsInt
     * @param valueAsLong valueAsLong
     * @param valueAsText valueAsText
     * @param valueNode valueNode
     */
    @ApiStatus.Internal
    public JsonNode(Boolean array, Boolean bigDecimal, Boolean bigInteger, Long bigIntegerValue, Boolean binary, List<Byte[]> binaryValue, Boolean booleanProp, Boolean booleanValue, Boolean containerNode, Double decimalValue, Boolean doubleProp, Double doubleValue, Object elements, Object fieldNames, Object fields, Boolean floatingPointNumber, Boolean intProp, Integer intValue, Boolean integralNumber, Boolean longProp, Long longValue, Boolean missingNode, Boolean nullProp, Boolean number, String numberType, Double numberValue, Boolean objectProp, Boolean pojo, String textValue, Boolean textual, Boolean valueAsBoolean, Double valueAsDouble, Integer valueAsInt, Long valueAsLong, String valueAsText, Boolean valueNode) {
        this.array = array;
        this.bigDecimal = bigDecimal;
        this.bigInteger = bigInteger;
        this.bigIntegerValue = bigIntegerValue;
        this.binary = binary;
        this.binaryValue = binaryValue;
        this.booleanProp = booleanProp;
        this.booleanValue = booleanValue;
        this.containerNode = containerNode;
        this.decimalValue = decimalValue;
        this.doubleProp = doubleProp;
        this.doubleValue = doubleValue;
        this.elements = elements;
        this.fieldNames = fieldNames;
        this.fields = fields;
        this.floatingPointNumber = floatingPointNumber;
        this.intProp = intProp;
        this.intValue = intValue;
        this.integralNumber = integralNumber;
        this.longProp = longProp;
        this.longValue = longValue;
        this.missingNode = missingNode;
        this.nullProp = nullProp;
        this.number = number;
        this.numberType = numberType;
        this.numberValue = numberValue;
        this.objectProp = objectProp;
        this.pojo = pojo;
        this.textValue = textValue;
        this.textual = textual;
        this.valueAsBoolean = valueAsBoolean;
        this.valueAsDouble = valueAsDouble;
        this.valueAsInt = valueAsInt;
        this.valueAsLong = valueAsLong;
        this.valueAsText = valueAsText;
        this.valueNode = valueNode;
    }


    /**
     * Fluent getter for array.
     *
     * @return array
     */
    public Boolean array() {
        return this.array;
    }

    /**
     * Fluent setter for array.
     *
     * @param array array
     * @return this
     */
    public JsonNode array(Boolean array) {
        this.array = array;
        return this;
    }

    /**
     * Gets the value of array.
     *
     * @return array
     */
    @JsonProperty("array")
    public Boolean getArray() {
        return this.array;
    }

    /**
     * Sets the value of array.
     *
     * @param array array
     */
    public void setArray(Boolean array) {
        this.array = array;
    }
    /**
     * Fluent getter for bigDecimal.
     *
     * @return bigDecimal
     */
    public Boolean bigDecimal() {
        return this.bigDecimal;
    }

    /**
     * Fluent setter for bigDecimal.
     *
     * @param bigDecimal bigDecimal
     * @return this
     */
    public JsonNode bigDecimal(Boolean bigDecimal) {
        this.bigDecimal = bigDecimal;
        return this;
    }

    /**
     * Gets the value of bigDecimal.
     *
     * @return bigDecimal
     */
    @JsonProperty("bigDecimal")
    public Boolean getBigDecimal() {
        return this.bigDecimal;
    }

    /**
     * Sets the value of bigDecimal.
     *
     * @param bigDecimal bigDecimal
     */
    public void setBigDecimal(Boolean bigDecimal) {
        this.bigDecimal = bigDecimal;
    }
    /**
     * Fluent getter for bigInteger.
     *
     * @return bigInteger
     */
    public Boolean bigInteger() {
        return this.bigInteger;
    }

    /**
     * Fluent setter for bigInteger.
     *
     * @param bigInteger bigInteger
     * @return this
     */
    public JsonNode bigInteger(Boolean bigInteger) {
        this.bigInteger = bigInteger;
        return this;
    }

    /**
     * Gets the value of bigInteger.
     *
     * @return bigInteger
     */
    @JsonProperty("bigInteger")
    public Boolean getBigInteger() {
        return this.bigInteger;
    }

    /**
     * Sets the value of bigInteger.
     *
     * @param bigInteger bigInteger
     */
    public void setBigInteger(Boolean bigInteger) {
        this.bigInteger = bigInteger;
    }
    /**
     * Fluent getter for bigIntegerValue.
     *
     * @return bigIntegerValue
     */
    public Long bigIntegerValue() {
        return this.bigIntegerValue;
    }

    /**
     * Fluent setter for bigIntegerValue.
     *
     * @param bigIntegerValue bigIntegerValue
     * @return this
     */
    public JsonNode bigIntegerValue(Long bigIntegerValue) {
        this.bigIntegerValue = bigIntegerValue;
        return this;
    }

    /**
     * Gets the value of bigIntegerValue.
     *
     * @return bigIntegerValue
     */
    @JsonProperty("bigIntegerValue")
    public Long getBigIntegerValue() {
        return this.bigIntegerValue;
    }

    /**
     * Sets the value of bigIntegerValue.
     *
     * @param bigIntegerValue bigIntegerValue
     */
    public void setBigIntegerValue(Long bigIntegerValue) {
        this.bigIntegerValue = bigIntegerValue;
    }
    /**
     * Fluent getter for binary.
     *
     * @return binary
     */
    public Boolean binary() {
        return this.binary;
    }

    /**
     * Fluent setter for binary.
     *
     * @param binary binary
     * @return this
     */
    public JsonNode binary(Boolean binary) {
        this.binary = binary;
        return this;
    }

    /**
     * Gets the value of binary.
     *
     * @return binary
     */
    @JsonProperty("binary")
    public Boolean getBinary() {
        return this.binary;
    }

    /**
     * Sets the value of binary.
     *
     * @param binary binary
     */
    public void setBinary(Boolean binary) {
        this.binary = binary;
    }
    /**
     * Fluent getter for binaryValue.
     *
     * @return binaryValue
     */
    public List<Byte[]> binaryValue() {
        return this.binaryValue;
    }

    /**
     * Fluent setter for binaryValue.
     *
     * @param binaryValue binaryValue
     * @return this
     */
    public JsonNode binaryValue(List<Byte[]> binaryValue) {
        this.binaryValue = binaryValue;
        return this;
    }

    /**
     * Gets the value of binaryValue.
     *
     * @return binaryValue
     */
    @JsonProperty("binaryValue")
    public List<Byte[]> getBinaryValue() {
        return this.binaryValue;
    }

    /**
     * Sets the value of binaryValue.
     *
     * @param binaryValue binaryValue
     */
    public void setBinaryValue(List<Byte[]> binaryValue) {
        this.binaryValue = binaryValue;
    }
    /**
     * Fluent getter for booleanProp.
     *
     * @return booleanProp
     */
    public Boolean booleanProp() {
        return this.booleanProp;
    }

    /**
     * Fluent setter for booleanProp.
     *
     * @param booleanProp booleanProp
     * @return this
     */
    public JsonNode booleanProp(Boolean booleanProp) {
        this.booleanProp = booleanProp;
        return this;
    }

    /**
     * Gets the value of booleanProp.
     *
     * @return booleanProp
     */
    @JsonProperty("boolean")
    public Boolean getBooleanProp() {
        return this.booleanProp;
    }

    /**
     * Sets the value of booleanProp.
     *
     * @param booleanProp booleanProp
     */
    public void setBooleanProp(Boolean booleanProp) {
        this.booleanProp = booleanProp;
    }
    /**
     * Fluent getter for booleanValue.
     *
     * @return booleanValue
     */
    public Boolean booleanValue() {
        return this.booleanValue;
    }

    /**
     * Fluent setter for booleanValue.
     *
     * @param booleanValue booleanValue
     * @return this
     */
    public JsonNode booleanValue(Boolean booleanValue) {
        this.booleanValue = booleanValue;
        return this;
    }

    /**
     * Gets the value of booleanValue.
     *
     * @return booleanValue
     */
    @JsonProperty("booleanValue")
    public Boolean getBooleanValue() {
        return this.booleanValue;
    }

    /**
     * Sets the value of booleanValue.
     *
     * @param booleanValue booleanValue
     */
    public void setBooleanValue(Boolean booleanValue) {
        this.booleanValue = booleanValue;
    }
    /**
     * Fluent getter for containerNode.
     *
     * @return containerNode
     */
    public Boolean containerNode() {
        return this.containerNode;
    }

    /**
     * Fluent setter for containerNode.
     *
     * @param containerNode containerNode
     * @return this
     */
    public JsonNode containerNode(Boolean containerNode) {
        this.containerNode = containerNode;
        return this;
    }

    /**
     * Gets the value of containerNode.
     *
     * @return containerNode
     */
    @JsonProperty("containerNode")
    public Boolean getContainerNode() {
        return this.containerNode;
    }

    /**
     * Sets the value of containerNode.
     *
     * @param containerNode containerNode
     */
    public void setContainerNode(Boolean containerNode) {
        this.containerNode = containerNode;
    }
    /**
     * Fluent getter for decimalValue.
     *
     * @return decimalValue
     */
    public Double decimalValue() {
        return this.decimalValue;
    }

    /**
     * Fluent setter for decimalValue.
     *
     * @param decimalValue decimalValue
     * @return this
     */
    public JsonNode decimalValue(Double decimalValue) {
        this.decimalValue = decimalValue;
        return this;
    }

    /**
     * Gets the value of decimalValue.
     *
     * @return decimalValue
     */
    @JsonProperty("decimalValue")
    public Double getDecimalValue() {
        return this.decimalValue;
    }

    /**
     * Sets the value of decimalValue.
     *
     * @param decimalValue decimalValue
     */
    public void setDecimalValue(Double decimalValue) {
        this.decimalValue = decimalValue;
    }
    /**
     * Fluent getter for doubleProp.
     *
     * @return doubleProp
     */
    public Boolean doubleProp() {
        return this.doubleProp;
    }

    /**
     * Fluent setter for doubleProp.
     *
     * @param doubleProp doubleProp
     * @return this
     */
    public JsonNode doubleProp(Boolean doubleProp) {
        this.doubleProp = doubleProp;
        return this;
    }

    /**
     * Gets the value of doubleProp.
     *
     * @return doubleProp
     */
    @JsonProperty("double")
    public Boolean getDoubleProp() {
        return this.doubleProp;
    }

    /**
     * Sets the value of doubleProp.
     *
     * @param doubleProp doubleProp
     */
    public void setDoubleProp(Boolean doubleProp) {
        this.doubleProp = doubleProp;
    }
    /**
     * Fluent getter for doubleValue.
     *
     * @return doubleValue
     */
    public Double doubleValue() {
        return this.doubleValue;
    }

    /**
     * Fluent setter for doubleValue.
     *
     * @param doubleValue doubleValue
     * @return this
     */
    public JsonNode doubleValue(Double doubleValue) {
        this.doubleValue = doubleValue;
        return this;
    }

    /**
     * Gets the value of doubleValue.
     *
     * @return doubleValue
     */
    @JsonProperty("doubleValue")
    public Double getDoubleValue() {
        return this.doubleValue;
    }

    /**
     * Sets the value of doubleValue.
     *
     * @param doubleValue doubleValue
     */
    public void setDoubleValue(Double doubleValue) {
        this.doubleValue = doubleValue;
    }
    /**
     * Fluent getter for elements.
     *
     * @return elements
     */
    public Object elements() {
        return this.elements;
    }

    /**
     * Fluent setter for elements.
     *
     * @param elements elements
     * @return this
     */
    public JsonNode elements(Object elements) {
        this.elements = elements;
        return this;
    }

    /**
     * Gets the value of elements.
     *
     * @return elements
     */
    @JsonProperty("elements")
    public Object getElements() {
        return this.elements;
    }

    /**
     * Sets the value of elements.
     *
     * @param elements elements
     */
    public void setElements(Object elements) {
        this.elements = elements;
    }
    /**
     * Fluent getter for fieldNames.
     *
     * @return fieldNames
     */
    public Object fieldNames() {
        return this.fieldNames;
    }

    /**
     * Fluent setter for fieldNames.
     *
     * @param fieldNames fieldNames
     * @return this
     */
    public JsonNode fieldNames(Object fieldNames) {
        this.fieldNames = fieldNames;
        return this;
    }

    /**
     * Gets the value of fieldNames.
     *
     * @return fieldNames
     */
    @JsonProperty("fieldNames")
    public Object getFieldNames() {
        return this.fieldNames;
    }

    /**
     * Sets the value of fieldNames.
     *
     * @param fieldNames fieldNames
     */
    public void setFieldNames(Object fieldNames) {
        this.fieldNames = fieldNames;
    }
    /**
     * Fluent getter for fields.
     *
     * @return fields
     */
    public Object fields() {
        return this.fields;
    }

    /**
     * Fluent setter for fields.
     *
     * @param fields fields
     * @return this
     */
    public JsonNode fields(Object fields) {
        this.fields = fields;
        return this;
    }

    /**
     * Gets the value of fields.
     *
     * @return fields
     */
    @JsonProperty("fields")
    public Object getFields() {
        return this.fields;
    }

    /**
     * Sets the value of fields.
     *
     * @param fields fields
     */
    public void setFields(Object fields) {
        this.fields = fields;
    }
    /**
     * Fluent getter for floatingPointNumber.
     *
     * @return floatingPointNumber
     */
    public Boolean floatingPointNumber() {
        return this.floatingPointNumber;
    }

    /**
     * Fluent setter for floatingPointNumber.
     *
     * @param floatingPointNumber floatingPointNumber
     * @return this
     */
    public JsonNode floatingPointNumber(Boolean floatingPointNumber) {
        this.floatingPointNumber = floatingPointNumber;
        return this;
    }

    /**
     * Gets the value of floatingPointNumber.
     *
     * @return floatingPointNumber
     */
    @JsonProperty("floatingPointNumber")
    public Boolean getFloatingPointNumber() {
        return this.floatingPointNumber;
    }

    /**
     * Sets the value of floatingPointNumber.
     *
     * @param floatingPointNumber floatingPointNumber
     */
    public void setFloatingPointNumber(Boolean floatingPointNumber) {
        this.floatingPointNumber = floatingPointNumber;
    }
    /**
     * Fluent getter for intProp.
     *
     * @return intProp
     */
    public Boolean intProp() {
        return this.intProp;
    }

    /**
     * Fluent setter for intProp.
     *
     * @param intProp intProp
     * @return this
     */
    public JsonNode intProp(Boolean intProp) {
        this.intProp = intProp;
        return this;
    }

    /**
     * Gets the value of intProp.
     *
     * @return intProp
     */
    @JsonProperty("int")
    public Boolean getIntProp() {
        return this.intProp;
    }

    /**
     * Sets the value of intProp.
     *
     * @param intProp intProp
     */
    public void setIntProp(Boolean intProp) {
        this.intProp = intProp;
    }
    /**
     * Fluent getter for intValue.
     *
     * @return intValue
     */
    public Integer intValue() {
        return this.intValue;
    }

    /**
     * Fluent setter for intValue.
     *
     * @param intValue intValue
     * @return this
     */
    public JsonNode intValue(Integer intValue) {
        this.intValue = intValue;
        return this;
    }

    /**
     * Gets the value of intValue.
     *
     * @return intValue
     */
    @JsonProperty("intValue")
    public Integer getIntValue() {
        return this.intValue;
    }

    /**
     * Sets the value of intValue.
     *
     * @param intValue intValue
     */
    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }
    /**
     * Fluent getter for integralNumber.
     *
     * @return integralNumber
     */
    public Boolean integralNumber() {
        return this.integralNumber;
    }

    /**
     * Fluent setter for integralNumber.
     *
     * @param integralNumber integralNumber
     * @return this
     */
    public JsonNode integralNumber(Boolean integralNumber) {
        this.integralNumber = integralNumber;
        return this;
    }

    /**
     * Gets the value of integralNumber.
     *
     * @return integralNumber
     */
    @JsonProperty("integralNumber")
    public Boolean getIntegralNumber() {
        return this.integralNumber;
    }

    /**
     * Sets the value of integralNumber.
     *
     * @param integralNumber integralNumber
     */
    public void setIntegralNumber(Boolean integralNumber) {
        this.integralNumber = integralNumber;
    }
    /**
     * Fluent getter for longProp.
     *
     * @return longProp
     */
    public Boolean longProp() {
        return this.longProp;
    }

    /**
     * Fluent setter for longProp.
     *
     * @param longProp longProp
     * @return this
     */
    public JsonNode longProp(Boolean longProp) {
        this.longProp = longProp;
        return this;
    }

    /**
     * Gets the value of longProp.
     *
     * @return longProp
     */
    @JsonProperty("long")
    public Boolean getLongProp() {
        return this.longProp;
    }

    /**
     * Sets the value of longProp.
     *
     * @param longProp longProp
     */
    public void setLongProp(Boolean longProp) {
        this.longProp = longProp;
    }
    /**
     * Fluent getter for longValue.
     *
     * @return longValue
     */
    public Long longValue() {
        return this.longValue;
    }

    /**
     * Fluent setter for longValue.
     *
     * @param longValue longValue
     * @return this
     */
    public JsonNode longValue(Long longValue) {
        this.longValue = longValue;
        return this;
    }

    /**
     * Gets the value of longValue.
     *
     * @return longValue
     */
    @JsonProperty("longValue")
    public Long getLongValue() {
        return this.longValue;
    }

    /**
     * Sets the value of longValue.
     *
     * @param longValue longValue
     */
    public void setLongValue(Long longValue) {
        this.longValue = longValue;
    }
    /**
     * Fluent getter for missingNode.
     *
     * @return missingNode
     */
    public Boolean missingNode() {
        return this.missingNode;
    }

    /**
     * Fluent setter for missingNode.
     *
     * @param missingNode missingNode
     * @return this
     */
    public JsonNode missingNode(Boolean missingNode) {
        this.missingNode = missingNode;
        return this;
    }

    /**
     * Gets the value of missingNode.
     *
     * @return missingNode
     */
    @JsonProperty("missingNode")
    public Boolean getMissingNode() {
        return this.missingNode;
    }

    /**
     * Sets the value of missingNode.
     *
     * @param missingNode missingNode
     */
    public void setMissingNode(Boolean missingNode) {
        this.missingNode = missingNode;
    }
    /**
     * Fluent getter for nullProp.
     *
     * @return nullProp
     */
    public Boolean nullProp() {
        return this.nullProp;
    }

    /**
     * Fluent setter for nullProp.
     *
     * @param nullProp nullProp
     * @return this
     */
    public JsonNode nullProp(Boolean nullProp) {
        this.nullProp = nullProp;
        return this;
    }

    /**
     * Gets the value of nullProp.
     *
     * @return nullProp
     */
    @JsonProperty("null")
    public Boolean getNullProp() {
        return this.nullProp;
    }

    /**
     * Sets the value of nullProp.
     *
     * @param nullProp nullProp
     */
    public void setNullProp(Boolean nullProp) {
        this.nullProp = nullProp;
    }
    /**
     * Fluent getter for number.
     *
     * @return number
     */
    public Boolean number() {
        return this.number;
    }

    /**
     * Fluent setter for number.
     *
     * @param number number
     * @return this
     */
    public JsonNode number(Boolean number) {
        this.number = number;
        return this;
    }

    /**
     * Gets the value of number.
     *
     * @return number
     */
    @JsonProperty("number")
    public Boolean getNumber() {
        return this.number;
    }

    /**
     * Sets the value of number.
     *
     * @param number number
     */
    public void setNumber(Boolean number) {
        this.number = number;
    }
    /**
     * Fluent getter for numberType.
     *
     * @return numberType
     */
    public String numberType() {
        return this.numberType;
    }

    /**
     * Fluent setter for numberType.
     *
     * @param numberType numberType
     * @return this
     */
    public JsonNode numberType(String numberType) {
        this.numberType = numberType;
        return this;
    }

    /**
     * Gets the value of numberType.
     *
     * @return numberType
     */
    @JsonProperty("numberType")
    public String getNumberType() {
        return this.numberType;
    }

    /**
     * Sets the value of numberType.
     *
     * @param numberType numberType
     */
    public void setNumberType(String numberType) {
        this.numberType = numberType;
    }
    /**
     * Fluent getter for numberValue.
     *
     * @return numberValue
     */
    public Double numberValue() {
        return this.numberValue;
    }

    /**
     * Fluent setter for numberValue.
     *
     * @param numberValue numberValue
     * @return this
     */
    public JsonNode numberValue(Double numberValue) {
        this.numberValue = numberValue;
        return this;
    }

    /**
     * Gets the value of numberValue.
     *
     * @return numberValue
     */
    @JsonProperty("numberValue")
    public Double getNumberValue() {
        return this.numberValue;
    }

    /**
     * Sets the value of numberValue.
     *
     * @param numberValue numberValue
     */
    public void setNumberValue(Double numberValue) {
        this.numberValue = numberValue;
    }
    /**
     * Fluent getter for objectProp.
     *
     * @return objectProp
     */
    public Boolean objectProp() {
        return this.objectProp;
    }

    /**
     * Fluent setter for objectProp.
     *
     * @param objectProp objectProp
     * @return this
     */
    public JsonNode objectProp(Boolean objectProp) {
        this.objectProp = objectProp;
        return this;
    }

    /**
     * Gets the value of objectProp.
     *
     * @return objectProp
     */
    @JsonProperty("object")
    public Boolean getObjectProp() {
        return this.objectProp;
    }

    /**
     * Sets the value of objectProp.
     *
     * @param objectProp objectProp
     */
    public void setObjectProp(Boolean objectProp) {
        this.objectProp = objectProp;
    }
    /**
     * Fluent getter for pojo.
     *
     * @return pojo
     */
    public Boolean pojo() {
        return this.pojo;
    }

    /**
     * Fluent setter for pojo.
     *
     * @param pojo pojo
     * @return this
     */
    public JsonNode pojo(Boolean pojo) {
        this.pojo = pojo;
        return this;
    }

    /**
     * Gets the value of pojo.
     *
     * @return pojo
     */
    @JsonProperty("pojo")
    public Boolean getPojo() {
        return this.pojo;
    }

    /**
     * Sets the value of pojo.
     *
     * @param pojo pojo
     */
    public void setPojo(Boolean pojo) {
        this.pojo = pojo;
    }
    /**
     * Fluent getter for textValue.
     *
     * @return textValue
     */
    public String textValue() {
        return this.textValue;
    }

    /**
     * Fluent setter for textValue.
     *
     * @param textValue textValue
     * @return this
     */
    public JsonNode textValue(String textValue) {
        this.textValue = textValue;
        return this;
    }

    /**
     * Gets the value of textValue.
     *
     * @return textValue
     */
    @JsonProperty("textValue")
    public String getTextValue() {
        return this.textValue;
    }

    /**
     * Sets the value of textValue.
     *
     * @param textValue textValue
     */
    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }
    /**
     * Fluent getter for textual.
     *
     * @return textual
     */
    public Boolean textual() {
        return this.textual;
    }

    /**
     * Fluent setter for textual.
     *
     * @param textual textual
     * @return this
     */
    public JsonNode textual(Boolean textual) {
        this.textual = textual;
        return this;
    }

    /**
     * Gets the value of textual.
     *
     * @return textual
     */
    @JsonProperty("textual")
    public Boolean getTextual() {
        return this.textual;
    }

    /**
     * Sets the value of textual.
     *
     * @param textual textual
     */
    public void setTextual(Boolean textual) {
        this.textual = textual;
    }
    /**
     * Fluent getter for valueAsBoolean.
     *
     * @return valueAsBoolean
     */
    public Boolean valueAsBoolean() {
        return this.valueAsBoolean;
    }

    /**
     * Fluent setter for valueAsBoolean.
     *
     * @param valueAsBoolean valueAsBoolean
     * @return this
     */
    public JsonNode valueAsBoolean(Boolean valueAsBoolean) {
        this.valueAsBoolean = valueAsBoolean;
        return this;
    }

    /**
     * Gets the value of valueAsBoolean.
     *
     * @return valueAsBoolean
     */
    @JsonProperty("valueAsBoolean")
    public Boolean getValueAsBoolean() {
        return this.valueAsBoolean;
    }

    /**
     * Sets the value of valueAsBoolean.
     *
     * @param valueAsBoolean valueAsBoolean
     */
    public void setValueAsBoolean(Boolean valueAsBoolean) {
        this.valueAsBoolean = valueAsBoolean;
    }
    /**
     * Fluent getter for valueAsDouble.
     *
     * @return valueAsDouble
     */
    public Double valueAsDouble() {
        return this.valueAsDouble;
    }

    /**
     * Fluent setter for valueAsDouble.
     *
     * @param valueAsDouble valueAsDouble
     * @return this
     */
    public JsonNode valueAsDouble(Double valueAsDouble) {
        this.valueAsDouble = valueAsDouble;
        return this;
    }

    /**
     * Gets the value of valueAsDouble.
     *
     * @return valueAsDouble
     */
    @JsonProperty("valueAsDouble")
    public Double getValueAsDouble() {
        return this.valueAsDouble;
    }

    /**
     * Sets the value of valueAsDouble.
     *
     * @param valueAsDouble valueAsDouble
     */
    public void setValueAsDouble(Double valueAsDouble) {
        this.valueAsDouble = valueAsDouble;
    }
    /**
     * Fluent getter for valueAsInt.
     *
     * @return valueAsInt
     */
    public Integer valueAsInt() {
        return this.valueAsInt;
    }

    /**
     * Fluent setter for valueAsInt.
     *
     * @param valueAsInt valueAsInt
     * @return this
     */
    public JsonNode valueAsInt(Integer valueAsInt) {
        this.valueAsInt = valueAsInt;
        return this;
    }

    /**
     * Gets the value of valueAsInt.
     *
     * @return valueAsInt
     */
    @JsonProperty("valueAsInt")
    public Integer getValueAsInt() {
        return this.valueAsInt;
    }

    /**
     * Sets the value of valueAsInt.
     *
     * @param valueAsInt valueAsInt
     */
    public void setValueAsInt(Integer valueAsInt) {
        this.valueAsInt = valueAsInt;
    }
    /**
     * Fluent getter for valueAsLong.
     *
     * @return valueAsLong
     */
    public Long valueAsLong() {
        return this.valueAsLong;
    }

    /**
     * Fluent setter for valueAsLong.
     *
     * @param valueAsLong valueAsLong
     * @return this
     */
    public JsonNode valueAsLong(Long valueAsLong) {
        this.valueAsLong = valueAsLong;
        return this;
    }

    /**
     * Gets the value of valueAsLong.
     *
     * @return valueAsLong
     */
    @JsonProperty("valueAsLong")
    public Long getValueAsLong() {
        return this.valueAsLong;
    }

    /**
     * Sets the value of valueAsLong.
     *
     * @param valueAsLong valueAsLong
     */
    public void setValueAsLong(Long valueAsLong) {
        this.valueAsLong = valueAsLong;
    }
    /**
     * Fluent getter for valueAsText.
     *
     * @return valueAsText
     */
    public String valueAsText() {
        return this.valueAsText;
    }

    /**
     * Fluent setter for valueAsText.
     *
     * @param valueAsText valueAsText
     * @return this
     */
    public JsonNode valueAsText(String valueAsText) {
        this.valueAsText = valueAsText;
        return this;
    }

    /**
     * Gets the value of valueAsText.
     *
     * @return valueAsText
     */
    @JsonProperty("valueAsText")
    public String getValueAsText() {
        return this.valueAsText;
    }

    /**
     * Sets the value of valueAsText.
     *
     * @param valueAsText valueAsText
     */
    public void setValueAsText(String valueAsText) {
        this.valueAsText = valueAsText;
    }
    /**
     * Fluent getter for valueNode.
     *
     * @return valueNode
     */
    public Boolean valueNode() {
        return this.valueNode;
    }

    /**
     * Fluent setter for valueNode.
     *
     * @param valueNode valueNode
     * @return this
     */
    public JsonNode valueNode(Boolean valueNode) {
        this.valueNode = valueNode;
        return this;
    }

    /**
     * Gets the value of valueNode.
     *
     * @return valueNode
     */
    @JsonProperty("valueNode")
    public Boolean getValueNode() {
        return this.valueNode;
    }

    /**
     * Sets the value of valueNode.
     *
     * @param valueNode valueNode
     */
    public void setValueNode(Boolean valueNode) {
        this.valueNode = valueNode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        JsonNode that = (JsonNode) o;
        return
            Objects.equals(this.array, that.array) &&
            Objects.equals(this.bigDecimal, that.bigDecimal) &&
            Objects.equals(this.bigInteger, that.bigInteger) &&
            Objects.equals(this.bigIntegerValue, that.bigIntegerValue) &&
            Objects.equals(this.binary, that.binary) &&
            Objects.equals(this.binaryValue, that.binaryValue) &&
            Objects.equals(this.booleanProp, that.booleanProp) &&
            Objects.equals(this.booleanValue, that.booleanValue) &&
            Objects.equals(this.containerNode, that.containerNode) &&
            Objects.equals(this.decimalValue, that.decimalValue) &&
            Objects.equals(this.doubleProp, that.doubleProp) &&
            Objects.equals(this.doubleValue, that.doubleValue) &&
            Objects.equals(this.elements, that.elements) &&
            Objects.equals(this.fieldNames, that.fieldNames) &&
            Objects.equals(this.fields, that.fields) &&
            Objects.equals(this.floatingPointNumber, that.floatingPointNumber) &&
            Objects.equals(this.intProp, that.intProp) &&
            Objects.equals(this.intValue, that.intValue) &&
            Objects.equals(this.integralNumber, that.integralNumber) &&
            Objects.equals(this.longProp, that.longProp) &&
            Objects.equals(this.longValue, that.longValue) &&
            Objects.equals(this.missingNode, that.missingNode) &&
            Objects.equals(this.nullProp, that.nullProp) &&
            Objects.equals(this.number, that.number) &&
            Objects.equals(this.numberType, that.numberType) &&
            Objects.equals(this.numberValue, that.numberValue) &&
            Objects.equals(this.objectProp, that.objectProp) &&
            Objects.equals(this.pojo, that.pojo) &&
            Objects.equals(this.textValue, that.textValue) &&
            Objects.equals(this.textual, that.textual) &&
            Objects.equals(this.valueAsBoolean, that.valueAsBoolean) &&
            Objects.equals(this.valueAsDouble, that.valueAsDouble) &&
            Objects.equals(this.valueAsInt, that.valueAsInt) &&
            Objects.equals(this.valueAsLong, that.valueAsLong) &&
            Objects.equals(this.valueAsText, that.valueAsText) &&
            Objects.equals(this.valueNode, that.valueNode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.array, 
            this.bigDecimal, 
            this.bigInteger, 
            this.bigIntegerValue, 
            this.binary, 
            this.binaryValue, 
            this.booleanProp, 
            this.booleanValue, 
            this.containerNode, 
            this.decimalValue, 
            this.doubleProp, 
            this.doubleValue, 
            this.elements, 
            this.fieldNames, 
            this.fields, 
            this.floatingPointNumber, 
            this.intProp, 
            this.intValue, 
            this.integralNumber, 
            this.longProp, 
            this.longValue, 
            this.missingNode, 
            this.nullProp, 
            this.number, 
            this.numberType, 
            this.numberValue, 
            this.objectProp, 
            this.pojo, 
            this.textValue, 
            this.textual, 
            this.valueAsBoolean, 
            this.valueAsDouble, 
            this.valueAsInt, 
            this.valueAsLong, 
            this.valueAsText, 
            this.valueNode
        );
    }

    @Override
    public String toString() {
        return "JsonNode{"
            + "array=" + array + ", "
            + "bigDecimal=" + bigDecimal + ", "
            + "bigInteger=" + bigInteger + ", "
            + "bigIntegerValue=" + bigIntegerValue + ", "
            + "binary=" + binary + ", "
            + "binaryValue=" + binaryValue + ", "
            + "booleanProp=" + booleanProp + ", "
            + "booleanValue=" + booleanValue + ", "
            + "containerNode=" + containerNode + ", "
            + "decimalValue=" + decimalValue + ", "
            + "doubleProp=" + doubleProp + ", "
            + "doubleValue=" + doubleValue + ", "
            + "elements=" + elements + ", "
            + "fieldNames=" + fieldNames + ", "
            + "fields=" + fields + ", "
            + "floatingPointNumber=" + floatingPointNumber + ", "
            + "intProp=" + intProp + ", "
            + "intValue=" + intValue + ", "
            + "integralNumber=" + integralNumber + ", "
            + "longProp=" + longProp + ", "
            + "longValue=" + longValue + ", "
            + "missingNode=" + missingNode + ", "
            + "nullProp=" + nullProp + ", "
            + "number=" + number + ", "
            + "numberType=" + numberType + ", "
            + "numberValue=" + numberValue + ", "
            + "objectProp=" + objectProp + ", "
            + "pojo=" + pojo + ", "
            + "textValue=" + textValue + ", "
            + "textual=" + textual + ", "
            + "valueAsBoolean=" + valueAsBoolean + ", "
            + "valueAsDouble=" + valueAsDouble + ", "
            + "valueAsInt=" + valueAsInt + ", "
            + "valueAsLong=" + valueAsLong + ", "
            + "valueAsText=" + valueAsText + ", "
            + "valueNode=" + valueNode
            + "}";
    }
}
