// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OldToNewSecurityLevelMappingsBean
 *
 */
@JsonTypeName("OldToNewSecurityLevelMappingsBean")
@JsonPropertyOrder({
    "newLevelId",
    "oldLevelId"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OldToNewSecurityLevelMappingsBean {

    /**
     * The new issue security level ID. Providing null will clear the assigned old level from issues.
     */
    @JsonProperty("newLevelId")
    protected String newLevelId;

    /**
     * The old issue security level ID. Providing null will remap all issues without any assigned levels.
     */
    @JsonProperty("oldLevelId")
    protected String oldLevelId;

    /**
     * Constructs a validated instance of {@link OldToNewSecurityLevelMappingsBean}.
     *
     * @param spec the specification to process
     */
    public OldToNewSecurityLevelMappingsBean(Consumer<OldToNewSecurityLevelMappingsBean> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OldToNewSecurityLevelMappingsBean() {
    }
    /**
     * Constructs a validated instance of {@link OldToNewSecurityLevelMappingsBean}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OldToNewSecurityLevelMappingsBean(Consumer)} instead.
     * @param newLevelId The new issue security level ID. Providing null will clear the assigned old level from issues.
     * @param oldLevelId The old issue security level ID. Providing null will remap all issues without any assigned levels.
     */
    @ApiStatus.Internal
    public OldToNewSecurityLevelMappingsBean(String newLevelId, String oldLevelId) {
        this.newLevelId = newLevelId;
        this.oldLevelId = oldLevelId;
    }


    /**
     * Fluent getter for newLevelId.
     * <p>
     * The new issue security level ID. Providing null will clear the assigned old level from issues.
     *
     * @return newLevelId
     */
    public String newLevelId() {
        return this.newLevelId;
    }

    /**
     * Fluent setter for newLevelId.
     * <p>
     * The new issue security level ID. Providing null will clear the assigned old level from issues.
     *
     * @param newLevelId newLevelId
     * @return this
     */
    public OldToNewSecurityLevelMappingsBean newLevelId(String newLevelId) {
        this.newLevelId = newLevelId;
        return this;
    }

    /**
     * Gets the value of newLevelId.
     * <p>
     * The new issue security level ID. Providing null will clear the assigned old level from issues.
     *
     * @return newLevelId
     */
    @JsonProperty("newLevelId")
    public String getNewLevelId() {
        return this.newLevelId;
    }

    /**
     * Sets the value of newLevelId.
     * <p>
     * The new issue security level ID. Providing null will clear the assigned old level from issues.
     *
     * @param newLevelId newLevelId
     */
    public void setNewLevelId(String newLevelId) {
        this.newLevelId = newLevelId;
    }
    /**
     * Fluent getter for oldLevelId.
     * <p>
     * The old issue security level ID. Providing null will remap all issues without any assigned levels.
     *
     * @return oldLevelId
     */
    public String oldLevelId() {
        return this.oldLevelId;
    }

    /**
     * Fluent setter for oldLevelId.
     * <p>
     * The old issue security level ID. Providing null will remap all issues without any assigned levels.
     *
     * @param oldLevelId oldLevelId
     * @return this
     */
    public OldToNewSecurityLevelMappingsBean oldLevelId(String oldLevelId) {
        this.oldLevelId = oldLevelId;
        return this;
    }

    /**
     * Gets the value of oldLevelId.
     * <p>
     * The old issue security level ID. Providing null will remap all issues without any assigned levels.
     *
     * @return oldLevelId
     */
    @JsonProperty("oldLevelId")
    public String getOldLevelId() {
        return this.oldLevelId;
    }

    /**
     * Sets the value of oldLevelId.
     * <p>
     * The old issue security level ID. Providing null will remap all issues without any assigned levels.
     *
     * @param oldLevelId oldLevelId
     */
    public void setOldLevelId(String oldLevelId) {
        this.oldLevelId = oldLevelId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OldToNewSecurityLevelMappingsBean that = (OldToNewSecurityLevelMappingsBean) o;
        return
            Objects.equals(this.newLevelId, that.newLevelId) &&
            Objects.equals(this.oldLevelId, that.oldLevelId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.newLevelId, 
            this.oldLevelId
        );
    }

    @Override
    public String toString() {
        return "OldToNewSecurityLevelMappingsBean{"
            + "newLevelId=" + newLevelId + ", "
            + "oldLevelId=" + oldLevelId
            + "}";
    }
}
