// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * PermissionGrants
 * <p>
 * List of permission grants.
 *
 */
@JsonTypeName("PermissionGrants")
@JsonPropertyOrder({
    "expand",
    "permissions"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PermissionGrants {

    /**
     * Expand options that include additional permission grant details in the response.
     */
    @JsonProperty("expand")
    protected String expand;

    /**
     * Permission grants list.
     */
    @JsonProperty("permissions")
    protected List<Map<String, Object>> permissions;

    /**
     * Constructs a validated instance of {@link PermissionGrants}.
     *
     * @param spec the specification to process
     */
    public PermissionGrants(Consumer<PermissionGrants> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected PermissionGrants() {
    }
    /**
     * Constructs a validated instance of {@link PermissionGrants}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PermissionGrants(Consumer)} instead.
     * @param expand Expand options that include additional permission grant details in the response.
     * @param permissions Permission grants list.
     */
    @ApiStatus.Internal
    public PermissionGrants(String expand, List<Map<String, Object>> permissions) {
        this.expand = expand;
        this.permissions = permissions;
    }


    /**
     * Fluent getter for expand.
     * <p>
     * Expand options that include additional permission grant details in the response.
     *
     * @return expand
     */
    public String expand() {
        return this.expand;
    }

    /**
     * Fluent setter for expand.
     * <p>
     * Expand options that include additional permission grant details in the response.
     *
     * @param expand expand
     * @return this
     */
    public PermissionGrants expand(String expand) {
        this.expand = expand;
        return this;
    }

    /**
     * Gets the value of expand.
     * <p>
     * Expand options that include additional permission grant details in the response.
     *
     * @return expand
     */
    @JsonProperty("expand")
    public String getExpand() {
        return this.expand;
    }

    /**
     * Sets the value of expand.
     * <p>
     * Expand options that include additional permission grant details in the response.
     *
     * @param expand expand
     */
    public void setExpand(String expand) {
        this.expand = expand;
    }
    /**
     * Fluent getter for permissions.
     * <p>
     * Permission grants list.
     *
     * @return permissions
     */
    public List<Map<String, Object>> permissions() {
        return this.permissions;
    }

    /**
     * Fluent setter for permissions.
     * <p>
     * Permission grants list.
     *
     * @param permissions permissions
     * @return this
     */
    public PermissionGrants permissions(List<Map<String, Object>> permissions) {
        this.permissions = permissions;
        return this;
    }

    /**
     * Gets the value of permissions.
     * <p>
     * Permission grants list.
     *
     * @return permissions
     */
    @JsonProperty("permissions")
    public List<Map<String, Object>> getPermissions() {
        return this.permissions;
    }

    /**
     * Sets the value of permissions.
     * <p>
     * Permission grants list.
     *
     * @param permissions permissions
     */
    public void setPermissions(List<Map<String, Object>> permissions) {
        this.permissions = permissions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PermissionGrants that = (PermissionGrants) o;
        return
            Objects.equals(this.expand, that.expand) &&
            Objects.equals(this.permissions, that.permissions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.expand, 
            this.permissions
        );
    }

    @Override
    public String toString() {
        return "PermissionGrants{"
            + "expand=" + expand + ", "
            + "permissions=" + permissions
            + "}";
    }
}
