// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * PermissionSchemes
 * <p>
 * List of all permission schemes.
 *
 */
@JsonTypeName("PermissionSchemes")
@JsonPropertyOrder({
    "permissionSchemes"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PermissionSchemes {

    /**
     * Permission schemes list.
     */
    @JsonProperty("permissionSchemes")
    protected List<Map<String, Object>> permissionSchemes;

    /**
     * Constructs a validated instance of {@link PermissionSchemes}.
     *
     * @param spec the specification to process
     */
    public PermissionSchemes(Consumer<PermissionSchemes> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected PermissionSchemes() {
    }
    /**
     * Constructs a validated instance of {@link PermissionSchemes}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PermissionSchemes(Consumer)} instead.
     * @param permissionSchemes Permission schemes list.
     */
    @ApiStatus.Internal
    public PermissionSchemes(List<Map<String, Object>> permissionSchemes) {
        this.permissionSchemes = permissionSchemes;
    }


    /**
     * Fluent getter for permissionSchemes.
     * <p>
     * Permission schemes list.
     *
     * @return permissionSchemes
     */
    public List<Map<String, Object>> permissionSchemes() {
        return this.permissionSchemes;
    }

    /**
     * Fluent setter for permissionSchemes.
     * <p>
     * Permission schemes list.
     *
     * @param permissionSchemes permissionSchemes
     * @return this
     */
    public PermissionSchemes permissionSchemes(List<Map<String, Object>> permissionSchemes) {
        this.permissionSchemes = permissionSchemes;
        return this;
    }

    /**
     * Gets the value of permissionSchemes.
     * <p>
     * Permission schemes list.
     *
     * @return permissionSchemes
     */
    @JsonProperty("permissionSchemes")
    public List<Map<String, Object>> getPermissionSchemes() {
        return this.permissionSchemes;
    }

    /**
     * Sets the value of permissionSchemes.
     * <p>
     * Permission schemes list.
     *
     * @param permissionSchemes permissionSchemes
     */
    public void setPermissionSchemes(List<Map<String, Object>> permissionSchemes) {
        this.permissionSchemes = permissionSchemes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PermissionSchemes that = (PermissionSchemes) o;
        return
            Objects.equals(this.permissionSchemes, that.permissionSchemes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.permissionSchemes
        );
    }

    @Override
    public String toString() {
        return "PermissionSchemes{"
            + "permissionSchemes=" + permissionSchemes
            + "}";
    }
}
