// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * PropertyKey
 * <p>
 * Property key details.
 *
 */
@JsonTypeName("PropertyKey")
@JsonPropertyOrder({
    "key",
    "self"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PropertyKey {

    /**
     * The key of the property.
     */
    @JsonProperty("key")
    protected String key;

    /**
     * The URL of the property.
     */
    @JsonProperty("self")
    protected String self;

    /**
     * Constructs a validated instance of {@link PropertyKey}.
     *
     * @param spec the specification to process
     */
    public PropertyKey(Consumer<PropertyKey> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected PropertyKey() {
    }
    /**
     * Constructs a validated instance of {@link PropertyKey}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PropertyKey(Consumer)} instead.
     * @param key The key of the property.
     * @param self The URL of the property.
     */
    @ApiStatus.Internal
    public PropertyKey(String key, String self) {
        this.key = key;
        this.self = self;
    }


    /**
     * Fluent getter for key.
     * <p>
     * The key of the property.
     *
     * @return key
     */
    public String key() {
        return this.key;
    }

    /**
     * Fluent setter for key.
     * <p>
     * The key of the property.
     *
     * @param key key
     * @return this
     */
    public PropertyKey key(String key) {
        this.key = key;
        return this;
    }

    /**
     * Gets the value of key.
     * <p>
     * The key of the property.
     *
     * @return key
     */
    @JsonProperty("key")
    public String getKey() {
        return this.key;
    }

    /**
     * Sets the value of key.
     * <p>
     * The key of the property.
     *
     * @param key key
     */
    public void setKey(String key) {
        this.key = key;
    }
    /**
     * Fluent getter for self.
     * <p>
     * The URL of the property.
     *
     * @return self
     */
    public String self() {
        return this.self;
    }

    /**
     * Fluent setter for self.
     * <p>
     * The URL of the property.
     *
     * @param self self
     * @return this
     */
    public PropertyKey self(String self) {
        this.self = self;
        return this;
    }

    /**
     * Gets the value of self.
     * <p>
     * The URL of the property.
     *
     * @return self
     */
    @JsonProperty("self")
    public String getSelf() {
        return this.self;
    }

    /**
     * Sets the value of self.
     * <p>
     * The URL of the property.
     *
     * @param self self
     */
    public void setSelf(String self) {
        this.self = self;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PropertyKey that = (PropertyKey) o;
        return
            Objects.equals(this.key, that.key) &&
            Objects.equals(this.self, that.self);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.key, 
            this.self
        );
    }

    @Override
    public String toString() {
        return "PropertyKey{"
            + "key=" + key + ", "
            + "self=" + self
            + "}";
    }
}
