// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * RolePayload
 * <p>
 * The payload used to create a project role. It is optional for CMP projects, as a default role actor will be provided. TMP will add new role actors to the table.
 *
 */
@JsonTypeName("RolePayload")
@JsonPropertyOrder({
    "defaultActors",
    "description",
    "name",
    "onConflict",
    "pcri",
    "type"
})
@Generated(value = "io.github.primelib.primecodegen")
public class RolePayload {

    /**
     * The default actors for the role. By adding default actors, the role will be added to any future projects created
     */
    @JsonProperty("defaultActors")
    protected List<ProjectCreateResourceIdentifier> defaultActors;

    /**
     * The description of the role
     */
    @JsonProperty("description")
    protected String description;

    /**
     * The name of the role
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters
     */
    @JsonProperty("onConflict")
    protected String onConflict;

    /**
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     */
    @JsonProperty("pcri")
    protected ProjectCreateResourceIdentifier pcri;

    /**
     * The type of the role. Only used by project-scoped project
     */
    @JsonProperty("type")
    protected String type;

    /**
     * Constructs a validated instance of {@link RolePayload}.
     *
     * @param spec the specification to process
     */
    public RolePayload(Consumer<RolePayload> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected RolePayload() {
    }
    /**
     * Constructs a validated instance of {@link RolePayload}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #RolePayload(Consumer)} instead.
     * @param defaultActors The default actors for the role. By adding default actors, the role will be added to any future projects created
     * @param description The description of the role
     * @param name The name of the role
     * @param onConflict The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters
     * @param pcri Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     * @param type The type of the role. Only used by project-scoped project
     */
    @ApiStatus.Internal
    public RolePayload(List<ProjectCreateResourceIdentifier> defaultActors, String description, String name, String onConflict, ProjectCreateResourceIdentifier pcri, String type) {
        this.defaultActors = defaultActors;
        this.description = description;
        this.name = name;
        this.onConflict = onConflict;
        this.pcri = pcri;
        this.type = type;
    }


    /**
     * Fluent getter for defaultActors.
     * <p>
     * The default actors for the role. By adding default actors, the role will be added to any future projects created
     *
     * @return defaultActors
     */
    public List<ProjectCreateResourceIdentifier> defaultActors() {
        return this.defaultActors;
    }

    /**
     * Fluent setter for defaultActors.
     * <p>
     * The default actors for the role. By adding default actors, the role will be added to any future projects created
     *
     * @param defaultActors defaultActors
     * @return this
     */
    public RolePayload defaultActors(List<ProjectCreateResourceIdentifier> defaultActors) {
        this.defaultActors = defaultActors;
        return this;
    }

    /**
     * Gets the value of defaultActors.
     * <p>
     * The default actors for the role. By adding default actors, the role will be added to any future projects created
     *
     * @return defaultActors
     */
    @JsonProperty("defaultActors")
    public List<ProjectCreateResourceIdentifier> getDefaultActors() {
        return this.defaultActors;
    }

    /**
     * Sets the value of defaultActors.
     * <p>
     * The default actors for the role. By adding default actors, the role will be added to any future projects created
     *
     * @param defaultActors defaultActors
     */
    public void setDefaultActors(List<ProjectCreateResourceIdentifier> defaultActors) {
        this.defaultActors = defaultActors;
    }
    /**
     * Fluent getter for description.
     * <p>
     * The description of the role
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the role
     *
     * @param description description
     * @return this
     */
    public RolePayload description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the role
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the role
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the role
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the role
     *
     * @param name name
     * @return this
     */
    public RolePayload name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the role
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the role
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for onConflict.
     * <p>
     * The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters
     *
     * @return onConflict
     */
    public String onConflict() {
        return this.onConflict;
    }

    /**
     * Fluent setter for onConflict.
     * <p>
     * The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters
     *
     * @param onConflict onConflict
     * @return this
     */
    public RolePayload onConflict(String onConflict) {
        this.onConflict = onConflict;
        return this;
    }

    /**
     * Gets the value of onConflict.
     * <p>
     * The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters
     *
     * @return onConflict
     */
    @JsonProperty("onConflict")
    public String getOnConflict() {
        return this.onConflict;
    }

    /**
     * Sets the value of onConflict.
     * <p>
     * The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters
     *
     * @param onConflict onConflict
     */
    public void setOnConflict(String onConflict) {
        this.onConflict = onConflict;
    }
    /**
     * Fluent getter for pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @return pcri
     */
    public ProjectCreateResourceIdentifier pcri() {
        return this.pcri;
    }

    /**
     * Fluent setter for pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @param pcri pcri
     * @return this
     */
    public RolePayload pcri(ProjectCreateResourceIdentifier pcri) {
        this.pcri = pcri;
        return this;
    }

    /**
     * Gets the value of pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @return pcri
     */
    @JsonProperty("pcri")
    public ProjectCreateResourceIdentifier getPcri() {
        return this.pcri;
    }

    /**
     * Sets the value of pcri.
     * <p>
     * Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation
     *
     * @param pcri pcri
     */
    public void setPcri(ProjectCreateResourceIdentifier pcri) {
        this.pcri = pcri;
    }
    /**
     * Fluent getter for type.
     * <p>
     * The type of the role. Only used by project-scoped project
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     * <p>
     * The type of the role. Only used by project-scoped project
     *
     * @param type type
     * @return this
     */
    public RolePayload type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     * <p>
     * The type of the role. Only used by project-scoped project
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     * <p>
     * The type of the role. Only used by project-scoped project
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RolePayload that = (RolePayload) o;
        return
            Objects.equals(this.defaultActors, that.defaultActors) &&
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.onConflict, that.onConflict) &&
            Objects.equals(this.pcri, that.pcri) &&
            Objects.equals(this.type, that.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.defaultActors, 
            this.description, 
            this.name, 
            this.onConflict, 
            this.pcri, 
            this.type
        );
    }

    @Override
    public String toString() {
        return "RolePayload{"
            + "defaultActors=" + defaultActors + ", "
            + "description=" + description + ", "
            + "name=" + name + ", "
            + "onConflict=" + onConflict + ", "
            + "pcri=" + pcri + ", "
            + "type=" + type
            + "}";
    }
}
