// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SearchAutoCompleteFilter
 * <p>
 * Details of how to filter and list search auto complete information.
 *
 */
@JsonTypeName("SearchAutoCompleteFilter")
@JsonPropertyOrder({
    "includeCollapsedFields",
    "projectIds"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SearchAutoCompleteFilter {

    /**
     * Include collapsed fields for fields that have non-unique names.
     */
    @JsonProperty("includeCollapsedFields")
    protected Boolean includeCollapsedFields;

    /**
     * List of project IDs used to filter the visible field details returned.
     */
    @JsonProperty("projectIds")
    protected List<Long> projectIds;

    /**
     * Constructs a validated instance of {@link SearchAutoCompleteFilter}.
     *
     * @param spec the specification to process
     */
    public SearchAutoCompleteFilter(Consumer<SearchAutoCompleteFilter> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SearchAutoCompleteFilter() {
    }
    /**
     * Constructs a validated instance of {@link SearchAutoCompleteFilter}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SearchAutoCompleteFilter(Consumer)} instead.
     * @param includeCollapsedFields Include collapsed fields for fields that have non-unique names.
     * @param projectIds List of project IDs used to filter the visible field details returned.
     */
    @ApiStatus.Internal
    public SearchAutoCompleteFilter(Boolean includeCollapsedFields, List<Long> projectIds) {
        this.includeCollapsedFields = includeCollapsedFields;
        this.projectIds = projectIds;
    }


    /**
     * Fluent getter for includeCollapsedFields.
     * <p>
     * Include collapsed fields for fields that have non-unique names.
     *
     * @return includeCollapsedFields
     */
    public Boolean includeCollapsedFields() {
        return this.includeCollapsedFields;
    }

    /**
     * Fluent setter for includeCollapsedFields.
     * <p>
     * Include collapsed fields for fields that have non-unique names.
     *
     * @param includeCollapsedFields includeCollapsedFields
     * @return this
     */
    public SearchAutoCompleteFilter includeCollapsedFields(Boolean includeCollapsedFields) {
        this.includeCollapsedFields = includeCollapsedFields;
        return this;
    }

    /**
     * Gets the value of includeCollapsedFields.
     * <p>
     * Include collapsed fields for fields that have non-unique names.
     *
     * @return includeCollapsedFields
     */
    @JsonProperty("includeCollapsedFields")
    public Boolean getIncludeCollapsedFields() {
        return this.includeCollapsedFields;
    }

    /**
     * Sets the value of includeCollapsedFields.
     * <p>
     * Include collapsed fields for fields that have non-unique names.
     *
     * @param includeCollapsedFields includeCollapsedFields
     */
    public void setIncludeCollapsedFields(Boolean includeCollapsedFields) {
        this.includeCollapsedFields = includeCollapsedFields;
    }
    /**
     * Fluent getter for projectIds.
     * <p>
     * List of project IDs used to filter the visible field details returned.
     *
     * @return projectIds
     */
    public List<Long> projectIds() {
        return this.projectIds;
    }

    /**
     * Fluent setter for projectIds.
     * <p>
     * List of project IDs used to filter the visible field details returned.
     *
     * @param projectIds projectIds
     * @return this
     */
    public SearchAutoCompleteFilter projectIds(List<Long> projectIds) {
        this.projectIds = projectIds;
        return this;
    }

    /**
     * Gets the value of projectIds.
     * <p>
     * List of project IDs used to filter the visible field details returned.
     *
     * @return projectIds
     */
    @JsonProperty("projectIds")
    public List<Long> getProjectIds() {
        return this.projectIds;
    }

    /**
     * Sets the value of projectIds.
     * <p>
     * List of project IDs used to filter the visible field details returned.
     *
     * @param projectIds projectIds
     */
    public void setProjectIds(List<Long> projectIds) {
        this.projectIds = projectIds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SearchAutoCompleteFilter that = (SearchAutoCompleteFilter) o;
        return
            Objects.equals(this.includeCollapsedFields, that.includeCollapsedFields) &&
            Objects.equals(this.projectIds, that.projectIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.includeCollapsedFields, 
            this.projectIds
        );
    }

    @Override
    public String toString() {
        return "SearchAutoCompleteFilter{"
            + "includeCollapsedFields=" + includeCollapsedFields + ", "
            + "projectIds=" + projectIds
            + "}";
    }
}
