// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SecurityLevelMember
 * <p>
 * Issue security level member.
 *
 */
@JsonTypeName("SecurityLevelMember")
@JsonPropertyOrder({
    "holder",
    "id",
    "issueSecurityLevelId",
    "issueSecuritySchemeId",
    "managed"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SecurityLevelMember {

    /**
     * The user or group being granted the permission. It consists of a `type` and a type-dependent `parameter`. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
     */
    @JsonProperty("holder")
    protected Object holder;

    /**
     * The ID of the issue security level member.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The ID of the issue security level.
     */
    @JsonProperty("issueSecurityLevelId")
    protected String issueSecurityLevelId;

    /**
     * The ID of the issue security scheme.
     */
    @JsonProperty("issueSecuritySchemeId")
    protected String issueSecuritySchemeId;

    @JsonProperty("managed")
    protected Boolean managed;

    /**
     * Constructs a validated instance of {@link SecurityLevelMember}.
     *
     * @param spec the specification to process
     */
    public SecurityLevelMember(Consumer<SecurityLevelMember> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SecurityLevelMember() {
    }
    /**
     * Constructs a validated instance of {@link SecurityLevelMember}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SecurityLevelMember(Consumer)} instead.
     * @param holder The user or group being granted the permission. It consists of a `type` and a type-dependent `parameter`. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
     * @param id The ID of the issue security level member.
     * @param issueSecurityLevelId The ID of the issue security level.
     * @param issueSecuritySchemeId The ID of the issue security scheme.
     * @param managed managed
     */
    @ApiStatus.Internal
    public SecurityLevelMember(Object holder, String id, String issueSecurityLevelId, String issueSecuritySchemeId, Boolean managed) {
        this.holder = holder;
        this.id = id;
        this.issueSecurityLevelId = issueSecurityLevelId;
        this.issueSecuritySchemeId = issueSecuritySchemeId;
        this.managed = managed;
    }


    /**
     * Fluent getter for holder.
     * <p>
     * The user or group being granted the permission. It consists of a `type` and a type-dependent `parameter`. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
     *
     * @return holder
     */
    public Object holder() {
        return this.holder;
    }

    /**
     * Fluent setter for holder.
     * <p>
     * The user or group being granted the permission. It consists of a `type` and a type-dependent `parameter`. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
     *
     * @param holder holder
     * @return this
     */
    public SecurityLevelMember holder(Object holder) {
        this.holder = holder;
        return this;
    }

    /**
     * Gets the value of holder.
     * <p>
     * The user or group being granted the permission. It consists of a `type` and a type-dependent `parameter`. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
     *
     * @return holder
     */
    @JsonProperty("holder")
    public Object getHolder() {
        return this.holder;
    }

    /**
     * Sets the value of holder.
     * <p>
     * The user or group being granted the permission. It consists of a `type` and a type-dependent `parameter`. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
     *
     * @param holder holder
     */
    public void setHolder(Object holder) {
        this.holder = holder;
    }
    /**
     * Fluent getter for id.
     * <p>
     * The ID of the issue security level member.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The ID of the issue security level member.
     *
     * @param id id
     * @return this
     */
    public SecurityLevelMember id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The ID of the issue security level member.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The ID of the issue security level member.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * Fluent getter for issueSecurityLevelId.
     * <p>
     * The ID of the issue security level.
     *
     * @return issueSecurityLevelId
     */
    public String issueSecurityLevelId() {
        return this.issueSecurityLevelId;
    }

    /**
     * Fluent setter for issueSecurityLevelId.
     * <p>
     * The ID of the issue security level.
     *
     * @param issueSecurityLevelId issueSecurityLevelId
     * @return this
     */
    public SecurityLevelMember issueSecurityLevelId(String issueSecurityLevelId) {
        this.issueSecurityLevelId = issueSecurityLevelId;
        return this;
    }

    /**
     * Gets the value of issueSecurityLevelId.
     * <p>
     * The ID of the issue security level.
     *
     * @return issueSecurityLevelId
     */
    @JsonProperty("issueSecurityLevelId")
    public String getIssueSecurityLevelId() {
        return this.issueSecurityLevelId;
    }

    /**
     * Sets the value of issueSecurityLevelId.
     * <p>
     * The ID of the issue security level.
     *
     * @param issueSecurityLevelId issueSecurityLevelId
     */
    public void setIssueSecurityLevelId(String issueSecurityLevelId) {
        this.issueSecurityLevelId = issueSecurityLevelId;
    }
    /**
     * Fluent getter for issueSecuritySchemeId.
     * <p>
     * The ID of the issue security scheme.
     *
     * @return issueSecuritySchemeId
     */
    public String issueSecuritySchemeId() {
        return this.issueSecuritySchemeId;
    }

    /**
     * Fluent setter for issueSecuritySchemeId.
     * <p>
     * The ID of the issue security scheme.
     *
     * @param issueSecuritySchemeId issueSecuritySchemeId
     * @return this
     */
    public SecurityLevelMember issueSecuritySchemeId(String issueSecuritySchemeId) {
        this.issueSecuritySchemeId = issueSecuritySchemeId;
        return this;
    }

    /**
     * Gets the value of issueSecuritySchemeId.
     * <p>
     * The ID of the issue security scheme.
     *
     * @return issueSecuritySchemeId
     */
    @JsonProperty("issueSecuritySchemeId")
    public String getIssueSecuritySchemeId() {
        return this.issueSecuritySchemeId;
    }

    /**
     * Sets the value of issueSecuritySchemeId.
     * <p>
     * The ID of the issue security scheme.
     *
     * @param issueSecuritySchemeId issueSecuritySchemeId
     */
    public void setIssueSecuritySchemeId(String issueSecuritySchemeId) {
        this.issueSecuritySchemeId = issueSecuritySchemeId;
    }
    /**
     * Fluent getter for managed.
     *
     * @return managed
     */
    public Boolean managed() {
        return this.managed;
    }

    /**
     * Fluent setter for managed.
     *
     * @param managed managed
     * @return this
     */
    public SecurityLevelMember managed(Boolean managed) {
        this.managed = managed;
        return this;
    }

    /**
     * Gets the value of managed.
     *
     * @return managed
     */
    @JsonProperty("managed")
    public Boolean getManaged() {
        return this.managed;
    }

    /**
     * Sets the value of managed.
     *
     * @param managed managed
     */
    public void setManaged(Boolean managed) {
        this.managed = managed;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SecurityLevelMember that = (SecurityLevelMember) o;
        return
            Objects.equals(this.holder, that.holder) &&
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.issueSecurityLevelId, that.issueSecurityLevelId) &&
            Objects.equals(this.issueSecuritySchemeId, that.issueSecuritySchemeId) &&
            Objects.equals(this.managed, that.managed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.holder, 
            this.id, 
            this.issueSecurityLevelId, 
            this.issueSecuritySchemeId, 
            this.managed
        );
    }

    @Override
    public String toString() {
        return "SecurityLevelMember{"
            + "holder=" + holder + ", "
            + "id=" + id + ", "
            + "issueSecurityLevelId=" + issueSecurityLevelId + ", "
            + "issueSecuritySchemeId=" + issueSecuritySchemeId + ", "
            + "managed=" + managed
            + "}";
    }
}
