// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * StatusWorkflowUsageWorkflow
 * <p>
 * The worflow.
 *
 */
@JsonTypeName("StatusWorkflowUsageWorkflow")
@JsonPropertyOrder({
    "id"
})
@Generated(value = "io.github.primelib.primecodegen")
public class StatusWorkflowUsageWorkflow {

    /**
     * The workflow ID.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * Constructs a validated instance of {@link StatusWorkflowUsageWorkflow}.
     *
     * @param spec the specification to process
     */
    public StatusWorkflowUsageWorkflow(Consumer<StatusWorkflowUsageWorkflow> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected StatusWorkflowUsageWorkflow() {
    }
    /**
     * Constructs a validated instance of {@link StatusWorkflowUsageWorkflow}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #StatusWorkflowUsageWorkflow(Consumer)} instead.
     * @param id The workflow ID.
     */
    @ApiStatus.Internal
    public StatusWorkflowUsageWorkflow(String id) {
        this.id = id;
    }


    /**
     * Fluent getter for id.
     * <p>
     * The workflow ID.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The workflow ID.
     *
     * @param id id
     * @return this
     */
    public StatusWorkflowUsageWorkflow id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The workflow ID.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The workflow ID.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StatusWorkflowUsageWorkflow that = (StatusWorkflowUsageWorkflow) o;
        return
            Objects.equals(this.id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.id
        );
    }

    @Override
    public String toString() {
        return "StatusWorkflowUsageWorkflow{"
            + "id=" + id
            + "}";
    }
}
