// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * UnrestrictedUserEmail
 *
 */
@JsonTypeName("UnrestrictedUserEmail")
@JsonPropertyOrder({
    "accountId",
    "email"
})
@Generated(value = "io.github.primelib.primecodegen")
public class UnrestrictedUserEmail {

    /**
     * The accountId of the user
     */
    @JsonProperty("accountId")
    protected String accountId;

    /**
     * The email of the user
     */
    @JsonProperty("email")
    protected String email;

    /**
     * Constructs a validated instance of {@link UnrestrictedUserEmail}.
     *
     * @param spec the specification to process
     */
    public UnrestrictedUserEmail(Consumer<UnrestrictedUserEmail> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected UnrestrictedUserEmail() {
    }
    /**
     * Constructs a validated instance of {@link UnrestrictedUserEmail}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #UnrestrictedUserEmail(Consumer)} instead.
     * @param accountId The accountId of the user
     * @param email The email of the user
     */
    @ApiStatus.Internal
    public UnrestrictedUserEmail(String accountId, String email) {
        this.accountId = accountId;
        this.email = email;
    }


    /**
     * Fluent getter for accountId.
     * <p>
     * The accountId of the user
     *
     * @return accountId
     */
    public String accountId() {
        return this.accountId;
    }

    /**
     * Fluent setter for accountId.
     * <p>
     * The accountId of the user
     *
     * @param accountId accountId
     * @return this
     */
    public UnrestrictedUserEmail accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Gets the value of accountId.
     * <p>
     * The accountId of the user
     *
     * @return accountId
     */
    @JsonProperty("accountId")
    public String getAccountId() {
        return this.accountId;
    }

    /**
     * Sets the value of accountId.
     * <p>
     * The accountId of the user
     *
     * @param accountId accountId
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }
    /**
     * Fluent getter for email.
     * <p>
     * The email of the user
     *
     * @return email
     */
    public String email() {
        return this.email;
    }

    /**
     * Fluent setter for email.
     * <p>
     * The email of the user
     *
     * @param email email
     * @return this
     */
    public UnrestrictedUserEmail email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Gets the value of email.
     * <p>
     * The email of the user
     *
     * @return email
     */
    @JsonProperty("email")
    public String getEmail() {
        return this.email;
    }

    /**
     * Sets the value of email.
     * <p>
     * The email of the user
     *
     * @param email email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UnrestrictedUserEmail that = (UnrestrictedUserEmail) o;
        return
            Objects.equals(this.accountId, that.accountId) &&
            Objects.equals(this.email, that.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.accountId, 
            this.email
        );
    }

    @Override
    public String toString() {
        return "UnrestrictedUserEmail{"
            + "accountId=" + accountId + ", "
            + "email=" + email
            + "}";
    }
}
