// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * UpdateScreenDetails
 * <p>
 * Details of a screen.
 *
 */
@JsonTypeName("UpdateScreenDetails")
@JsonPropertyOrder({
    "description",
    "name"
})
@Generated(value = "io.github.primelib.primecodegen")
public class UpdateScreenDetails {

    /**
     * The description of the screen. The maximum length is 255 characters.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * The name of the screen. The name must be unique. The maximum length is 255 characters.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Constructs a validated instance of {@link UpdateScreenDetails}.
     *
     * @param spec the specification to process
     */
    public UpdateScreenDetails(Consumer<UpdateScreenDetails> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected UpdateScreenDetails() {
    }
    /**
     * Constructs a validated instance of {@link UpdateScreenDetails}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #UpdateScreenDetails(Consumer)} instead.
     * @param description The description of the screen. The maximum length is 255 characters.
     * @param name The name of the screen. The name must be unique. The maximum length is 255 characters.
     */
    @ApiStatus.Internal
    public UpdateScreenDetails(String description, String name) {
        this.description = description;
        this.name = name;
    }


    /**
     * Fluent getter for description.
     * <p>
     * The description of the screen. The maximum length is 255 characters.
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the screen. The maximum length is 255 characters.
     *
     * @param description description
     * @return this
     */
    public UpdateScreenDetails description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the screen. The maximum length is 255 characters.
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the screen. The maximum length is 255 characters.
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the screen. The name must be unique. The maximum length is 255 characters.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the screen. The name must be unique. The maximum length is 255 characters.
     *
     * @param name name
     * @return this
     */
    public UpdateScreenDetails name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the screen. The name must be unique. The maximum length is 255 characters.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the screen. The name must be unique. The maximum length is 255 characters.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UpdateScreenDetails that = (UpdateScreenDetails) o;
        return
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.name, that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.description, 
            this.name
        );
    }

    @Override
    public String toString() {
        return "UpdateScreenDetails{"
            + "description=" + description + ", "
            + "name=" + name
            + "}";
    }
}
