// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * VersionIssuesStatus
 * <p>
 * Counts of the number of issues in various statuses.
 *
 */
@JsonTypeName("VersionIssuesStatus")
@JsonPropertyOrder({
    "done",
    "inProgress",
    "toDo",
    "unmapped"
})
@Generated(value = "io.github.primelib.primecodegen")
public class VersionIssuesStatus {

    /**
     * Count of issues with status *done*.
     */
    @JsonProperty("done")
    protected Long done;

    /**
     * Count of issues with status *in progress*.
     */
    @JsonProperty("inProgress")
    protected Long inProgress;

    /**
     * Count of issues with status *to do*.
     */
    @JsonProperty("toDo")
    protected Long toDo;

    /**
     * Count of issues with a status other than *to do*, *in progress*, and *done*.
     */
    @JsonProperty("unmapped")
    protected Long unmapped;

    /**
     * Constructs a validated instance of {@link VersionIssuesStatus}.
     *
     * @param spec the specification to process
     */
    public VersionIssuesStatus(Consumer<VersionIssuesStatus> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected VersionIssuesStatus() {
    }
    /**
     * Constructs a validated instance of {@link VersionIssuesStatus}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #VersionIssuesStatus(Consumer)} instead.
     * @param done Count of issues with status *done*.
     * @param inProgress Count of issues with status *in progress*.
     * @param toDo Count of issues with status *to do*.
     * @param unmapped Count of issues with a status other than *to do*, *in progress*, and *done*.
     */
    @ApiStatus.Internal
    public VersionIssuesStatus(Long done, Long inProgress, Long toDo, Long unmapped) {
        this.done = done;
        this.inProgress = inProgress;
        this.toDo = toDo;
        this.unmapped = unmapped;
    }


    /**
     * Fluent getter for done.
     * <p>
     * Count of issues with status *done*.
     *
     * @return done
     */
    public Long done() {
        return this.done;
    }

    /**
     * Fluent setter for done.
     * <p>
     * Count of issues with status *done*.
     *
     * @param done done
     * @return this
     */
    public VersionIssuesStatus done(Long done) {
        this.done = done;
        return this;
    }

    /**
     * Gets the value of done.
     * <p>
     * Count of issues with status *done*.
     *
     * @return done
     */
    @JsonProperty("done")
    public Long getDone() {
        return this.done;
    }

    /**
     * Sets the value of done.
     * <p>
     * Count of issues with status *done*.
     *
     * @param done done
     */
    public void setDone(Long done) {
        this.done = done;
    }
    /**
     * Fluent getter for inProgress.
     * <p>
     * Count of issues with status *in progress*.
     *
     * @return inProgress
     */
    public Long inProgress() {
        return this.inProgress;
    }

    /**
     * Fluent setter for inProgress.
     * <p>
     * Count of issues with status *in progress*.
     *
     * @param inProgress inProgress
     * @return this
     */
    public VersionIssuesStatus inProgress(Long inProgress) {
        this.inProgress = inProgress;
        return this;
    }

    /**
     * Gets the value of inProgress.
     * <p>
     * Count of issues with status *in progress*.
     *
     * @return inProgress
     */
    @JsonProperty("inProgress")
    public Long getInProgress() {
        return this.inProgress;
    }

    /**
     * Sets the value of inProgress.
     * <p>
     * Count of issues with status *in progress*.
     *
     * @param inProgress inProgress
     */
    public void setInProgress(Long inProgress) {
        this.inProgress = inProgress;
    }
    /**
     * Fluent getter for toDo.
     * <p>
     * Count of issues with status *to do*.
     *
     * @return toDo
     */
    public Long toDo() {
        return this.toDo;
    }

    /**
     * Fluent setter for toDo.
     * <p>
     * Count of issues with status *to do*.
     *
     * @param toDo toDo
     * @return this
     */
    public VersionIssuesStatus toDo(Long toDo) {
        this.toDo = toDo;
        return this;
    }

    /**
     * Gets the value of toDo.
     * <p>
     * Count of issues with status *to do*.
     *
     * @return toDo
     */
    @JsonProperty("toDo")
    public Long getToDo() {
        return this.toDo;
    }

    /**
     * Sets the value of toDo.
     * <p>
     * Count of issues with status *to do*.
     *
     * @param toDo toDo
     */
    public void setToDo(Long toDo) {
        this.toDo = toDo;
    }
    /**
     * Fluent getter for unmapped.
     * <p>
     * Count of issues with a status other than *to do*, *in progress*, and *done*.
     *
     * @return unmapped
     */
    public Long unmapped() {
        return this.unmapped;
    }

    /**
     * Fluent setter for unmapped.
     * <p>
     * Count of issues with a status other than *to do*, *in progress*, and *done*.
     *
     * @param unmapped unmapped
     * @return this
     */
    public VersionIssuesStatus unmapped(Long unmapped) {
        this.unmapped = unmapped;
        return this;
    }

    /**
     * Gets the value of unmapped.
     * <p>
     * Count of issues with a status other than *to do*, *in progress*, and *done*.
     *
     * @return unmapped
     */
    @JsonProperty("unmapped")
    public Long getUnmapped() {
        return this.unmapped;
    }

    /**
     * Sets the value of unmapped.
     * <p>
     * Count of issues with a status other than *to do*, *in progress*, and *done*.
     *
     * @param unmapped unmapped
     */
    public void setUnmapped(Long unmapped) {
        this.unmapped = unmapped;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VersionIssuesStatus that = (VersionIssuesStatus) o;
        return
            Objects.equals(this.done, that.done) &&
            Objects.equals(this.inProgress, that.inProgress) &&
            Objects.equals(this.toDo, that.toDo) &&
            Objects.equals(this.unmapped, that.unmapped);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.done, 
            this.inProgress, 
            this.toDo, 
            this.unmapped
        );
    }

    @Override
    public String toString() {
        return "VersionIssuesStatus{"
            + "done=" + done + ", "
            + "inProgress=" + inProgress + ", "
            + "toDo=" + toDo + ", "
            + "unmapped=" + unmapped
            + "}";
    }
}
