// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * WorkflowMetadataRestModel
 * <p>
 * Workflow metadata and usage detail.
 *
 */
@JsonTypeName("WorkflowMetadataRestModel")
@JsonPropertyOrder({
    "description",
    "id",
    "name",
    "version"
})
@Generated(value = "io.github.primelib.primecodegen")
public class WorkflowMetadataRestModel {

    /**
     * The description of the workflow.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * The ID of the workflow.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The name of the workflow.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The current version details of this workflow scheme.
     */
    @JsonProperty("version")
    protected DocumentVersion version;

    /**
     * Constructs a validated instance of {@link WorkflowMetadataRestModel}.
     *
     * @param spec the specification to process
     */
    public WorkflowMetadataRestModel(Consumer<WorkflowMetadataRestModel> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected WorkflowMetadataRestModel() {
    }
    /**
     * Constructs a validated instance of {@link WorkflowMetadataRestModel}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #WorkflowMetadataRestModel(Consumer)} instead.
     * @param description The description of the workflow.
     * @param id The ID of the workflow.
     * @param name The name of the workflow.
     * @param version The current version details of this workflow scheme.
     */
    @ApiStatus.Internal
    public WorkflowMetadataRestModel(String description, String id, String name, DocumentVersion version) {
        this.description = description;
        this.id = id;
        this.name = name;
        this.version = version;
    }


    /**
     * Fluent getter for description.
     * <p>
     * The description of the workflow.
     *
     * @return description
     */
    public String description() {
        return this.description;
    }

    /**
     * Fluent setter for description.
     * <p>
     * The description of the workflow.
     *
     * @param description description
     * @return this
     */
    public WorkflowMetadataRestModel description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Gets the value of description.
     * <p>
     * The description of the workflow.
     *
     * @return description
     */
    @JsonProperty("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the value of description.
     * <p>
     * The description of the workflow.
     *
     * @param description description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Fluent getter for id.
     * <p>
     * The ID of the workflow.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The ID of the workflow.
     *
     * @param id id
     * @return this
     */
    public WorkflowMetadataRestModel id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The ID of the workflow.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The ID of the workflow.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * Fluent getter for name.
     * <p>
     * The name of the workflow.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the workflow.
     *
     * @param name name
     * @return this
     */
    public WorkflowMetadataRestModel name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the workflow.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the workflow.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for version.
     * <p>
     * The current version details of this workflow scheme.
     *
     * @return version
     */
    public DocumentVersion version() {
        return this.version;
    }

    /**
     * Fluent setter for version.
     * <p>
     * The current version details of this workflow scheme.
     *
     * @param version version
     * @return this
     */
    public WorkflowMetadataRestModel version(DocumentVersion version) {
        this.version = version;
        return this;
    }

    /**
     * Gets the value of version.
     * <p>
     * The current version details of this workflow scheme.
     *
     * @return version
     */
    @JsonProperty("version")
    public DocumentVersion getVersion() {
        return this.version;
    }

    /**
     * Sets the value of version.
     * <p>
     * The current version details of this workflow scheme.
     *
     * @param version version
     */
    public void setVersion(DocumentVersion version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        WorkflowMetadataRestModel that = (WorkflowMetadataRestModel) o;
        return
            Objects.equals(this.description, that.description) &&
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.version, that.version);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.description, 
            this.id, 
            this.name, 
            this.version
        );
    }

    @Override
    public String toString() {
        return "WorkflowMetadataRestModel{"
            + "description=" + description + ", "
            + "id=" + id + ", "
            + "name=" + name + ", "
            + "version=" + version
            + "}";
    }
}
