// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * WorkflowTransitionRulesUpdateErrors
 * <p>
 * Details of any errors encountered while updating workflow transition rules.
 *
 */
@JsonTypeName("WorkflowTransitionRulesUpdateErrors")
@JsonPropertyOrder({
    "updateResults"
})
@Generated(value = "io.github.primelib.primecodegen")
public class WorkflowTransitionRulesUpdateErrors {

    /**
     * A list of workflows.
     */
    @JsonProperty("updateResults")
    protected List<WorkflowTransitionRulesUpdateErrorDetails> updateResults;

    /**
     * Constructs a validated instance of {@link WorkflowTransitionRulesUpdateErrors}.
     *
     * @param spec the specification to process
     */
    public WorkflowTransitionRulesUpdateErrors(Consumer<WorkflowTransitionRulesUpdateErrors> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected WorkflowTransitionRulesUpdateErrors() {
    }
    /**
     * Constructs a validated instance of {@link WorkflowTransitionRulesUpdateErrors}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #WorkflowTransitionRulesUpdateErrors(Consumer)} instead.
     * @param updateResults A list of workflows.
     */
    @ApiStatus.Internal
    public WorkflowTransitionRulesUpdateErrors(List<WorkflowTransitionRulesUpdateErrorDetails> updateResults) {
        this.updateResults = updateResults;
    }


    /**
     * Fluent getter for updateResults.
     * <p>
     * A list of workflows.
     *
     * @return updateResults
     */
    public List<WorkflowTransitionRulesUpdateErrorDetails> updateResults() {
        return this.updateResults;
    }

    /**
     * Fluent setter for updateResults.
     * <p>
     * A list of workflows.
     *
     * @param updateResults updateResults
     * @return this
     */
    public WorkflowTransitionRulesUpdateErrors updateResults(List<WorkflowTransitionRulesUpdateErrorDetails> updateResults) {
        this.updateResults = updateResults;
        return this;
    }

    /**
     * Gets the value of updateResults.
     * <p>
     * A list of workflows.
     *
     * @return updateResults
     */
    @JsonProperty("updateResults")
    public List<WorkflowTransitionRulesUpdateErrorDetails> getUpdateResults() {
        return this.updateResults;
    }

    /**
     * Sets the value of updateResults.
     * <p>
     * A list of workflows.
     *
     * @param updateResults updateResults
     */
    public void setUpdateResults(List<WorkflowTransitionRulesUpdateErrorDetails> updateResults) {
        this.updateResults = updateResults;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        WorkflowTransitionRulesUpdateErrors that = (WorkflowTransitionRulesUpdateErrors) o;
        return
            Objects.equals(this.updateResults, that.updateResults);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.updateResults
        );
    }

    @Override
    public String toString() {
        return "WorkflowTransitionRulesUpdateErrors{"
            + "updateResults=" + updateResults
            + "}";
    }
}
