// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.client;

import io.github.primelib.jira.datacenter.client.JiraDataCenterClientFactorySpec;
import io.github.primelib.jira.datacenter.client.models.ErrorCollection;
import io.github.primelib.jira.datacenter.client.models.ProjectDataPolicies;
import io.github.primelib.jira.datacenter.client.models.WorkspaceDataPolicy;
import io.github.primelib.jira.datacenter.client.operations.Get2DataPolicyProjectV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2DataPolicyV1OperationSpec;
import io.github.primelib.jira.datacenter.client.responses.Get2DataPolicyProjectV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2DataPolicyV1Response;
import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.dataformat.xml.XmlMapper;

/**
 * JiraDataCenterClientAppDataPoliciesApi
 *
 * This resource represents app access rule data policies.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraDataCenterClientAppDataPoliciesApi extends AbstractJiraDataCenterClientApiClient {

    public JiraDataCenterClientAppDataPoliciesApi(JiraDataCenterClientFactorySpec<?> spec, OkHttpClient httpClient, JsonMapper jsonMapper, XmlMapper xmlMapper) {
        super(spec, httpClient, jsonMapper, xmlMapper);
    }


    /**
     * Get2DataPolicyV1
     * Get data policy for the workspace
     * Returns data policy for the workspace.
     *
     * API Method: GET /rest/api/2/data-policy
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2DataPolicyV1Response get2DataPolicyV1(Consumer<Get2DataPolicyV1OperationSpec> spec) {
        Get2DataPolicyV1OperationSpec r = new Get2DataPolicyV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("data-policy");

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<WorkspaceDataPolicy>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2DataPolicyV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2DataPolicyProjectV1
     * Get data policy for projects
     * Returns data policies for the projects specified in the request.
     *
     * API Method: GET /rest/api/2/data-policy/project
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>ids: A list of project identifiers. This parameter accepts a comma-separated list.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2DataPolicyProjectV1Response get2DataPolicyProjectV1(Consumer<Get2DataPolicyProjectV1OperationSpec> spec) {
        Get2DataPolicyProjectV1OperationSpec r = new Get2DataPolicyProjectV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("data-policy");
        pathBuilder.append("/").append("project");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "ids", r.ids());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyProjectV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<ProjectDataPolicies>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyProjectV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyProjectV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2DataPolicyProjectV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2DataPolicyProjectV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


}
