// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.client;

import io.github.primelib.jira.datacenter.client.JiraDataCenterClientFactorySpec;
import io.github.primelib.jira.datacenter.client.models.ErrorCollection;
import io.github.primelib.jira.datacenter.client.models.NotificationScheme;
import io.github.primelib.jira.datacenter.client.models.PageBeanNotificationScheme;
import io.github.primelib.jira.datacenter.client.models.PageBeanNotificationSchemeAndProjectMappingJsonBean;
import io.github.primelib.jira.datacenter.client.operations.Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Delete2NotificationschemeByNotificationSchemeIdV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2NotificationschemeByIdV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2NotificationschemeProjectV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2NotificationschemeV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Post2NotificationschemeV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Put2NotificationschemeByIdNotificationV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Put2NotificationschemeByIdV1OperationSpec;
import io.github.primelib.jira.datacenter.client.responses.Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response;
import io.github.primelib.jira.datacenter.client.responses.Delete2NotificationschemeByNotificationSchemeIdV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2NotificationschemeByIdV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2NotificationschemeProjectV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2NotificationschemeV1Response;
import io.github.primelib.jira.datacenter.client.responses.Post2NotificationschemeV1Response;
import io.github.primelib.jira.datacenter.client.responses.Put2NotificationschemeByIdNotificationV1Response;
import io.github.primelib.jira.datacenter.client.responses.Put2NotificationschemeByIdV1Response;
import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.dataformat.xml.XmlMapper;

/**
 * JiraDataCenterClientIssueNotificationSchemesApi
 *
 * This resource represents notification schemes, lists of events and the recipients who will receive notifications for those events. Use it to get details of a notification scheme and a list of notification schemes.
 * 
 * ### About notification schemes ###
 * 
 * A notification scheme is a list of events and recipients who will receive notifications for those events. The list is contained within the `notificationSchemeEvents` object and contains pairs of `events` and `notifications`:
 * 
 *  *  `event` Identifies the type of event. The events can be [Jira system events](https://support.atlassian.com/jira-cloud-administration/docs/configure-notification-schemes/) (see the *Events* section) or [custom events](https://support.atlassian.com/jira-cloud-administration/docs/add-a-custom-event/).
 *  *  `notifications` Identifies the [recipients](https://confluence.atlassian.com/x/8YdKLg#Creatinganotificationscheme-recipientsRecipients) of notifications for each event. Recipients can be any of the following types:
 *     
 *      *  `CurrentAssignee`
 *      *  `Reporter`
 *      *  `CurrentUser`
 *      *  `ProjectLead`
 *      *  `ComponentLead`
 *      *  `User` (the `parameter` is the user key)
 *      *  `Group` (the `parameter` is the group name)
 *      *  `ProjectRole` (the `parameter` is the project role ID)
 *      *  `EmailAddress` *(deprecated)*
 *      *  `AllWatchers`
 *      *  `UserCustomField` (the `parameter` is the ID of the custom field)
 *      *  `GroupCustomField`(the `parameter` is the ID of the custom field)
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraDataCenterClientIssueNotificationSchemesApi extends AbstractJiraDataCenterClientApiClient {

    public JiraDataCenterClientIssueNotificationSchemesApi(JiraDataCenterClientFactorySpec<?> spec, OkHttpClient httpClient, JsonMapper jsonMapper, XmlMapper xmlMapper) {
        super(spec, httpClient, jsonMapper, xmlMapper);
    }


    /**
     * Get2NotificationschemeV1
     * Get notification schemes paginated
     * Returns a [paginated](#pagination) list of [notification schemes](https://confluence.atlassian.com/x/8YdKLg) ordered by the display name.
    * 
    * *Note that you should allow for events without recipients to appear in responses.*
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira, however, the user must have permission to administer at least one project associated with a notification scheme for it to be returned.
     *
     * API Method: GET /rest/api/2/notificationscheme
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>id: The list of notification schemes IDs to be filtered by</li>
     *   <li>projectId: The list of projects IDs to be filtered by</li>
     *   <li>onlyDefault: When set to true, returns only the default notification scheme. If you provide project IDs not associated with the default, returns an empty page. The default value is false.</li>
     *   <li>expand: Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:   *  `all` Returns all expandable information  *  `field` Returns information about any custom fields assigned to receive an event  *  `group` Returns information about any groups assigned to receive an event  *  `notificationSchemeEvents` Returns a list of event associations. This list is returned for all expandable information  *  `projectRole` Returns information about any project roles assigned to receive an event  *  `user` Returns information about any users assigned to receive an event</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2NotificationschemeV1Response get2NotificationschemeV1(Consumer<Get2NotificationschemeV1OperationSpec> spec) {
        Get2NotificationschemeV1OperationSpec r = new Get2NotificationschemeV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());
        addQueryParam(queryParams, "id", r.id());
        addQueryParam(queryParams, "projectId", r.projectId());
        addQueryParam(queryParams, "onlyDefault", r.onlyDefault());
        addQueryParam(queryParams, "expand", r.expand());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2NotificationschemeV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<PageBeanNotificationScheme>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2NotificationschemeV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<String>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2NotificationschemeV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Post2NotificationschemeV1
     * Create notification scheme
     * Creates a notification scheme with notifications. You can create up to 1000 notifications per request.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: POST /rest/api/2/notificationscheme
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Post2NotificationschemeV1Response post2NotificationschemeV1(Consumer<Post2NotificationschemeV1OperationSpec> spec) {
        Post2NotificationschemeV1OperationSpec r = new Post2NotificationschemeV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Content-Type", "application/json");
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), true);
        String contentType = getHeader(operationHeaders, "Content-Type");
        RequestBody requestBody = buildRequestBody(r.payload(), contentType);
        requestBuilder.method("POST", requestBody);

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "201")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Post2NotificationschemeV1Response.CreatedResponse(
                deserializeBody(info.body(), new TypeReference<Map<String, Object>>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Post2NotificationschemeV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Post2NotificationschemeV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Post2NotificationschemeV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Post2NotificationschemeV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2NotificationschemeProjectV1
     * Get projects using notification schemes paginated
     * Returns a [paginated](#pagination) mapping of project that have notification scheme assigned. You can provide either one or multiple notification scheme IDs or project IDs to filter by. If you don't provide any, this will return a list of all mappings. Note that only company-managed (classic) projects are supported. This is because team-managed projects don't have a concept of a default notification scheme. The mappings are ordered by projectId.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira.
     *
     * API Method: GET /rest/api/2/notificationscheme/project
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>notificationSchemeId: The list of notifications scheme IDs to be filtered out</li>
     *   <li>projectId: The list of project IDs to be filtered out</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2NotificationschemeProjectV1Response get2NotificationschemeProjectV1(Consumer<Get2NotificationschemeProjectV1OperationSpec> spec) {
        Get2NotificationschemeProjectV1OperationSpec r = new Get2NotificationschemeProjectV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");
        pathBuilder.append("/").append("project");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());
        addQueryParam(queryParams, "notificationSchemeId", r.notificationSchemeId());
        addQueryParam(queryParams, "projectId", r.projectId());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2NotificationschemeProjectV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<PageBeanNotificationSchemeAndProjectMappingJsonBean>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2NotificationschemeProjectV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2NotificationschemeProjectV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2NotificationschemeProjectV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2NotificationschemeByIdV1
     * Get notification scheme
     * Returns a [notification scheme](https://confluence.atlassian.com/x/8YdKLg), including the list of events and the recipients who will receive notifications for those events.
    * 
    * **[Permissions](#permissions) required:** Permission to access Jira, however, the user must have permission to administer at least one project associated with the notification scheme.
     *
     * API Method: GET /rest/api/2/notificationscheme/{id}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>id: The ID of the notification scheme. Use [Get notification schemes paginated](#api-rest-api-2-notificationscheme-get) to get a list of notification scheme IDs.</li>
     *   <li>expand: Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:   *  `all` Returns all expandable information  *  `field` Returns information about any custom fields assigned to receive an event  *  `group` Returns information about any groups assigned to receive an event  *  `notificationSchemeEvents` Returns a list of event associations. This list is returned for all expandable information  *  `projectRole` Returns information about any project roles assigned to receive an event  *  `user` Returns information about any users assigned to receive an event</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2NotificationschemeByIdV1Response get2NotificationschemeByIdV1(Consumer<Get2NotificationschemeByIdV1OperationSpec> spec) {
        Get2NotificationschemeByIdV1OperationSpec r = new Get2NotificationschemeByIdV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");
        pathBuilder.append("/").append(urlEncode(String.valueOf(r.id())));

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "expand", r.expand());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2NotificationschemeByIdV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<NotificationScheme>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2NotificationschemeByIdV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Put2NotificationschemeByIdV1
     * Update notification scheme
     * Updates a notification scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/notificationscheme/{id}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>id: The ID of the notification scheme.</li>
     *   <li>payload: </li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Put2NotificationschemeByIdV1Response put2NotificationschemeByIdV1(Consumer<Put2NotificationschemeByIdV1OperationSpec> spec) {
        Put2NotificationschemeByIdV1OperationSpec r = new Put2NotificationschemeByIdV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");
        pathBuilder.append("/").append(urlEncode(String.valueOf(r.id())));

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Content-Type", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), true);
        String contentType = getHeader(operationHeaders, "Content-Type");
        RequestBody requestBody = buildRequestBody(r.payload(), contentType);
        requestBuilder.method("PUT", requestBody);

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "204")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdV1Response.NoContentResponse(
                deserializeBody(info.body(), new TypeReference<Object>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "404")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdV1Response.NotFoundResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Put2NotificationschemeByIdV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Put2NotificationschemeByIdNotificationV1
     * Add notifications to notification scheme
     * Adds notifications to a notification scheme. You can add up to 1000 notifications per request.
    * 
    * *Deprecated: The notification type `EmailAddress` is no longer supported in Cloud. Refer to the [changelog](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-1031) for more details.*
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/notificationscheme/{id}/notification
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>id: The ID of the notification scheme.</li>
     *   <li>payload: </li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Put2NotificationschemeByIdNotificationV1Response put2NotificationschemeByIdNotificationV1(Consumer<Put2NotificationschemeByIdNotificationV1OperationSpec> spec) {
        Put2NotificationschemeByIdNotificationV1OperationSpec r = new Put2NotificationschemeByIdNotificationV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");
        pathBuilder.append("/").append(urlEncode(String.valueOf(r.id())));
        pathBuilder.append("/").append("notification");

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Content-Type", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), true);
        String contentType = getHeader(operationHeaders, "Content-Type");
        RequestBody requestBody = buildRequestBody(r.payload(), contentType);
        requestBuilder.method("PUT", requestBody);

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "204")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdNotificationV1Response.NoContentResponse(
                deserializeBody(info.body(), new TypeReference<Object>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdNotificationV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdNotificationV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdNotificationV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "404")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2NotificationschemeByIdNotificationV1Response.NotFoundResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Put2NotificationschemeByIdNotificationV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Delete2NotificationschemeByNotificationSchemeIdV1
     * Delete notification scheme
     * Deletes a notification scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/notificationscheme/{notificationSchemeId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>notificationSchemeId: The ID of the notification scheme.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Delete2NotificationschemeByNotificationSchemeIdV1Response delete2NotificationschemeByNotificationSchemeIdV1(Consumer<Delete2NotificationschemeByNotificationSchemeIdV1OperationSpec> spec) {
        Delete2NotificationschemeByNotificationSchemeIdV1OperationSpec r = new Delete2NotificationschemeByNotificationSchemeIdV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");
        pathBuilder.append("/").append(urlEncode(String.valueOf(r.notificationSchemeId())));

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("DELETE", bodyForMethodWithoutPayload("DELETE"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "204")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdV1Response.NoContentResponse(
                deserializeBody(info.body(), new TypeReference<Object>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "404")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdV1Response.NotFoundResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Delete2NotificationschemeByNotificationSchemeIdV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1
     * Remove notification from notification scheme
     * Removes a notification from a notification scheme.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/notificationscheme/{notificationSchemeId}/notification/{notificationId}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>notificationSchemeId: The ID of the notification scheme.</li>
     *   <li>notificationId: The ID of the notification.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1(Consumer<Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1OperationSpec> spec) {
        Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1OperationSpec r = new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("notificationscheme");
        pathBuilder.append("/").append(urlEncode(String.valueOf(r.notificationSchemeId())));
        pathBuilder.append("/").append("notification");
        pathBuilder.append("/").append(urlEncode(String.valueOf(r.notificationId())));

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("DELETE", bodyForMethodWithoutPayload("DELETE"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "204")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response.NoContentResponse(
                deserializeBody(info.body(), new TypeReference<Object>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "404")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response.NotFoundResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Delete2NotificationschemeByNotificationSchemeIdNotificationByNotificationIdV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


}
