// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.client;

import io.github.primelib.jira.datacenter.client.JiraDataCenterClientFactorySpec;
import io.github.primelib.jira.datacenter.client.models.ErrorCollection;
import io.github.primelib.jira.datacenter.client.models.FoundUsers;
import io.github.primelib.jira.datacenter.client.models.PageBeanUser;
import io.github.primelib.jira.datacenter.client.models.PageBeanUserKey;
import io.github.primelib.jira.datacenter.client.models.User;
import io.github.primelib.jira.datacenter.client.operations.Get2UserAssignableMultiProjectSearchV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserAssignableSearchV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserPermissionSearchV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserPickerV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserSearchQueryKeyV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserSearchQueryV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserSearchV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Get2UserViewissueSearchV1OperationSpec;
import io.github.primelib.jira.datacenter.client.responses.Get2UserAssignableMultiProjectSearchV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserAssignableSearchV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserPermissionSearchV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserPickerV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserSearchQueryKeyV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserSearchQueryV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserSearchV1Response;
import io.github.primelib.jira.datacenter.client.responses.Get2UserViewissueSearchV1Response;
import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.dataformat.xml.XmlMapper;

/**
 * JiraDataCenterClientUserSearchApi
 *
 * This resource represents various ways to search for and find users. Use it to obtain list of users including users assignable to projects and issues, users with permissions, user lists for pickup fields, and user lists generated using structured queries. Note that the operations in this resource only return users found within the first 1000 users.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraDataCenterClientUserSearchApi extends AbstractJiraDataCenterClientApiClient {

    public JiraDataCenterClientUserSearchApi(JiraDataCenterClientFactorySpec<?> spec, OkHttpClient httpClient, JsonMapper jsonMapper, XmlMapper xmlMapper) {
        super(spec, httpClient, jsonMapper, xmlMapper);
    }


    /**
     * Get2UserAssignableMultiProjectSearchV1
     * Find users assignable to projects
     * Returns a list of users who can be assigned issues in one or more projects. The list may be restricted to users whose attributes match a string.
    * 
    * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that can be assigned issues in the projects. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who can be assigned issues in the projects, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for each project specified in `projectKeys`.
     *
     * API Method: GET /rest/api/2/user/assignable/multiProjectSearch
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A query string that is matched against user attributes, such as `displayName` and `emailAddress`, to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*. Required, unless `accountId` is specified.</li>
     *   <li>username: This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.</li>
     *   <li>accountId: A query string that is matched exactly against user `accountId`. Required, unless `query` is specified.</li>
     *   <li>projectKeys: A list of project keys (case sensitive). This parameter accepts a comma-separated list.</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserAssignableMultiProjectSearchV1Response get2UserAssignableMultiProjectSearchV1(Consumer<Get2UserAssignableMultiProjectSearchV1OperationSpec> spec) {
        Get2UserAssignableMultiProjectSearchV1OperationSpec r = new Get2UserAssignableMultiProjectSearchV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("assignable");
        pathBuilder.append("/").append("multiProjectSearch");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "username", r.username());
        addQueryParam(queryParams, "accountId", r.accountId());
        addQueryParam(queryParams, "projectKeys", r.projectKeys());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserAssignableMultiProjectSearchV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<List<User>>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserAssignableMultiProjectSearchV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserAssignableSearchV1
     * Find users assignable to issues
     * Returns a list of users that can be assigned to an issue. Use this operation to find the list of users who can be assigned to:
    * 
    *  *  a new issue, by providing the `projectKeyOrId`.
    *  *  an updated issue, by providing the `issueKey` or `issueId`.
    *  *  to an issue during a transition (workflow action), by providing the `issueKey` or `issueId` and the transition id in `actionDescriptorId`. You can obtain the IDs of an issue's valid transitions using the `transitions` option in the `expand` parameter of [ Get issue](#api-rest-api-2-issue-issueIdOrKey-get).
    * 
    * In all these cases, you can pass an account ID to determine if a user can be assigned to an issue. The user is returned in the response if they can be assigned to the issue or issue transition.
    * 
    * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that can be assigned the issue. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who can be assigned the issue, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
    * 
    * **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg) or *Assign issues* [project permission](https://confluence.atlassian.com/x/yodKLg)
     *
     * API Method: GET /rest/api/2/user/assignable/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A query string that is matched against user attributes, such as `displayName`, and `emailAddress`, to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*. Required, unless `username` or `accountId` is specified.</li>
     *   <li>sessionId: The sessionId of this request. SessionId is the same until the assignee is set.</li>
     *   <li>username: This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.</li>
     *   <li>accountId: A query string that is matched exactly against user `accountId`. Required, unless `query` is specified.</li>
     *   <li>project: The project ID or project key (case sensitive). Required, unless `issueKey` or `issueId` is specified.</li>
     *   <li>issueKey: The key of the issue. Required, unless `issueId` or `project` is specified.</li>
     *   <li>issueId: The ID of the issue. Required, unless `issueKey` or `project` is specified.</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return. This operation may return less than the maximum number of items even if more are available. The operation fetches users up to the maximum and then, from the fetched users, returns only the users that can be assigned to the issue.</li>
     *   <li>actionDescriptorId: The ID of the transition.</li>
     *   <li>recommend: </li>
     *   <li>accountType: </li>
     *   <li>appType: </li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserAssignableSearchV1Response get2UserAssignableSearchV1(Consumer<Get2UserAssignableSearchV1OperationSpec> spec) {
        Get2UserAssignableSearchV1OperationSpec r = new Get2UserAssignableSearchV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("assignable");
        pathBuilder.append("/").append("search");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "sessionId", r.sessionId());
        addQueryParam(queryParams, "username", r.username());
        addQueryParam(queryParams, "accountId", r.accountId());
        addQueryParam(queryParams, "project", r.project());
        addQueryParam(queryParams, "issueKey", r.issueKey());
        addQueryParam(queryParams, "issueId", r.issueId());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());
        addQueryParam(queryParams, "actionDescriptorId", r.actionDescriptorId());
        addQueryParam(queryParams, "recommend", r.recommend());
        addQueryParam(queryParams, "accountType", r.accountType());
        addQueryParam(queryParams, "appType", r.appType());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserAssignableSearchV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<List<User>>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserAssignableSearchV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserPermissionSearchV1
     * Find users with permissions
     * Returns a list of users who fulfill these criteria:
    * 
    *  *  their user attributes match a search string.
    *  *  they have a set of permissions for a project or issue.
    * 
    * If no search string is provided, a list of all users with the permissions is returned.
    * 
    * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the search string and have permission for the project or issue. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the search string and have permission for the project or issue, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:**
    * 
    *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), to get users for any project.
    *  *  *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for a project, to get users for that project.
     *
     * API Method: GET /rest/api/2/user/permission/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A query string that is matched against user attributes, such as `displayName` and `emailAddress`, to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*. Required, unless `accountId` is specified.</li>
     *   <li>username: This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.</li>
     *   <li>accountId: A query string that is matched exactly against user `accountId`. Required, unless `query` is specified.</li>
     *   <li>permissions: A comma separated list of permissions. Permissions can be specified as any:   *  permission returned by [Get all permissions](#api-rest-api-2-permissions-get).  *  custom project permission added by Connect apps.  *  (deprecated) one of the following:           *  ASSIGNABLE\_USER      *  ASSIGN\_ISSUE      *  ATTACHMENT\_DELETE\_ALL      *  ATTACHMENT\_DELETE\_OWN      *  BROWSE      *  CLOSE\_ISSUE      *  COMMENT\_DELETE\_ALL      *  COMMENT\_DELETE\_OWN      *  COMMENT\_EDIT\_ALL      *  COMMENT\_EDIT\_OWN      *  COMMENT\_ISSUE      *  CREATE\_ATTACHMENT      *  CREATE\_ISSUE      *  DELETE\_ISSUE      *  EDIT\_ISSUE      *  LINK\_ISSUE      *  MANAGE\_WATCHER\_LIST      *  MODIFY\_REPORTER      *  MOVE\_ISSUE      *  PROJECT\_ADMIN      *  RESOLVE\_ISSUE      *  SCHEDULE\_ISSUE      *  SET\_ISSUE\_SECURITY      *  TRANSITION\_ISSUE      *  VIEW\_VERSION\_CONTROL      *  VIEW\_VOTERS\_AND\_WATCHERS      *  VIEW\_WORKFLOW\_READONLY      *  WORKLOG\_DELETE\_ALL      *  WORKLOG\_DELETE\_OWN      *  WORKLOG\_EDIT\_ALL      *  WORKLOG\_EDIT\_OWN      *  WORK\_ISSUE</li>
     *   <li>issueKey: The issue key for the issue.</li>
     *   <li>projectKey: The project key for the project (case sensitive).</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserPermissionSearchV1Response get2UserPermissionSearchV1(Consumer<Get2UserPermissionSearchV1OperationSpec> spec) {
        Get2UserPermissionSearchV1OperationSpec r = new Get2UserPermissionSearchV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("permission");
        pathBuilder.append("/").append("search");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "username", r.username());
        addQueryParam(queryParams, "accountId", r.accountId());
        addQueryParam(queryParams, "permissions", r.permissions());
        addQueryParam(queryParams, "issueKey", r.issueKey());
        addQueryParam(queryParams, "projectKey", r.projectKey());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserPermissionSearchV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<List<User>>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserPermissionSearchV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserPickerV1
     * Find users for picker
     * Returns a list of users whose attributes match the query term. The returned object includes the `html` field where the matched query term is highlighted with the HTML strong tag. A list of account IDs can be provided to exclude users from the results.
    * 
    * This operation takes the users in the range defined by `maxResults`, up to the thousandth user, and then returns only the users from that range that match the query term. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the query term, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg). Anonymous calls and calls by users without the required permission return search results for an exact name match only.
     *
     * API Method: GET /rest/api/2/user/picker
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A query string that is matched against user attributes, such as `displayName`, and `emailAddress`, to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*.</li>
     *   <li>maxResults: The maximum number of items to return. The total number of matched users is returned in `total`.</li>
     *   <li>showAvatar: Include the URI to the user's avatar.</li>
     *   <li>exclude: This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.</li>
     *   <li>excludeAccountIds: A list of account IDs to exclude from the search results. This parameter accepts a comma-separated list. Multiple account IDs can also be provided using an ampersand-separated list. For example, `excludeAccountIds=5b10a2844c20165700ede21g,5b10a0effa615349cb016cd8&amp;excludeAccountIds=5b10ac8d82e05b22cc7d4ef5`. Cannot be provided with `exclude`.</li>
     *   <li>avatarSize: </li>
     *   <li>excludeConnectUsers: </li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserPickerV1Response get2UserPickerV1(Consumer<Get2UserPickerV1OperationSpec> spec) {
        Get2UserPickerV1OperationSpec r = new Get2UserPickerV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("picker");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "maxResults", r.maxResults());
        addQueryParam(queryParams, "showAvatar", r.showAvatar());
        addQueryParam(queryParams, "exclude", r.exclude());
        addQueryParam(queryParams, "excludeAccountIds", r.excludeAccountIds());
        addQueryParam(queryParams, "avatarSize", r.avatarSize());
        addQueryParam(queryParams, "excludeConnectUsers", r.excludeConnectUsers());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserPickerV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<FoundUsers>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserPickerV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserSearchV1
     * Find users
     * Returns a list of active users that match the search string and property.
    * 
    * This operation first applies a filter to match the search string and property, and then takes the filtered users in the range defined by `startAt` and `maxResults`, up to the thousandth user. To get all the users who match the search string and property, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * This operation can be accessed anonymously.
    * 
    * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
    * 
    * **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg). Anonymous calls or calls by users without the required permission return empty search results.
     *
     * API Method: GET /rest/api/2/user/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A query string that is matched against user attributes ( `displayName`, and `emailAddress`) to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*. Required, unless `accountId` or `property` is specified.</li>
     *   <li>username: </li>
     *   <li>accountId: A query string that is matched exactly against a user `accountId`. Required, unless `query` or `property` is specified.</li>
     *   <li>startAt: The index of the first item to return in a page of filtered results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>property: A query string used to search properties. Property keys are specified by path, so property keys containing dot (.) or equals (=) characters cannot be used. The query string cannot be specified using a JSON object. Example: To search for the value of `nested` from `{"something":{"nested":1,"other":2}}` use `thepropertykey.something.nested=1`. Required, unless `accountId` or `query` is specified.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserSearchV1Response get2UserSearchV1(Consumer<Get2UserSearchV1OperationSpec> spec) {
        Get2UserSearchV1OperationSpec r = new Get2UserSearchV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("search");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "username", r.username());
        addQueryParam(queryParams, "accountId", r.accountId());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());
        addQueryParam(queryParams, "property", r.property());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<List<User>>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserSearchV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserSearchQueryV1
     * Find users by query
     * Finds users with a structured query and returns a [paginated](#pagination) list of user details.
    * 
    * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the structured query. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the structured query, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    * 
    * The query statements are:
    * 
    *  *  `is assignee of PROJ` Returns the users that are assignees of at least one issue in project *PROJ*.
    *  *  `is assignee of (PROJ-1, PROJ-2)` Returns users that are assignees on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is reporter of (PROJ-1, PROJ-2)` Returns users that are reporters on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is watcher of (PROJ-1, PROJ-2)` Returns users that are watchers on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is voter of (PROJ-1, PROJ-2)` Returns users that are voters on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is commenter of (PROJ-1, PROJ-2)` Returns users that have posted a comment on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is transitioner of (PROJ-1, PROJ-2)` Returns users that have performed a transition on issues *PROJ-1* or *PROJ-2*.
    *  *  `[propertyKey].entity.property.path is "property value"` Returns users with the entity property value. For example, if user property `location` is set to value `{"office": {"country": "AU", "city": "Sydney"}}`, then it's possible to use `[location].office.city is "Sydney"` to match the user.
    * 
    * The list of issues can be extended as needed, as in *(PROJ-1, PROJ-2, ... PROJ-n)*. Statements can be combined using the `AND` and `OR` operators to form more complex queries. For example:
    * 
    * `is assignee of PROJ AND [propertyKey].entity.property.path is "property value"`
     *
     * API Method: GET /rest/api/2/user/search/query
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: The search query.</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserSearchQueryV1Response get2UserSearchQueryV1(Consumer<Get2UserSearchQueryV1OperationSpec> spec) {
        Get2UserSearchQueryV1OperationSpec r = new Get2UserSearchQueryV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("search");
        pathBuilder.append("/").append("query");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<PageBeanUser>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "408")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryV1Response.Status408Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserSearchQueryV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserSearchQueryKeyV1
     * Find user keys by query
     * Finds users with a structured query and returns a [paginated](#pagination) list of user keys.
    * 
    * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the structured query. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the structured query, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    * 
    * The query statements are:
    * 
    *  *  `is assignee of PROJ` Returns the users that are assignees of at least one issue in project *PROJ*.
    *  *  `is assignee of (PROJ-1, PROJ-2)` Returns users that are assignees on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is reporter of (PROJ-1, PROJ-2)` Returns users that are reporters on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is watcher of (PROJ-1, PROJ-2)` Returns users that are watchers on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is voter of (PROJ-1, PROJ-2)` Returns users that are voters on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is commenter of (PROJ-1, PROJ-2)` Returns users that have posted a comment on the issues *PROJ-1* or *PROJ-2*.
    *  *  `is transitioner of (PROJ-1, PROJ-2)` Returns users that have performed a transition on issues *PROJ-1* or *PROJ-2*.
    *  *  `[propertyKey].entity.property.path is "property value"` Returns users with the entity property value. For example, if user property `location` is set to value `{"office": {"country": "AU", "city": "Sydney"}}`, then it's possible to use `[location].office.city is "Sydney"` to match the user.
    * 
    * The list of issues can be extended as needed, as in *(PROJ-1, PROJ-2, ... PROJ-n)*. Statements can be combined using the `AND` and `OR` operators to form more complex queries. For example:
    * 
    * `is assignee of PROJ AND [propertyKey].entity.property.path is "property value"`
     *
     * API Method: GET /rest/api/2/user/search/query/key
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: The search query.</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResult: The maximum number of items to return per page.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserSearchQueryKeyV1Response get2UserSearchQueryKeyV1(Consumer<Get2UserSearchQueryKeyV1OperationSpec> spec) {
        Get2UserSearchQueryKeyV1OperationSpec r = new Get2UserSearchQueryKeyV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("search");
        pathBuilder.append("/").append("query");
        pathBuilder.append("/").append("key");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResult", r.maxResult());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryKeyV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<PageBeanUserKey>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "400")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryKeyV1Response.BadRequestResponse(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "401")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryKeyV1Response.Status401Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "403")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryKeyV1Response.Status403Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (matchesStatusCode(info.statusCode(), "408")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserSearchQueryKeyV1Response.Status408Response(
                deserializeBody(info.body(), new TypeReference<ErrorCollection>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserSearchQueryKeyV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Get2UserViewissueSearchV1
     * Find users with browse permission
     * Returns a list of users who fulfill these criteria:
    * 
    *  *  their user attributes match a search string.
    *  *  they have permission to browse issues.
    * 
    * Use this resource to find users who can browse:
    * 
    *  *  an issue, by providing the `issueKey`.
    *  *  any issue in a project, by providing the `projectKey`.
    * 
    * This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the search string and have permission to browse issues. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the search string and have permission to browse issues, use [Get all users](#api-rest-api-2-users-search-get) and filter the records in your code.
    * 
    * Privacy controls are applied to the response based on the users' preferences. This could mean, for example, that the user's email address is hidden. See the [Profile visibility overview](https://developer.atlassian.com/cloud/jira/platform/profile-visibility/) for more details.
    * 
    * This operation can be accessed anonymously.
    * 
    * **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg). Anonymous calls and calls by users without the required permission return empty search results.
     *
     * API Method: GET /rest/api/2/user/viewissue/search
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>query: A query string that is matched against user attributes, such as `displayName` and `emailAddress`, to find relevant users. The string can match the prefix of the attribute's value. For example, *query=john* matches a user with a `displayName` of *John Smith* and a user with an `emailAddress` of *johnson@example.com*. Required, unless `accountId` is specified.</li>
     *   <li>username: This parameter is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.</li>
     *   <li>accountId: A query string that is matched exactly against user `accountId`. Required, unless `query` is specified.</li>
     *   <li>issueKey: The issue key for the issue. Required, unless `projectKey` is specified.</li>
     *   <li>projectKey: The project key for the project (case sensitive). Required, unless `issueKey` is specified.</li>
     *   <li>startAt: The index of the first item to return in a page of results (page offset).</li>
     *   <li>maxResults: The maximum number of items to return per page.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Get2UserViewissueSearchV1Response get2UserViewissueSearchV1(Consumer<Get2UserViewissueSearchV1OperationSpec> spec) {
        Get2UserViewissueSearchV1OperationSpec r = new Get2UserViewissueSearchV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("user");
        pathBuilder.append("/").append("viewissue");
        pathBuilder.append("/").append("search");

        Map<String, List<String>> queryParams = newQueryParams();
        addQueryParam(queryParams, "query", r.query());
        addQueryParam(queryParams, "username", r.username());
        addQueryParam(queryParams, "accountId", r.accountId());
        addQueryParam(queryParams, "issueKey", r.issueKey());
        addQueryParam(queryParams, "projectKey", r.projectKey());
        addQueryParam(queryParams, "startAt", r.startAt());
        addQueryParam(queryParams, "maxResults", r.maxResults());

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Accept", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), false);
        requestBuilder.method("GET", bodyForMethodWithoutPayload("GET"));

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "200")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Get2UserViewissueSearchV1Response.OkResponse(
                deserializeBody(info.body(), new TypeReference<List<User>>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Get2UserViewissueSearchV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


}
