// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.client;

import io.github.primelib.jira.datacenter.client.JiraDataCenterClientFactorySpec;
import io.github.primelib.jira.datacenter.client.operations.Delete2FieldAssociationV1OperationSpec;
import io.github.primelib.jira.datacenter.client.operations.Put2FieldAssociationV1OperationSpec;
import io.github.primelib.jira.datacenter.client.responses.Delete2FieldAssociationV1Response;
import io.github.primelib.jira.datacenter.client.responses.Put2FieldAssociationV1Response;
import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.dataformat.xml.XmlMapper;

/**
 * JiraDataCenterClientIssueCustomFieldAssociationsApi
 *
 * This resource represents the fields associated to project and issue type contexts. Use it to:
 * 
 *  *  assign custom field to projects and issue types.
 */
@Generated(value = "io.github.primelib.primecodegen")
public class JiraDataCenterClientIssueCustomFieldAssociationsApi extends AbstractJiraDataCenterClientApiClient {

    public JiraDataCenterClientIssueCustomFieldAssociationsApi(JiraDataCenterClientFactorySpec<?> spec, OkHttpClient httpClient, JsonMapper jsonMapper, XmlMapper xmlMapper) {
        super(spec, httpClient, jsonMapper, xmlMapper);
    }


    /**
     * Put2FieldAssociationV1
     * Create associations
     * Associates fields with projects.
    * 
    * Fields will be associated with each issue type on the requested projects.
    * 
    * Fields will be associated with all projects that share the same field configuration which the provided projects are using. This means that while the field will be associated with the requested projects, it will also be associated with any other projects that share the same field configuration.
    * 
    * If a success response is returned it means that the field association has been created in any applicable contexts where it wasn't already present.
    * 
    * Up to 50 fields and up to 100 projects can be associated in a single request. If more fields or projects are provided a 400 response will be returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: PUT /rest/api/2/field/association
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: Payload containing the fields to associate and the projects to associate them to.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Put2FieldAssociationV1Response put2FieldAssociationV1(Consumer<Put2FieldAssociationV1OperationSpec> spec) {
        Put2FieldAssociationV1OperationSpec r = new Put2FieldAssociationV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("field");
        pathBuilder.append("/").append("association");

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Content-Type", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), true);
        String contentType = getHeader(operationHeaders, "Content-Type");
        RequestBody requestBody = buildRequestBody(r.payload(), contentType);
        requestBuilder.method("PUT", requestBody);

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "204")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Put2FieldAssociationV1Response.NoContentResponse(
                deserializeBody(info.body(), new TypeReference<Object>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Put2FieldAssociationV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


    /**
     * Delete2FieldAssociationV1
     * Remove associations
     * Unassociates a set of fields with a project and issue type context.
    * 
    * Fields will be unassociated with all projects/issue types that share the same field configuration which the provided project and issue types are using. This means that while the field will be unassociated with the provided project and issue types, it will also be unassociated with any other projects and issue types that share the same field configuration.
    * 
    * If a success response is returned it means that the field association has been removed in any applicable contexts where it was present.
    * 
    * Up to 50 fields and up to 100 projects and issue types can be unassociated in a single request. If more fields or projects are provided a 400 response will be returned.
    * 
    * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * API Method: DELETE /rest/api/2/field/association
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: Payload containing the fields to uassociate and the projects and issue types to unassociate them to.</li>
     *   <li>failOnError: throws a exception if the response has a status code of 4xx or 5xx</li>
     *   <li>extraHeaders: additional HTTP headers to include in this request</li>
     *   <li>extraQueryParams: additional query parameters to include in this request</li>
     *   <li>overrideAuthMethods / overrideAuthMethod: per-request authentication override</li>
     * </ul>
     */
    public Delete2FieldAssociationV1Response delete2FieldAssociationV1(Consumer<Delete2FieldAssociationV1OperationSpec> spec) {
        Delete2FieldAssociationV1OperationSpec r = new Delete2FieldAssociationV1OperationSpec(spec);

        StringBuilder pathBuilder = new StringBuilder();
        pathBuilder.append("/").append("rest");
        pathBuilder.append("/").append("api");
        pathBuilder.append("/").append("2");
        pathBuilder.append("/").append("field");
        pathBuilder.append("/").append("association");

        Map<String, List<String>> queryParams = newQueryParams();

        addAuthQueryParams(queryParams, r.overrideAuthMethods());

        Map<String, List<String>> operationHeaders = newHeaderParams();
        putHeader(operationHeaders, "Content-Type", "application/json");

        URI uri = buildUri(pathBuilder.toString(), queryParams, r.extraQueryParams());
        Request.Builder requestBuilder = newRequestBuilder(uri, operationHeaders, r.extraHeaders(), r.overrideAuthMethods(), true);
        String contentType = getHeader(operationHeaders, "Content-Type");
        RequestBody requestBody = buildRequestBody(r.payload(), contentType);
        requestBuilder.method("DELETE", requestBody);

        ResponseInfo info = executeRaw(requestBuilder.build());
        if (matchesStatusCode(info.statusCode(), "204")) {
            if (isErrorStatus(info.statusCode()) && r.failOnError()) {
                throw new ApiResponseException(info.statusCode(), info.body());
            }
            return new Delete2FieldAssociationV1Response.NoContentResponse(
                deserializeBody(info.body(), new TypeReference<Object>() {}),
                info.statusCode(),
                info.body(),
                info.headers()
            );
        }
        if (isErrorStatus(info.statusCode()) && r.failOnError()) {
            throw new ApiResponseException(info.statusCode(), info.body());
        }
        return new Delete2FieldAssociationV1Response.Unknown(info.statusCode(), info.body(), info.headers());
    }


}
