// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.responses;


import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Delete2MypreferencesV1Response
 * <p>
 * Deletes a preference of the user, which restores the default value of system defined settings.
 * 
 * Note that these keys are deprecated:
 * 
 *  *  *jira.user.locale* The locale of the user. By default, not set. The user takes the instance locale.
 *  *  *jira.user.timezone* The time zone of the user. By default, not set. The user takes the instance timezone.
 * 
 * Use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API to manage timezone and locale instead.
 * 
 * **[Permissions](#permissions) required:** Permission to access Jira.
 */
@Generated(value = "io.github.primelib.primecodegen")
public sealed interface Delete2MypreferencesV1Response {
    int statusCode();

    @Nullable
    String rawBody();

    @NonNull
    Map<String, List<String>> headers();


    record Unknown(
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Delete2MypreferencesV1Response {}

    /**
     * Tries to cast the response to {@link Unknown}.
     * @return The casted {@link Unknown} response.
     * @throws IllegalStateException If the actual response status code does not match.
     */
    default Unknown asUnknown() {
        if (this instanceof Unknown target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'Unknown', but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
}
