// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.responses;

import io.github.primelib.jira.datacenter.client.models.PageBeanIssueFieldOption;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Get2FieldByFieldKeyOptionSuggestionsSearchV1Response
 * <p>
 * Returns a [paginated](#pagination) list of options for a select list issue field that can be viewed by the user.
 * 
 * Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.
 * 
 * **[Permissions](#permissions) required:** Permission to access Jira.
 */
@Generated(value = "io.github.primelib.primecodegen")
public sealed interface Get2FieldByFieldKeyOptionSuggestionsSearchV1Response {
    int statusCode();

    @Nullable
    String rawBody();

    @NonNull
    Map<String, List<String>> headers();

    record OkResponse(
        PageBeanIssueFieldOption body,
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Get2FieldByFieldKeyOptionSuggestionsSearchV1Response {}

    record Unknown(
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Get2FieldByFieldKeyOptionSuggestionsSearchV1Response {}

    /**
    * Tries to cast the response to {@link OkResponse}.
    * @return The casted {@link OkResponse} response.
    * @throws IllegalStateException If the actual response status code does not match.
    */
    default OkResponse asOkResponse() {
        if (this instanceof OkResponse target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'OkResponse' (code 200), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }

    /**
     * Tries to cast the response to {@link Unknown}.
     * @return The casted {@link Unknown} response.
     * @throws IllegalStateException If the actual response status code does not match.
     */
    default Unknown asUnknown() {
        if (this instanceof Unknown target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'Unknown', but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
    /**
     * Extracts the payload data directly if the response represents a successful status code (200).
     * <p>
     * If the response is not a success status code, an {@link IllegalStateException} is thrown.
     *
     * @return The response data payload of type {@link PageBeanIssueFieldOption}.
     * @throws IllegalStateException If the response status code is not 200.
     */
    default PageBeanIssueFieldOption data() {
        if (this instanceof OkResponse target) {
            return target.body();
        }
        throw new IllegalStateException("Expected a successful response type 'OkResponse' (code 200), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
}
