// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.responses;

import io.github.primelib.jira.datacenter.client.models.Project;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Post2ProjectByProjectIdOrKeyRestoreV1Response
 * <p>
 * Restores a project that has been archived or placed in the Jira recycle bin.
 * 
 * **[Permissions](#permissions) required:**
 * 
 *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)for Company managed projects.
 *  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) or *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project for Team managed projects.
 */
@Generated(value = "io.github.primelib.primecodegen")
public sealed interface Post2ProjectByProjectIdOrKeyRestoreV1Response {
    int statusCode();

    @Nullable
    String rawBody();

    @NonNull
    Map<String, List<String>> headers();

    record OkResponse(
        Project body,
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Post2ProjectByProjectIdOrKeyRestoreV1Response {}

    record Unknown(
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Post2ProjectByProjectIdOrKeyRestoreV1Response {}

    /**
    * Tries to cast the response to {@link OkResponse}.
    * @return The casted {@link OkResponse} response.
    * @throws IllegalStateException If the actual response status code does not match.
    */
    default OkResponse asOkResponse() {
        if (this instanceof OkResponse target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'OkResponse' (code 200), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }

    /**
     * Tries to cast the response to {@link Unknown}.
     * @return The casted {@link Unknown} response.
     * @throws IllegalStateException If the actual response status code does not match.
     */
    default Unknown asUnknown() {
        if (this instanceof Unknown target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'Unknown', but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
    /**
     * Extracts the payload data directly if the response represents a successful status code (200).
     * <p>
     * If the response is not a success status code, an {@link IllegalStateException} is thrown.
     *
     * @return The response data payload of type {@link Project}.
     * @throws IllegalStateException If the response status code is not 200.
     */
    default Project data() {
        if (this instanceof OkResponse target) {
            return target.body();
        }
        throw new IllegalStateException("Expected a successful response type 'OkResponse' (code 200), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
}
