// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.jira.datacenter.client.responses;


import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Put2IssuetypeByIssueTypeIdPropertyByPropertyKeyV1Response
 * <p>
 * Creates or updates the value of the [issue type property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties). Use this resource to store and update data against an issue type.
 * 
 * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
 * 
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 */
@Generated(value = "io.github.primelib.primecodegen")
public sealed interface Put2IssuetypeByIssueTypeIdPropertyByPropertyKeyV1Response {
    int statusCode();

    @Nullable
    String rawBody();

    @NonNull
    Map<String, List<String>> headers();

    record OkResponse(
        Object body,
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Put2IssuetypeByIssueTypeIdPropertyByPropertyKeyV1Response {}
    record CreatedResponse(
        Object body,
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Put2IssuetypeByIssueTypeIdPropertyByPropertyKeyV1Response {}

    record Unknown(
        int statusCode,
        @Nullable String rawBody,
        @NonNull Map<String, List<String>> headers
    ) implements Put2IssuetypeByIssueTypeIdPropertyByPropertyKeyV1Response {}

    /**
    * Tries to cast the response to {@link OkResponse}.
    * @return The casted {@link OkResponse} response.
    * @throws IllegalStateException If the actual response status code does not match.
    */
    default OkResponse asOkResponse() {
        if (this instanceof OkResponse target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'OkResponse' (code 200), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }

    /**
    * Tries to cast the response to {@link CreatedResponse}.
    * @return The casted {@link CreatedResponse} response.
    * @throws IllegalStateException If the actual response status code does not match.
    */
    default CreatedResponse asCreatedResponse() {
        if (this instanceof CreatedResponse target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'CreatedResponse' (code 201), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }

    /**
     * Tries to cast the response to {@link Unknown}.
     * @return The casted {@link Unknown} response.
     * @throws IllegalStateException If the actual response status code does not match.
     */
    default Unknown asUnknown() {
        if (this instanceof Unknown target) {
            return target;
        }
        throw new IllegalStateException("Expected response type 'Unknown', but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
    /**
     * Extracts the payload data directly if the response represents a successful status code (201).
     * <p>
     * If the response is not a success status code, an {@link IllegalStateException} is thrown.
     *
     * @return The response data payload of type {@link Object}.
     * @throws IllegalStateException If the response status code is not 201.
     */
    default Object data() {
        if (this instanceof CreatedResponse target) {
            return target.body();
        }
        throw new IllegalStateException("Expected a successful response type 'CreatedResponse' (code 201), but got '" + this.getClass().getSimpleName() + "' (code " + statusCode() + "). Body: " + rawBody());
    }
}
